### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by GHNJ** [microsoft/presidio#1015]
Hi all, hopefully this is the correct place to post this question: 

when I call: 
    `redacted_dicom_image = engine.redact(f, fill="contrast")`

The output error I get is this: 
    venv\lib\site-packages\presidio_image_redactor\dicom_image_redactor_engine.py", line 198, in _check_if_greyscale    
    color_scale = instance[0x0028, 0x0004].value
    TypeError: string indices must be integers

Note: 
1. Prior to the redacted dicom image call, I have: `pydicom.dcmread(f)`
2. I checked the p10 and the PMI tag does exist and shows as: "MONOCHROME1"

Versions: 
pydicom==2.3.1
presidio-image-redactor==0.0.45
pydicom==2.3.1

Thanks for the help!

**Comment by niwilso** [comment]
Thank you for reporting this bug. I'm starting to look into this.

**Comment by niwilso** [comment]
To help with the debugging process, would you mind pasting the output of the following lines of code using the same loaded DICOM file?

```python
color_scale = redacted_dicom_image[0x0028, 0x0004].value
print(f"color_scale ({type(color_scale)}): {color_scale}")
```

**Comment by niwilso** [comment]
Also, what version of Python and what operating system are you using?

**Comment by niwilso** [comment]
Apologies, I meant to ask for information related to the loaded DICOM file. I suspect there may be something going wrong with either the loading or metadata representation. Please run the following updated code and paste the output when you have a moment:

```python
instance = pydicom.dcmread(f)
print(f"instance type: {type(instance)}")
print(f"int: {str(instance[40, 4])}")
print(f"hex: {str(instance[0x0028, 0x0004])}")
```

**Comment by niwilso** [comment]
Reminder:
- `.redact(instance)` is used to redact from a loaded DICOM instance
- `.redact_from_file(path_to_dicom_here, output_directory_here)` is used to redact from a DICOM file

**Comment by GHNJ** [comment]
I think you can close this issue out. I found that I was not providing the complete path to the DCM file and when I fixed that I was able to call .redact(instance) as expected, and the masks showed in the output p10 file. 

Thanks again for the help on this.

**Comment by GHNJ** [comment]
actually I opened it so I'll close it :)

**Comment by niwilso** [comment]
Glad the problem is resolved! This was also good feedback about error handling for the `DicomImageRedactorEngine` class, so I've added issue #1019 to address later. Have a great day :)
