### ISSUE TITLE
OpenAPI definition: Anonymizer list type in anonymize request does not reflect the underlying json data schema  

### ISSUE THREAD

**Issue by CodeRunRepeat** [microsoft/presidio#1016]
**Describe the bug**
The OpenAPI definition of the anonymize request reads as follows:

```yaml
anonymizers:
          description: "Object where the key is DEFAULT or the ENTITY_TYPE and the value is the anonymizer definition"
          type: object
          anyOf:
            - $ref: "#/components/schemas/Replace"
            - $ref: "#/components/schemas/Redact"
            - $ref: "#/components/schemas/Mask"
            - $ref: "#/components/schemas/Hash"
            - $ref: "#/components/schemas/Encrypt"
```
This translates to (and swagger-codegen agrees) as one of the Replace/Redact/etc. objects.
Actually, as also shown in the examples (e.g. [here](https://microsoft.github.io/presidio/api-docs/api-docs.html#tag/Anonymizer/paths/~1anonymize/post)), this field is effectively a map from a string (entity name) to one of these objects.

**To Reproduce**
Generate a client from the Open API file to e.g. Golang using swagger-codegen

**Expected behavior**
The generated AnonymizeRequest.Anonymizers field should have a map type.
Instead, it is a pointer to a single struct that represents a single anonymizer.
Check it out [here](https://github.com/CodeRunRepeat/presidio-go-client/blob/d11a58e6eab5da699312dc6572c21457f490c02b/src/generated/model_anonymize_request.go)

**Comment by SharonHart** [comment]
Also valid for the deanoniymize endpoint
