### ISSUE TITLE
Decryption for different file formats

### ISSUE THREAD

**Issue by rebeca-reyes** [microsoft/presidio#1039]
I have tested that Presidio is able to encrypt data in different file formats such as CSV, JSON, etc. Does Presidio allow for decryption of different file formats? No success in testing this so far.

**Comment by omri374** [comment]
Hi @rebeca-reyes, Presidio works on strings only, so in order to have it run on files, you'd have to read the file first, encrypt it, and save to file.

Would this solve the issue? or is there's anything I might be missing?

**Comment by rebeca-reyes** [comment]
Is the Deanonymize Engine able to decrypt file formats? We have been able to encrypt on files but cannot decrypt.

**Comment by omri374** [comment]
Presidio does not operate directly on files. First, a file needs to be read, and then Presidio should be applied to each value in that file.
For example, if the file contains this text:
`My name is David and I’m a data scientist`
Then Pyspark would be used to read the text file into a string, and then Presidio would encrypt it, resulting in:
`Hi I'm ubw4l8jvm7AWpSx/9oyglQgByahDFJBc5zRVrLiVKgA= and I'm a data scientist`
Plus some metadata.
 
Then, during decrypt, the metadata would be used to identify where in the text the cyphertext exists, and we would be able to decrypt it back to the original text.
 
If you have other types of files like CSV or parquet, then some processing of files into strings is required. This should be a simple operation on Synapse with Pyspark, for example when the file is read and each row/cell is sent to a UDF/pandas_udf similar to the one in the Synpase example you shared.
 
For CSVs specifically, we have [this example](https://github.com/microsoft/presidio/blob/main/docs/samples/python/batch_processing.ipynb) which demonstrates how to apply Presidio on every row/column, but it pretty much just runs the encrypt/decrypt on each cell similarly to the previous example.
