### ISSUE TITLE
Problem importing presidio-analyzer

### ISSUE THREAD

**Issue by ArthurOliveiraTeles** [microsoft/presidio#1076]
Hello, apparently there was an error in your library "presidio-analyzer". Until yesterday, everything worked perfectly, however today, when trying to import the library in python, I am getting the following error: "TypeError: issubclass() arg 1 must be a class"

![image](https://github.com/microsoft/presidio/assets/64510443/21eda049-f586-4f90-87a4-7357537cb2bd)

Can someone help me please?

**Comment by omri374** [comment]
Hi, which Python and Presidio Analyzer version are you using?
Have you tried re-install ing the package?

**Comment by omri374** [comment]
Closing for now, please re-open if you have more information to share.
