### ISSUE TITLE
Supported entity NIF is defined incorrectly in the documentation

### ISSUE THREAD

**Issue by elsatch** [microsoft/presidio#1085]
**Describe the bug**
The bug involves the incorrect definition of the supported entity NIF in the documentation provided at https://microsoft.github.io/presidio/supported_entities/. The FieldType for the NIF entity is not defined correctly, leading to an error when using it in requests.

In the documentation the FieldType should be "ES_NIF" instead of the current "NIF".

**To Reproduce**
1. Go to the URL https://microsoft.github.io/presidio/supported_entities/.
2. Check the definition of the NIF entity.
3. Attempt to use the NIF entity in a request, for example:
```python
analyzer_nif = batch_analyzer.analyze_dict(nif_list, entities=['NIF'], language="es")
```

4. Observe the error message received:

```
ValueError: No matching recognizers were found to serve the request.
``` 
**Expected behavior**

The expected behavior is that the NIF entity can be used in requests without encountering any errors following the documentation. 

**Screenshots**

N/A

**Additional context**
The current definition in the documentation for the FieldType of the NIF entity is incorrect. Instead of "NIF," the correct FieldType should be "ES_NIF" when using it in requests.

**Comment by omri374** [comment]
Hi, thanks for raising this. It was addressed in https://github.com/microsoft/presidio/pull/1057 and will be updated on the upcoming docs release.
