### ISSUE TITLE
Image Redactor not redacting `Name` and `Phone No.`

### ISSUE THREAD

**Issue by KrishPatel13** [microsoft/presidio#1101]
**Describe the bug**
Image Redactor not redacting `Name` and `Phone Number` in a Image.

**To Reproduce**
1. Download this Image and name it sample_emr_1.png:
![sample_emr_1](https://github.com/microsoft/presidio/assets/65433817/aec0d726-3ba3-4aa4-b845-71617031e9c5)

2. Open Python
3. Run the below code (keeping the Image in the same directory)
```
test_image_path = "resources/sample_emr_1.png"
with open(test_image_path, "rb") as file:
    test_image_data = file.read()

# Convert image data to PIL Image object
test_image = Image.open(BytesIO(test_image_data))

# Scrub the image
scrubbed_image = scrub.scrub_image(test_image)

# Save the scrubbed image data to a file
scrubbed_image_path = test_image_path[:-4] + "_scrubbed.png"
scrubbed_image.save(scrubbed_image_path)

```
4. See the Image saved in CWD manually and verify the missed PII/PHI that were not redacted.
Redacted Image:
![sample_emr_1_scrubbed](https://github.com/microsoft/presidio/assets/65433817/a0743b7c-a1ca-4139-b81f-a13257e0b9c8)

**Expected behavior**
It should have scrubbed/redacted `Name` and `Phone Number`. [Not sure if it supports Age and **Company Name**] Will appreciate some guidance on that if it does not

**Screenshots**
Included in the comment: https://github.com/MLDSAI/OpenAdapt/pull/328#issuecomment-1611909662

**Comment by omri374** [comment]
Hi @KrishPatel13, on the image redaction pipeline, errors could be caused either by a wrong OCR text extraction, or by a miss by the presidio-analyzer module. Is there a way for your to check what is the output of tesseract on this image?

We are working towards a revamp of the image-redactor package (see https://github.com/microsoft/presidio/discussions/1049) but it is still work in progress.

**Comment by omri374** [comment]
Closing for now, please re-open if needed.
