### ISSUE TITLE
Instance preserving anonymization

### ISSUE THREAD

**Issue by feynmanliang** [microsoft/presidio#1102]
**Is your feature request related to a problem? Please describe.**

When I use a REPLACE anonymizer, all entities of the same `entity_type` are collapsed to the same `<ENTITY_TYPE>` token. For example "Alice and Bob and Alice" is replaced to "<NAME> and <NAME> and <NAME>" and it is not possible to determine whether these tokens refer to the same or different people.

**Describe the solution you'd like**

The ability to preserve instance identity. For example, if we have a `preserve_instance: True` param to the `REPLACE` operator, then we would like the result:

"<NAME 0> and <NAME 1> and <NAME 0>"

**Describe alternatives you've considered**

It may be useful to annotate instance identity within the `PIIEntity` or `RecognizerResult` classes themselves, for example for later use in deanonymization.

**Additional context**

We have this running on a fork; happy to submit a PR if there's interest.

**Comment by omri374** [comment]
Thanks! That is definitely a needed capability. Have you thought of ways to persist the relation between original and new? We should allow users to persist this mapping in multiple ways (in a db, in memory etc.) Just an initial thought.

**Comment by SharonHart** [comment]
I know that its not fully covers your use-case, but using 'hash' anonymization should hash two similar values into the same value (you would lose the entity type that way though)

**Comment by feynmanliang** [comment]
Thanks for the comment! Yeah, unfortunately we are using this inside of a LLM anonymization service and replacing PII with hashes significantly changes the responses generated by the LLM.

**Comment by himsgpt** [comment]
Interestingly there are multiple use case fir this and I am looking to utilize this feature. Has it been implemented in presidio?

**Comment by omri374** [comment]
Hi, not yet, but maybe this discussion can help. Feel free to add your feedback to the discussion.
https://github.com/microsoft/presidio/discussions/1118

**Comment by omri374** [comment]
Closing for #1118
