### ISSUE TITLE
Adding no-code recognizer not working

### ISSUE THREAD

**Issue by Aryan-Jain-1710** [microsoft/presidio#1116]
I made a function and put the following code in that function, then I am calling my function in the main method.
```
yaml_file = "recognizers.yaml"  # path to YAML file
registry = RecognizerRegistry()
registry.load_predefined_recognizers()  # Loads all the predefined recognizers (Credit card, phone number etc.)
registry.add_recognizers_from_yaml(yaml_file)
```
After that I am using the code below to find out if the recognizer was added or not
```
analyzer = AnalyzerEngine() # or your custom way of creating the analyzer engine
list = analyzer.registry.get_recognizers(language="en", entities=["USERS"]) 
```
(the name of the supported entity of the recognizer described in the yaml file is "USERS")

However, the output says no recognizer with the specific entity name is found. Am I doing something wrong? And is there a limit to the number of items that I can have in the deny list?

**Comment by omri374** [comment]
Hi @Aryan-Jain-1710, I think you're missing one step which is to define your registry as the one used by the `AnalyzerEngine`:
```python
analyzer = AnalyzerEngine(registry=registry)
```

**Comment by omri374** [comment]
Closing for now, please feel free to re-open if needed.

**Comment by Aryan-Jain-1710** [comment]
Hi

I have the following code:
```
from presidio_analyzer import AnalyzerEngine, RecognizerRegistry
from typing import List

def add_recog(yaml_file):
    registry = RecognizerRegistry()
    registry.load_predefined_recognizers()  # Loads all the predefined recognizers (Credit card, phone number etc.)
    registry.add_recognizers_from_yaml(yaml_file)


def get_recog() -> None:
    registry = RecognizerRegistry()
    analyzer = AnalyzerEngine(registry=registry) # or your custom way of creating the analyzer engine
    list = analyzer.registry.get_recognizers(language="en", entities=["USERS"]) 
    print(list)

def main():
    add_recog("user_recognizer.yaml")
    get_recog()

```

However, on running the python file, I am getting ValueError saying no matching recognizers were found. Is there something that I am still missing?

**Comment by omri374** [comment]
Please try this:
```python
from presidio_analyzer import AnalyzerEngine, RecognizerRegistry
from typing import List

def create_recognizer_registry(yaml_file):
    registry = RecognizerRegistry()
    registry.load_predefined_recognizers()  # Loads all the predefined recognizers (Credit card, phone number etc.)
    registry.add_recognizers_from_yaml(yaml_file)
    return registry

def main():
    registry = create_recognizer_registry("user_recognizer.yaml")
    analyzer = AnalyzerEngine(registry=registry) # or your custom way of creating the analyzer engine
    list = analyzer.registry.get_recognizers(language="en", entities=["USERS"]) 
    print(list)
```
In your code, you are instantiating the `RecognizerRegistry` object twice, once in each method, but only use it once.

**Comment by Aryan-Jain-1710** [comment]
Alright, thank you.
If I wish to view the list of all the recognizers, I run the get recognizers method with entities=None, however, I get a ValueError saying no entities are provided, is there a way for me to view all the recognizers?

**Comment by omri374** [comment]
`analyzer.get
