### ISSUE TITLE
Deny List Recognizer

### ISSUE THREAD

**Issue by Aryan-Jain-1710** [microsoft/presidio#1119]
Hi,

If I create a new deny list recognizer with a list of words in the deny list, would it be possible to detect words that may be like the words part of the list?
```[tasklist]
### Tasks
```

**Comment by omri374** [comment]
Could you please clarify what you mean by "may be like the words part of the list" and/or provide an example?

**Comment by Aryan-Jain-1710** [comment]
I am not sure if it is possible but what I mean is basically if I have a list of users and I create a deny list recognizer and I add that list of users to it, would it be possible for me to detect any other users who were not part of that list (with the main issue that context words can not be implemented since words like name, user, author are not being used in the text being analysed instead the actually username is being used directly)

For example, 
"""
user1 controls kernel process
user2 accesses 5 nodes
user3 cancelled their task
"""

now say in this case user1 and user2 were part of the list, is there a way for me to detect user3 without it being part of the deny list recognizer?

**Comment by navalev** [comment]
Yes, if user3 is an entity that can be detected by the built in presidio recognizers https://microsoft.github.io/presidio/supported_entities/
