### ISSUE TITLE
Presidio Tabular  

### ISSUE THREAD

**Issue by zahycs** [microsoft/presidio#1122]
**Is your feature request related to a problem?**
Yes, the feature request is related to an identified limitation in Presidio. Currently, while the tool is excellent in handling various data types, its capability with tabular/structured data (like SQL databases, Excel files, or CSVs) is limited. This poses a challenge for users trying to anonymize such types of data.

**Describe the solution you'd like**
We propose the enhancement of Presidio's anonymization capabilities to efficiently handle tabular and structured data. The new feature should be integrated into the existing framework seamlessly, and should effectively anonymize structured data while preserving the inherent relationships within the data structure. In essence, Presidio should be able to understand the schema of the data and anonymize accordingly.

**Describe alternatives you've considered**
An alternative solution could be the development of a separate tool specifically designed to handle tabular/structured data anonymization. However, this could lead to toolset fragmentation, complicating user experience.

Another possibility involves using external tools to preprocess the structured data into a format compatible with Presidio. However, this could introduce unnecessary complexity and additional steps for the end-user.

**Additional context**
During a recent customer engagement, we realized the significance and demand for such a feature in Presidio. As structured data is common across various use-cases, extending Presidio's capabilities to handle this data format would make the tool more comprehensive and widely applicable. This aligns with the ongoing development efforts to make Presidio a holistic solution for data anonymization.

**Comment by omri374** [comment]
Solved in #1192. Thanks @zahycs and @Jakob-98!
