### ISSUE TITLE
How to filter Entities in ImageRedactorEngine

### ISSUE THREAD

**Issue by pavanbalajin** [microsoft/presidio#1129]
Hi,
        I am struck with Entities filtration in InageRedactorEngine, please help me if any one knows.I dont want all entities to be blocked.

Regards,
Pavan

**Comment by omri374** [comment]
To filter entities during image redaction, you should pass the arguments to the `AnalyzerEngine.analyze` method through the `ImageRedactorEngine.redact` kwargs:
```python
from presidio_image_redactor import ImageRedactorEngine

engine = ImageRedactorEngine()
engine.redact(image, entities = ["PERSON", "PHONE_NUMBER"])
```

Please try and re-open if you experience any issues.

**Comment by omri374** [comment]
To filter entities during image redaction, you should pass the arguments to the `AnalyzerEngine.analyze` method through the `ImageRedactorEngine.redact kwargs:
```python
from presidio_image_redactor import ImageRedactorEngine

engine = ImageRedactorEngine()
engine.redact(image, entities = ["PERSON", "PHONE_NUMBER"])
```

Please try and re-open if you experience any issues.
