### ISSUE TITLE
Flair Recognizer Initialization Error

### ISSUE THREAD

**Issue by mhmdaskari** [microsoft/presidio#1142]
Hello,

I am getting an error while trying to instantiate an object from the FlairRecognizer class defined in this document:
[flair_recognizer.py](https://github.com/microsoft/presidio/blob/main/docs/samples/python/flair_recognizer.py).

The error happens at [line 92](https://github.com/microsoft/presidio/blob/e323fed0209a3cef3fa7e75eb6b2ef0e0e92234f/docs/samples/python/flair_recognizer.py#L92) of the file:

> Error(s) in loading state_dict for XLMRobertaModel:
> 	Unexpected key(s) in state_dict: "embeddings.position_ids".

1. Clone this code [flair_recognizer.py](https://github.com/microsoft/presidio/blob/main/docs/samples/python/flair_recognizer.py)
2. Run it and wait for the weights of the model to be downloaded.
3. See the error.

**Comment by brondsem** [comment]
Did you find a solution or workaround for this error?

**Comment by omri374** [comment]
Could the bug be related to this? https://github.com/flairNLP/flair/issues/3284

**Comment by mhmdaskari** [comment]
My issue came from the incompatibility of one of the Flair package requirements with Apple silicon processors (arm64), lxml.
I could fix that by manually building the package based on the provided [instructions](https://lxml.de/build.html#building-lxml-on-macos-x) using the following code:

`STATIC_DEPS=true pip install lxml`

Note that there might be cached data saved from pip that could prevent you from building the package. You may delete the caches before building the package or use the following code to ignore the saved caches:

`STATIC_DEPS=true pip --no-cache-dir install lxml`

I hope that helps!

P.S. I wasn't sure if that would be something related to presidio, and that's why I closed the issue.
