### ISSUE TITLE
Option to have encryption mode produce the same ciphertext for the same plaintext

### ISSUE THREAD

**Issue by octaviansima** [microsoft/presidio#1157]
**Is your feature request related to a problem? Please describe.**
The way the encryption logic currently works, a new IV is used in every call to `AESCipher.encrypt`. This means that every ciphertext will be unique for the same underlying plaintext. We've found that manually replacing them with the same ciphertext has better performance when the anonymized prompt is fed into various LLMs.

**Describe the solution you'd like**
We would like to contribute a change to [Encrypt](https://github.com/microsoft/presidio/blob/main/presidio-anonymizer/presidio_anonymizer/operators/encrypt.py#L9) to track previously seen `text` values and simply return the ciphertext generated once for them in the call to `Encrypt.operate`.

**Describe alternatives you've considered**
We can also make `AESCipher.encrypt` take in an IV and track those, but the solution above avoids unnecessary encryption.

Please let me know if this is a contribution that Presidio would accept, thanks.

**Comment by omri374** [comment]
Hi @octaviansima, thanks for the suggestion! I find your suggestion to be somewhat related to other discussions we're having. Could you please take a look at [this document](https://github.com/microsoft/presidio/discussions/1118) and see if is relevant? 

Keeping a list of previously seen text values would be simple in a naive implementation, but when it comes to multiple instances of anonymizers, or when there are strict restrictions on holding PII data, it might become complex. 

We found that it is better done on the client side, i.e. results from the analyzer would be replaced using a dictionary held on the user's side. This would allow more scalability and more security.

**Comment by octaviansima** [comment]
Hi @omri374, thanks for the suggestion. We decided to go with the client-side dictionary approach, closing
