### ISSUE TITLE
Using German Flair for entity recognizer

### ISSUE THREAD

**Issue by OnsElleuch** [microsoft/presidio#1160]
I am trying to follow the exact same Flair recognizer that was provided in the documentation to be able to use Flair with German as spacy models were not performing very well when it comes to PERSON entities and Flair has better results from my experience. I have not changed anything in the [FlairRcognizer](https://github.com/microsoft/presidio/blob/main/docs/samples/python/flair_recognizer.py) class. 
then this is the code I have : 
```
flair_recognizer = FlairRecognizer(supported_language="de")
registry = RecognizerRegistry()
registry.add_recognizer(flair_recognizer)
results = analyzer.analyze(text, language="de")
```
I get the error: `KeyError: 'de'` in `spacy_nlp_engine.py:44`
Now I am confused if I should configure an NLP engine. And if so, how would the configuration look? 
Thanks

**Comment by omri374** [comment]
Hi @OnsElleuch,
Presidio requires a spaCy model in every supported language, even if you're using Flair, as spaCy output is used by other Presidio modules (lemmas, tokens etc.). 

If you're not interested in the spaCy NER output, I would suggest to use [a small German spaCy model](https://spacy.io/models/de#de_core_news_sm), and remove the `SpacyRecognizer` from the list of recognizers:
```python
configuration = {
    "nlp_engine_name": "spacy",
    "models": [
        {"lang_code": "de", "model_name": "de_core_news_sm"}
    ],
}

# Create NLP engine based on configuration
provider = NlpEngineProvider(nlp_configuration=configuration)
nlp_engine = provider.create_engine()

registry = RecognizerRegistry()
registry.load_predefined_recognizers()
flair_recognizer = FlairRecognizer(supported_language="de")

registry.add_recognizer(flair_recognizer)
registry.remove_recognizer("SpacyRecognizer")

analyzer = AnalyzerEngine(registry=registry, nlp_engine=nlp_engine, supported_languages=["de"])


```

See more here:
- https://microsoft.github.io/presidio/tutorial/05_languages/
- https://huggingface.co/spaces/presidio/presidio_demo/blob/b7be871e6a6692ea5945974c891409552889c927/presidio_nlp_engine_config.py#L80



Closing the issue, please re-open if you have other questions
