### ISSUE TITLE
Number recognized as a PERSON, is this right?

### ISSUE THREAD

**Issue by fabiohaertel** [microsoft/presidio#1173]
Hi all.

I have a small csv file with 2 lines:

    6033391
    6058722

For some reason those values are recognized as PERSON
Is that a bug?

`"value": [
				"6033391",
				"6058722"
			],
			"recognizer_results": [
				[
					"type: PERSON, start: 0, end: 7, score: 0.85"
				],
				[
					"type: PERSON, start: 0, end: 7, score: 0.85"
				]
			]`

Thank you! (just trying to understand what's going on).

**Comment by fabiohaertel** [comment]
Small update:

Using the presidio demo page with spaCy/en_core_web_lg model it's also recognized as a PERSON

https://huggingface.co/spaces/presidio/presidio_demo

**Comment by omri374** [comment]
Could be an issue with the `en_core_web_lg` model (which is being used in the default Presidio version too).

**Comment by SemanticBrainCorp** [comment]
Another example of PERSON (and URL) false positive

```
from presidio_analyzer import AnalyzerEngine
from pprint import pprint

analyzer = AnalyzerEngine()

text = "03/22 08:51:06 INFO   :...read_physical_netif: index #1, interface TR1 has address 9.22.22.222, ifidx 1"

results = analyzer.analyze(text=text, language='en')
pprint(results)
```

```
[type: PERSON, start: 6, end: 14, score: 0.85,
 type: IP_ADDRESS, start: 83, end: 94, score: 0.6,
 type: URL, start: 23, end: 28, score: 0.5,
 type: DATE_TIME, start: 0, end: 5, score: 0.1]
```

**Comment by albertsemantic** [comment]
Another example of PERSON (and URL) false positive

```
from presidio_analyzer import AnalyzerEngine
from pprint import pprint

analyzer = AnalyzerEngine()

text = "03/22 08:51:06 INFO   :...read_physical_netif: index #1, interface TR1 has address 9.22.22.222, ifidx 1"

results = analyzer.analyze(text=text, language='en')
pprint(results)
```

```
 [type: PERSON, start: 6, end: 14, score: 0.85,
 type: IP_ADDRESS, start: 83, end: 94, score: 0.6,
 type: URL, start: 23, end: 28, score: 0.5,
 type: DATE_TIME, start: 0, end: 5, score: 0.1]
```

**Comment by omri374** [comment]
Each model and each logic has some ratio of false positives and false negatives. Please see the documentation on how to experiment with different types of detection mechanisms, including the tooling on https://github.com/microsoft/presidio-research

Closing for now, feel free to re-open if needed.
