### ISSUE TITLE
Inconsistent type check

### ISSUE THREAD

**Issue by ChenghaoMou** [microsoft/presidio#1174]
https://github.com/microsoft/presidio/blob/d8541e973349ceefccec926a01992dd554de6123/presidio-analyzer/presidio_analyzer/recognizer_registry/recognizer_registry.py#L128

```
    def _get_nlp_recognizer(
        nlp_engine: NlpEngine,
    ) -> Union[Type[SpacyRecognizer], Type[StanzaRecognizer]]:
        """Return the recognizer leveraging the selected NLP Engine."""

        if not nlp_engine or type(nlp_engine) is SpacyNlpEngine:
            return SpacyRecognizer
        if isinstance(nlp_engine, StanzaNlpEngine):
            return StanzaRecognizer
        if isinstance(nlp_engine, TransformersNlpEngine):
            return TransformersRecognizer
        else:
            logger.warning(
                "nlp engine should be either SpacyNlpEngine,"
                "StanzaNlpEngine or TransformersNlpEngine"
            )
            # Returning default
            return SpacyRecognizer
```

Currently, it uses `type(nlp_engine) is SpacyNlpEngine` instead of `isinstance(nlp_engine, SpacyNlpEngine)`. It will lead to a warning even if the engine is an instance from an inherited class:

```
from presidio_analyzer.nlp_engine import SpacyNlpEngine


class LoadedSpacyNlpEngine(SpacyNlpEngine):
    def __init__(self, loaded_spacy_model):
        self.nlp = {"en": loaded_spacy_model}

if __name__ == "__main__":
    
    import spacy
    nlp = spacy.load("en_core_web_lg")
    temp_engine = LoadedSpacyNlpEngine(nlp)
    print(type(temp_engine) is SpacyNlpEngine)
    print(isinstance(temp_engine, SpacyNlpEngine))
```

**Comment by omri374** [comment]
Hi @ChenghaoMou, the other NLP Engines (Stanza, Transformers) inherit from `SpacyNlpEngine`, so replacing with `isinstance` would not work. If you have any suggestions which keeps the existing flow in tact + supports inherited engines, please let us know. In general, you don't have to use the `NlpEngineProvider`, and can instantiate your custom `NlpEngine` yourself, before passing it to the `AnalyzerEngine`.

**Comment by ChenghaoMou** [comment]
I see. Thanks for the explanation. Could you elaborate on why changing the flow won't work here?
```
if isinstance(nlp_engine, StanzaNlpEngine):
    return StanzaRecognizer
if isinstance(nlp_engine, TransformersNlpEngine):
    return TransformersRecognizer
if not nlp_engine or isinstance(nlp_engine, SpacyNlpEngine):
    return SpacyRecognizer
```

**Comment by omri374** [comment]
That should work! Will you update your PR?

**Comment by omri374** [comment]
BTW more changes are coming to the NLP engine in this PR #1159

**Comment by ChenghaoMou** [comment]
Thank you for the pointer! It looks like the config system should eliminate my reason for the PR, at least for my use case. I have updated the PR in case it is still wanted, and I am happy to close it otherwise.

**Comment by omri374** [comment]
I'm interested to understand more about your use case, if you're willing to share.

**Comment by ChenghaoMou** [comment]
The short version is that I want to use `en_core_web_lg`, `en_core_web_trf`, or a custom-trained spacy model like the `LoadedSpacyNlpEngine` above without warning, but it looks like the config or NlpEngineProvider should be enough.
