### ISSUE TITLE
Running in GPU

### ISSUE THREAD

**Issue by sankagirirajeev** [microsoft/presidio#1186]
I'm running Persidio on around 60 lakh records. It takes more than 4 minutes to process 1000k data. Is there any way to run it in the fattest way possible?

**Comment by sankagirirajeev** [comment]
Anyone please help with this issue?

**Comment by olonok69** [comment]
> Anyone please help with this issue?

I have the same issue,  and digging on there. I think spacy it is not install with gpu support . I manage to install spacy with GPU support and on top presidio, but it simply fails when trying to create a analyzerEngine()

**Comment by sankagirirajeev** [comment]
import spacy
spacy.require_gpu()

i used like this ..but still its taking too much of time to run.

**Comment by omri374** [comment]
Combining this issue with the discussion here: https://github.com/microsoft/presidio/discussions/1185
