### ISSUE TITLE
How to use a locally downloaded version of an NLP engine

### ISSUE THREAD

**Issue by J-hme** [microsoft/presidio#1204]
I cannot use live http connection to download models directly by python due to a firewall.
However, I have downloaded "en_core_web_sm" in a local folder and
nlp = spacy.load('/en_core_web_sm/en_core_web_sm-3.5.0/') successfully loads the model.

Now how to use this in the following functions
TransformersNlpEngine, AnalyzerEngine

Thanks!

**Comment by omri374** [comment]
Are you interested in using the `en_core_web_sm` model, or a huggingface model? 
In both cases, if you pre-downloaded the models, they should be installed without going online. Could you please provide more information if that's not the case?

On how to use the following functions, please see this doc: https://microsoft.github.io/presidio/analyzer/nlp_engines/transformers/#creating-a-configuration-file

Alternatively, if you prefer to configure it via code:
```python
from presidio_analyzer import AnalyzerEngine, RecognizerRegistry
from presidio_analyzer.nlp_engine import NlpEngineProvider

# Configure which spacy and huggingface models you'd like to use
configuration = {
    "nlp_engine_name": "transformers",
    "models": [{
                    "lang_code": "en",
                    "model_name": {
                        "spacy": "en_core_web_sm",
                        "transformers": "StanfordAIMI/stanford-deidentifier-base",
                    },
                }],
}

# Note that additional configuration for things like entity mapping and more should be passed. Here we use the default

# create nlp_engine
provider = NlpEngineProvider(nlp_configuration = configuration)
nlp_engine = provider.create_engine()

# Use Presidio Analyzer
analyzer = AnalyzerEngine(nlp_engine=nlp_engine)
analyzer.analyze(...)
```

**Comment by J-hme** [comment]
Thanks @omri374. I am interested to use "en_core_web_sm".

I cannot use the following due to a firewall and get http connection error
python -m spacy download en_core_web_sm

As I mentioned, I have downloaded it in a local folder  c:/en_core_web_sm/en_core_web_sm-3.5.0/

My question is how to give the location of the downloaded model to the code? 
should I change the configuration like this:

configuration = {
    "nlp_engine_name": "spacy",
    "models": [{
                    "lang_code": "en",
                    "model_name": {
                        "spacy": "c:/en_core_web_sm/en_core_web_sm-3.5.0/",
                        "transformers": "StanfordAIMI/stanford-deidentifier-base",
                    },
                }],
}

I did and it raised a ValueError: model_name must be a string

**Comment by omri374** [comment]
Hi, you are providing a transformers configuration (which is a spaCy pipeline with a transformers model in it) instead of a spacy configuration. For spacy, `model_name` should be the path to the model, not a dictionary.

**Comment by omri374** [comment]
Another option would be to load the model directly using spacy this way: https://microsoft.github.io/presidio/analyzer/nlp_engines/spacy_stanza/#using-a-previously-loaded-spacy-pipeline

**Comment by VMD7** [comment]
Hi, you can use the following way as well. 
```
from presidio_analyzer import AnalyzerEngine
from presidio_anonymizer import AnonymizerEngine
from presidio_analyzer.nlp_engine import SpacyNlpEngine
import spacy
text="Pls activate following login for portal my number is 98989898898"

class LoadedSpacyNlpEngine(SpacyNlpEngine):
    def __init__(self, loaded_spacy_model):
        self.nlp = {"en": loaded_spacy_model}

nlp = spacy.load(r"C:/Tasks/PIIFilter/Experiments/SpacyTrainedModel/model-best")

loaded_nlp_engine = LoadedSpacyNlpEngine(loaded_spacy_model = nlp)
analyzer = AnalyzerEngine(nlp_engine = loaded_nlp_engine)

# Call analyzer to get results
results = analyzer.analyze(text=text,
                           entities=["PERSON","PHONE_NUMBER","EMAIL_ADDRESS","IP_ADDRESS","US_SSN","UserId","Password"],
                           language='en')
print(results)

anonymizer = AnonymizerEngine()
anonymized_text = anonymizer.anonymize(text=text,analyzer_results=results)
print(anonymized_text)
```

**Comment by J-hme** [comment]
> Another option would be to load the model directly using spacy this way: https://microsoft.github.io/presidio/analyzer/nlp_engines/spacy_stanza/#using-a-previously-loaded-spacy-pipeline

Thanks @omri374 
I get this error now:
![image](https://github.com/microsoft/presidio/assets/36275746/dddcad9d-a4ec-4791-9c97-3483ac085eac)

**Comment by VMD7** [comment]
Hi, 
There might be two reasons for this 
**-> You might have downloaded wrong spacy model or the model which doesn't support ner or not giving the path of spacy where it couldn't find the config file.** 
**Steps:**
-> Go to the following official link - ```https://github.com/explosion/spacy-models/releases?q=en_core_web_sm-3.5.0&expanded=true```
-> Download the tar file and extract the same.
-> Now while specifying the path make sure that you are giving the path till it can detect the config file. For example - ```D:/Experiment/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0/en_core_web_sm/en_core_web_sm-3.5.0```. Make sure that in this directory `config` file present. 
-> Now use the same code and it will work. 
```from presidio_analyzer import AnalyzerEngine
from presidio_anonymizer import AnonymizerEngine
from presidio_analyzer.nlp_engine import SpacyNlpEngine
import spacy
text="Pls activate my number is 98989898898"

class LoadedSpacyNlpEngine(SpacyNlpEngine):
    def __init__(self, loaded_spacy_model):
        self.nlp = {"en": loaded_spacy_model}

nlp = spacy.load("D:Experiment/en_core_web_sm-3.5.0/en_core_web_sm-3.5.0/en_core_web_sm/en_core_web_sm-3.5.0")

loaded_nlp_engine = LoadedSpacyNlpEngine(loaded_spacy_model = nlp)
analyzer = AnalyzerEngine(nlp_engine = loaded_nlp_engine)

# Call analyzer to get results
results = analyzer.analyze(text=text,
                           entities=["PERSON","PHONE_NUMBER","EMAIL_ADDRESS","IP_ADDRESS","US_SSN","UserId","Password"],
                           language='en')
print(results)

anonymizer = AnonymizerEngine()
anonymized_text = anonymizer.anonymize(text=text,analyzer_results=results)
print(anonymized_text)```

**Comment by VMD7** [comment]
Hi, 
You can refer below code for reference.
```
from presidio_analyzer import AnalyzerEngine
from presidio_anonymizer import AnonymizerEngine
from presidio_analyzer.nlp_engine import SpacyNlpEngine, NerModelConfiguration  
import spacy

text="Pls activate my number is 98989898898"

ner_model_config = NerModelConfiguration(
    model_to_presidio_entity_mapping={
    "PERSON":"PERSON",
    "LOC":"LOCATION"
    }
)

class LoadedSpacyNlpEngine(SpacyNlpEngine):
    def __init__(self, loaded_spacy_model, ner_model_configuration):
        self.nlp = {"en": loaded_spacy_model}
        self.ner_model_configuration = ner_model_configuration

nlp = spacy.load("/content/en_core_web_sm-3.5.0/en_core_web_sm/en_core_web_sm-3.5.0")

loaded_nlp_engine = LoadedSpacyNlpEngine(loaded_spacy_model = nlp, ner_model_configuration = ner_model_config)
analyzer = AnalyzerEngine(nlp_engine = loaded_nlp_engine)

# Call analyzer to get results
results = analyzer.analyze(text=text,
                           language='en')
print(results)

anonymizer = AnonymizerEngine()
anonymized_text = anonymizer.anonymize(text=text,analyzer_results=results)
print(anonymized_text)```

**Comment by restrictedalex96** [comment]
Hi. there are still some occasions when presidio tries to access the inherent. 
For example if i'm including an email address, and asking the analyzer to analyze it with a locally loaded Spacy model I'm getting the following warning. followed by HTTP max retries error:
```
unable to cache publicsuffix.org-tlds.{'urls': ('https://publicsuffix.org/list/public_suffix_list.dat', 'https://raw.githubusercontent.com/publicsuffix/list/master/public_suffix_list.dat'), 'fallback_to_snapshot': True} in /home/ssm-user/.cache/python-tldextract/3.8.10.final__usr__7d8fdf__tldextract-5.0.1/publicsuffix.org-tlds/de84b5ca2167d4c83e38fb162f2e8738.tldextract.json. This could refresh the Public Suffix List over HTTP every app startup. Construct your `TLDExtract` with a writable `cache_dir` or set `cache_dir=None` to silence this warning. [Errno 13] Permission denied: '/home/ssm-user/.cache
```

**Comment by J-hme** [comment]
> Hi, You can refer below code for reference.
> 
> ```
> from presidio_analyzer import AnalyzerEngine
> from presidio_anonymizer import AnonymizerEngine
> from presidio_analyzer.nlp_engine import SpacyNlpEngine, NerModelConfiguration  
> import spacy
> 
> text="Pls activate my number is 98989898898"
> 
> ner_model_config = NerModelConfiguration(
>     model_to_presidio_entity_mapping={
>     "PERSON":"PERSON",
>     "LOC":"LOCATION"
>     }
> )
> 
> class LoadedSpacyNlpEngine(SpacyNlpEngine):
>     def __init__(self, loaded_spacy_model, ner_model_configuration):
>         self.nlp = {"en": loaded_spacy_model}
>         self.ner_model_configuration = ner_model_configuration
> 
> nlp = spacy.load("/content/en_core_web_sm-3.5.0/en_core_web_sm/en_core_web_sm-3.5.0")
> 
> loaded_nlp_engine = LoadedSpacyNlpEngine(loaded_spacy_model = nlp, ner_model_configuration = ner_model_config)
> analyzer = AnalyzerEngine(nlp_engine = loaded_nlp_engine)
> 
> # Call analyzer to get results
> results = analyzer.analyze(text=text,
>                            language='en')
> print(results)
> 
> anonymizer = AnonymizerEngine()
> anonymized_text = anonymizer.anonymize(text=text,analyzer_results=results)
> print(anonymized_text)
> ```

This solved the issue thank you very much for the help @VMD7
