### ISSUE TITLE
tldextract tries to access a web page if email address is part of the analyzed text (Offline mode)

### ISSUE THREAD

**Issue by restrictedalex96** [microsoft/presidio#1205]
**Describe the bug**
I'm using presidio in an offline mode (without network). I'm assuming my machine has a pre-downloaded Spacy model. I'm loading it in the following way: https://github.com/microsoft/presidio/issues/1204#issuecomment-1792990076
I'm mostly interested in the analyzer. I've noticed that in some flows, the analyzer.analyze tries to access the web, specifically using tldextract it tries to access https://publicsuffix.org/list/public_suffix_list.dat
This flow only happens if the analyzed text contains email addresses. for example "Hello my email address is alex@gmail.com"

**To Reproduce**
Use the following code to setup: https://github.com/microsoft/presidio/issues/1204#issuecomment-1792990076
Inject an email address into the analyzed text. 
Presidio will be stuck trying to access the .bat file with public suffixes and will Timeout after a few minutes 

**Expected behavior**
Presidio should analyze the text without trying to access the internet

**Screenshots**
![image](https://github.com/microsoft/presidio/assets/89806869/0e5f4db4-3f84-49dc-a80b-8ded827bd9af)

**Comment by omri374** [comment]
Thanks @restrictedalex96. 
Here are some possible workarounds:
1. Remove the url and email recognizers, if you don't need emails and urls detected
2. Leverage the logic in the URL and email recognizers, without the `tldextract` validation, by inheriting their classes and overloading the `validate` method with `return True`
3. Handle the `tldextract` cache prior to running Presidio or monkeypatch `tldextract`

If you need more information on each of these, please let us know. We will look into finding alternative ways to validate emails and URLs without having to go online.

**Comment by omri374** [comment]
See more on tldextract caching here: https://github.com/john-kurkowski/tldextract#note-about-caching
You can pre-download the cache and avoid live http calls.

**Comment by restrictedalex96** [comment]
Thank you!
