### ISSUE TITLE
2.2.351 no longer correctly detects ORG with Spacy en_core_web_lg

### ISSUE THREAD

**Issue by claesmk** [microsoft/presidio#1212]
**Describe the bug**
Last known working version was 2.2.33.  Using this version with en_core_web_lg-3.6.0 an ORG was correctly detected as shown:
```
Enter a test string or <enter> to quit: This is an organization: Texas A&M University
<-- spacy only results -->
text: This is an organization: Texas A&M University
Texas A&M University 25 45 ORG
<-- Microsoft Presidio results -->
text: This is an organization: Texas A&M University
result: Texas A&M University entity_type: ORGANIZATION, score: 0.85, start: 25, end: 45
```
However, with 2.2.351 using en_core_web_lg-3.7.0, spacy detects an ORG however Presidio does not:
```
Enter a test string or <enter> to quit: This is an organization: Texas A&M University
<-- spacy only results -->
text: This is an organization: Texas A&M University
Texas A&M University 25 45 ORG
<-- Microsoft Presidio results -->
text: This is an organization: Texas A&M University
```

**To Reproduce**
1. Setup this [repo](https://github.com/NCATComp410/comp410_fall_2023) in a codespace
2. From a terminal execute "python spacy_vs_ms.py"
3. Enter "This is an organization: Texas A&M University" as a test string
4. Observer that spacy detects an ORG but Presidio does not

**Expected behavior**
I would expect Presido to detect an ORG in this case since Spacy did.

**Screenshots**
See snips above

**Additional context**
I will attempt some additional debugging on this issue to determine why an ORG is not detected as expected.

**Comment by kondera** [comment]
I had the same problem after upgrading to new version of analyser. The default configuration changed - now ORG is ignored, because it has low accuracy. So if you want to have orgs identified you need to pass config nlp_engine like:
```{python}
configuration = {
    "nlp_engine_name": "spacy",
    "models": [
        {"lang_code": "en", "model_name": "en_core_web_lg"},
    ],
    # default ner model config
    "ner_model_configuration": {
        "labels_to_ignore": [
            # don't ignore
            # "ORG",
            # "ORGANIZATION",
            "MONEY",
            "LAW",
            "QUANTITY",
            "EVENT",
            "O",
            "LANGUAGE",
            "ORDINAL",
            "PERCENT",
            "WORK_OF_ART",
            "CARDINAL",
            "PRODUCT",
        ],
        "model_to_presidio_entity_mapping": {
            "LOC": "LOCATION",
            "NORP": "NRP",
            "GPE": "LOCATION",
            "PER": "PERSON",
            "PERSON": "PERSON",
            "FAC": "LOCATION",
            "LOCATION": "LOCATION",
            "TIME": "DATE_TIME",
            "DATE": "DATE_TIME",
            "ORG": "ORGANIZATION",
            "ORGANIZATION": "ORGANIZATION",
        },
    },
}

provider = NlpEngineProvider(nlp_configuration=configuration)
nlp_engine = provider.create_engine()

analyzer = AnalyzerEngine(
    nlp_engine=nlp_engine,
    supported_languages=["en"],
)
```

**Comment by claesmk** [comment]
Thanks a lot for the pointer. I think probably a deprecation warning message, especially [here](https://github.com/microsoft/presidio/blob/d68c44b2cad080ae3a377f8e9ca835b4aa2314f3/presidio-analyzer/presidio_analyzer/predefined_recognizers/spacy_recognizer.py#L28C34-L28C34), would have helped me realize what was happening since I happened to be calling SpacyRecognizer()

**Comment by omri374** [comment]
Hi @claesmk, we added two deprecation warnings in the new code, one when passing the deprecated `check_label_groups`:
https://github.com/microsoft/presidio/blob/d68c44b2cad080ae3a377f8e9ca835b4aa2314f3/presidio-analyzer/presidio_analyzer/predefined_recognizers/spacy_recognizer.py#L57
The other when calling the `__check_label` function:
https://github.com/microsoft/presidio/blob/d68c44b2cad080ae3a377f8e9ca835b4aa2314f3/presidio-analyzer/presidio_analyzer/predefined_recognizers/spacy_recognizer.py#L134

If you have a suggestion on how to handle the specific case you had, please let us know. We try to avoid backward incompatibility as much as we can, but sometimes it's inevitable.

**Comment by claesmk** [comment]
It seems that vscode + python extension + GitHub codespace is not showing warnings.  It looks like your warnings were working fine but I was simply not seeing them.  I'll take a look into why it was set this way.  
```
$ python -Wall test_pii_scan.py 
/workspaces/comp410_fall_2023/pii_scan.py:251: DeprecationWarning: check_label_groups is deprecated and isn't used;entities are mapped in NerModelConfiguration
  spacy_recognizer = SpacyRecognizer(check_label_groups=label_groups, supported_entities=entities, )
..F...
======================================================================
FAIL: test_organization (__main__.TestPIIScan.test_organization)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspaces/comp410_fall_2023/test_pii_scan.py", line 39, in test_organization
    self.assertIn('ORGANIZATION', str(results))
AssertionError: 'ORGANIZATION' not found in '[]'
```

**Comment by omri374** [comment]
Thank you. closing for now, please feel free to re-open if needed.
