### ISSUE TITLE
How can I have Operator dictionary value in single quotes

### ISSUE THREAD

**Issue by TusharPiku** [microsoft/presidio#1218]
We have 'Operator' function as parameter in 'anonymizer_engine.anonymize'. 
And programmatically, I built the dictionary for operator parameter like,

{
'DEFAULT': OperatorConfig("replace", {"new_value": "<ANONYMIZED>"}) ,
"US_PASSPORT": 'OperatorConfig("replace", {"new_value": "<passport>"})'
}

Here I have dictionary key for US_PASSSPORT value in single quote. But it is throwing error,

> File /anaconda/envs/azureml_py38/lib/python3.8/site-packages/presidio_anonymizer/core/engine_base.py:85, in EngineBase.__operate_on_text(self, text_metadata, text_to_operate_on, operator_metadata, operator_type)
>      82 entity_type = text_metadata.entity_type
>      83 self.logger.debug(f"getting operator for {entity_type}")
>      84 operator = self.operators_factory.create_operator_class(
> ---> 85     operator_metadata.operator_name, operator_type
>      86 )
>      87 self.logger.debug(f"validating operator {operator} for {entity_type}")
>      88 operator.validate(params=operator_metadata.params)
> 
> AttributeError: 'str' object has no attribute 'operator_name'

How can I have it in quotes? As I am building dictionary value by custom code, hence it is being created in single quotes always and system throws error. Any suggestion on it ? 

Also, "default' key value is allowed in quote.

**Comment by omri374** [comment]
Hi, the `OperatorConfig` value should be an instance of `OperatorConfig` and not a string. I'm not sure if this is what's causing the issue or not, please correct me if I'm wrong.

Your dictionary should be:
```python
{
'DEFAULT': OperatorConfig("replace", {"new_value": ""}) ,
"US_PASSPORT": OperatorConfig("replace", {"new_value": ""})
}
```

If you'd like to build it dynamically, you can use something like this:
```python

default_operator = OperatorConfig("replace", {"new_value": ""})
us_passport_operator = OperatorConfig("replace", {"new_value": ""})

operators_dict = {'DEFAULT': default_operator,'US_PASSPORT': us_passport_operator}
```

Closing the issue, please re-open if more context can be provided.

**Comment by TusharPiku** [comment]
Thanks Omri !!
