### ISSUE TITLE
Documentation of simple code for custom pattern regex not working

### ISSUE THREAD

**Issue by TusharPiku** [microsoft/presidio#1219]
Describe the bug
I tried to add custom regex as per documentation, but it is not working for me. 
Link - https://github.com/microsoft/presidio/blob/main/docs/samples//python/customizing_presidio_analyzer.ipynb

To Reproduce
## Define the regex pattern in a Presidio `Pattern` object
numbers_pattern = Pattern(name="numbers_pattern",regex="^\d", score = 0.1)

## Define the recognizer with one or more pattern
number_recognizer = PatternRecognizer(supported_entity="NUMBER", patterns = [numbers_pattern])
# Testing the recognizer itself:

text2 = "I live in 510 Broad st."

numbers_result = number_recognizer.analyze(text=text2, entities=["NUMBER"])
print("Result:")
print(numbers_result)

**Expected behavior**
Result:
[type: NUMBER, start: 10, end: 13, score: 0.5]

I Gets,
Result:
[]

**Screenshots**
<img width="1129" alt="image" src="https://github.com/microsoft/presidio/assets/69418120/659c73be-5a26-4820-a3b6-1be179c1433b">

**Additional context**

**Comment by omri374** [comment]
Hi, the regex used in the sample is `"\d+"` whereas in your sample it is `"^\d"`. I assume this is the source of the mismatch. Closing for now, please re-open if there's more context here.
