### ISSUE TITLE
Rescale dicom image incorrectly when intensity can be negative

### ISSUE THREAD

**Issue by jenny-hm-lee** [microsoft/presidio#1227]
**Describe the bug**
When redactoring an dicom image in dicom_image_radactor_engine.py,  the image intensity are rescaled using the function _rescale_dcm_pixel_array().  This function rescales the gray scale to be 0 to 255; however the rescale formula (below) assumes the smallest intensity value of the image array is 0, which is not usually not the case for medical CT images.  CT image have negative intensity value. 

`           
            image_2d_scaled = (
                np.maximum(image_2d_float, 0) / image_2d_float.max()
            ) * 255.0
`

Instead, a more robust formula would be

`           
            image_2d_scaled = (
                (image_2d_float.max() - image_2d_float) / (image_2d_float.max() - image_2d_float.min())
            ) * 255.0
`

As a consequence of this bug, the scaled image filtered out some text which were in negative intensity, and the text were not detected downstream.

**Comment by omri374** [comment]
Thank you, would you be interested in creating a pull request?

**Comment by jenny-hm-lee** [comment]
Yes.  What do I need for a successful PR?

**Comment by omri374** [comment]
This covers our contribution guidelines: https://github.com/microsoft/presidio/blob/main/CONTRIBUTING.md
