### ISSUE TITLE
Incorrect types assignation in NerModelConfiguration class in validation of a dictionary and in a default attribute

### ISSUE THREAD

**Issue by ebotiab** [microsoft/presidio#1229]
**Describe the bugs**
In the method `_validate_input` from the `NerModelConfiguration` class, the _dictionary_ `key_to_type` assigns type `list` instead of type `typing.Collection` as values for both `labels_to_ignore` and `low_score_entity_names` keys. This leads to errors when validating a well-formatted _dictionary_.

In addition, the default value for `low_score_entity_names` is an empty _dictionary_ (`LOW_SCORE_ENTITY_NAMES={}`) instead of an empty _list_ or an empty _set_ (e.g., `LOW_SCORE_ENTITY_NAMES=set()`), which could lead to undesired behavior.

**To Reproduce**
1. Create a _dictionary_ that allows the creation of a `NerModelConfiguration` instance in which `labels_to_ignore` and/or `low_score_entity_names` are _collection_ types other than _lists_ (e.g., _sets_). For example, this could be obtained by generating a _dictionary_ with the `NerModelConfiguration` default values via:

    `ner_conf_valid_dict = NerModelConfiguration().to_dict()`

2. Observe the error `ValueError: labels_to_ignore must be of type <class 'list'>` or `ValueError: low_score_entity_names must be of type <class 'list'>` when creating a `NerModelConfiguration` _object_ using this _dictionary_.

    `NerModelConfiguration().from_dict(ner_conf_valid_dict)`

3. Observe the error `AssertionError` when verifying that the default _attribute_ `low_score_entity_names` for the NerModelConfiguration class is either a list or a _set_.

    `assert isinstance(NerModelConfiguration().low_score_entity_names, (list, set))`

**Expected behavior**
The `NerModelConfiguration` should process as valid dictionaries with the _set_ type in the values assigned for `labels_to_ignore` and `low_score_entity_names` keys with other types of Collections to be valid, and its _attribute_ `low_score_entity_names` should be a list or a _set_ by default and not a _dictionary_.

**Comment by omri374** [comment]
Thanks! Great improvement.
