### ISSUE TITLE
Support for SpanMarker

### ISSUE THREAD

**Issue by Hveemos** [microsoft/presidio#1237]
I have found that SpanMarker models such as tomaarsen/span-marker-mbert-base-multinerd to be very usefull at NER recognition. But Presidio does not seem to support the class 'span_marker.configuration.SpanMarkerConfig'.

Can I resolve this myself or might this be added as an additional feature?

Regards
Joakim

**Comment by ogencoglu** [comment]
+1 for this

**Comment by ogencoglu** [comment]
Maybe @tomaarsen point some tips.

**Comment by omri374** [comment]
Thanks! Great suggestion. Something along those lines? https://github.com/tomaarsen/SpanMarkerNER?tab=readme-ov-file#using-pretrained-spanmarker-models-with-spacy

**Comment by omri374** [comment]
@Hveemos would you be interested in adding this capability?

**Comment by Hveemos** [comment]
Yes, something along those lines (https://github.com/tomaarsen/SpanMarkerNER?tab=readme-ov-file#using-pretrained-spanmarker-models-with-spacy). But I'm sorry to say that I don't have the time or competency to contribute in this project. I solved this with duct tape instead, i.e. running the SpanMarker on each line and using regex to redact (takes forever though).

**Comment by omri374** [comment]
@Hveemos the easiest solution would be to create a recognizer class and glue the SpanMarker output to a `RecognizerResult` object. See something similar here, we did for the flair package: https://github.com/microsoft/presidio/blob/ca7772ce4919af9b2e08063dc5f0759aa3205fb6/docs/samples/python/flair_recognizer.py#L131

**Comment by ogencoglu** [comment]
UniversalNER is also another interesting generative candidate: https://universal-ner.github.io/
