### ISSUE TITLE
Ability to combine spacy and transformers configs into a single one

### ISSUE THREAD

**Issue by ogencoglu** [microsoft/presidio#1238]
Is it possible to combine spacy and transformers configs into a single one? 

For example 
```
configuration = {
    "nlp_engine_name": "spacy",
    "models": [{"lang_code": "fi", "model_name": "fi_core_news_sm"},
               {"lang_code": "en", "model_name": "en_core_web_sm"},
               {"lang_code": "ru", "model_name": "ru_core_news_sm"},
               ],
}
```
+
```
configuration_hf = {
    "nlp_engine_name": "transformers",
    "models": [{"lang_code": "et", "model_name": {"spacy": "en_core_web_sm", "transformers": "tartuNLP/EstBERT_NER_v2"}},
               ],
}
```

in a single config?

**Comment by omri374** [comment]
Are you interested in running Presidio in parallel to Huggingface?

**Comment by ogencoglu** [comment]
Do I understand you correctly that I can do something like? :

```
configuration = {
    "nlp_engine_name": "spacy",
    "models": [{"lang_code": "fi", "model_name": "fi_core_news_sm"},
               {"lang_code": "en", "model_name": "en_core_web_sm"},
               {"lang_code": "ru", "model_name": "ru_core_news_sm"},
               {"lang_code": "et", "model_name": {"spacy": "en_core_web_sm", "transformers": "tartuNLP/EstBERT_NER_v2"}
               ],
}
```

**Comment by omri374** [comment]
You can either use a `SpacyNlpEngine` or a `TransformersNlpEngine`, but not both. For the configuration you have here, the simplest way would be to:
1. Configure `fi`, `en`, `ru` languages using `SpacyNlpEngine` with the configuration you provided, without the line for `et`.
2. Create a new custom recognizer for the tartuNLP/EstBERT_NER_v2 model. See doc here: https://microsoft.github.io/presidio/samples/python/transformers_recognizer/

This would allow you to have all models running in parallel.

**Comment by ogencoglu** [comment]
Thanks for the swift reply!

**Comment by ogencoglu** [comment]
Continuing the discussion, do I understand correctly that even if I have all models running in parallel (as you described above), I still need to tell the specific language `AnalyzerEngine.analyze` works on such as

```
analyze(
        text=text,
        entities=analyzer.get_supported_entities(),
        language="en",
        return_decision_process=False,
    )
```

and I can not do something like `language=["en", "ru", "et"]` ?

Meaning that, I still need to detect the language of the text or conversation with some language detection tool to be able to route the pipeline to the correct language.

Is my understanding correct?
