### ISSUE TITLE
Deanonymize Operator Mask

### ISSUE THREAD

**Issue by okyx** [microsoft/presidio#1246]
Can i Deanonymize text other than decrypt operator such as mask and custom?

**Comment by omri374** [comment]
Hi, once masking is done, it's impossible to reverse the process (as we are not maintaining the original after masking). Another use case for de-anonmization could be pseudonymization, where we use a dictionary to map original and new, and be able to return the text to its original form.

**Comment by okyx** [comment]
thankyou
