### ISSUE TITLE
Opposite of deny_list

### ISSUE THREAD

**Issue by ogencoglu** [microsoft/presidio#1247]
A field that works as the opposite of `deny_list` (`accept_list` or `allow_list` maybe?) would be super helpful where the entities in the list are not flagged if they are detected as PII. This is not necessarily even related only to ad-hoc recognizers but in general.

**Comment by omri374** [comment]
Does this solve your problem?
https://microsoft.github.io/presidio/tutorial/13_allow_list/

**Comment by ogencoglu** [comment]
Yes! Thanks a lot!
