### ISSUE TITLE
Tensor size conflict from hf-pipeline

### ISSUE THREAD

**Issue by ragesh2000** [microsoft/presidio#1248]
I was working with presidio using a transformer model exactly as the code provided in the comment below
[https://github.com/microsoft/presidio/issues/1239#issuecomment-1871217627](url)

The result was not containing any entities from the transformer model instead a warning
`/home/ragesh/miniconda3/envs/presidio/lib/python3.8/site-packages/spacy_huggingface_pipelines/token_classification.py:203: UserWarning: Unable to process, skipping annotation for doc '{'_source': {'@timestamp': '2023-12-19T06:45:58.322Z', 'log_level': 'DEBUG', 'message': 'Validating ...'`

I tried to debug and it was found the issue is coming from the except block of the following code from the file `spacy_huggingface_pipelines/token_classification.py`

```
for doc in docs:
    try:
        outputs.append(self.hf_pipeline(doc.text))
    except Exception:
        text_excerpt = (
            doc.text if len(doc.text) < 100 else doc.text[:100] + "..."
        )
        warnings.warn(
            f"Unable to process, skipping annotation for doc '{text_excerpt}'"
        )
        outputs.append([])
```
Due to the exception (tensor size conflict) just empty list where appended to the outputs. 
when i just splitted the input (doc) and do the same iteratively in the except block, it was working. Please provide me a better solution  as splitting at random points may not be a better solution all the time.

**Comment by omri374** [comment]
Hi, what is the length of the text? Transformers models have a window size, and if the text is longer, it has to be split into smaller chunks.

**Comment by ragesh2000** [comment]
length would be around 1000. @omri374

**Comment by ragesh2000** [comment]
i have a suggestion that if splitting is needed, that has to be there in the except block if possible. Currently it is just empty list which is getting appended.

**Comment by omri374** [comment]
This is an issue with spacy-huggingface-pipelines, which is a Presidio dependency. 
I would suggest splitting the text beforehand. The try/except block here doesn't do any splitting, it just writes a message in case the processing failed.

**Comment by omri374** [comment]
Hi @ragesh2000, were you able to solve this issue?

**Comment by ragesh2000** [comment]
Instead of skipping annotation i just splitted the input into chunks using langchain document splitter and merged the final result. @omri374
