### ISSUE TITLE
Possibly incorrect type hint for `texts` in `BatchAnonymizerEngine::anonymize_list`

### ISSUE THREAD

**Issue by JosephSBoyle** [microsoft/presidio#1249]
First, thank you for the library!

the signature of BatchAnonymizerEngine::anonymize_list is:
```python
    def anonymize_list(
        self,
        texts: List[Union[str, bool, int, float]],
        recognizer_results_list: List[List[RecognizerResult]],
        **kwargs
    ) -> List[Union[str, object]]:
```
However, the function implicitly supports `List[Any]`: passing a something that isn't a str, bool, int or float simply returns that thing, which I found out whilst moving from the normal anonymizer - which would error when passing `None` - to the batch anonymizer, which surprised me by simply returning the value as-is. This behaviour is desired in my particular case as I'm anonymizing a nullable (i.e `None`-able) SQL field.

Minimal example (see assertion at the bottom)
```python
from typing import Iterable, Union

from presidio_analyzer import BatchAnalyzerEngine
from presidio_anonymizer import BatchAnonymizerEngine


_ANALYZER = BatchAnalyzerEngine()
_ANONYMIZER = BatchAnonymizerEngine()

def anonymize(texts: Iterable[Union[str, None]]) -> list[Union[str, None]]:
    """Anonymize a batch of texts."""
    recognizer_results_list = _ANALYZER.analyze_iterator(texts=texts, language="en")
    anonymized_batch = _ANONYMIZER.anonymize_list(
        texts=texts, recognizer_results_list=recognizer_results_list
    )
    return anonymized_batch

assert anonymize([None]) == [None]  # This works -- type hint of `anonymize_list` maybe implies it should not?
```

I would prefer that we keep this behaviour and document it than raise an error, as is done in the single-text equivalent. 😅 
Perhaps adding a new line to the docstring along the lines of:

```python
        :param texts: List containing the texts to be anonymized (original texts)
            Note: instances of types other than str, bool, int and float will be returned without modification.
```

Happy to work on a PR if needed.

PS:  If I understand the python docs[1] correctly, the return type of the method in question should be `Union[str, Any]` rather than `Union[str, object]`.

[1] https://docs.python.org/3/library/typing.html#the-any-type

**Comment by omri374** [comment]
Hi @JosephSBoyle,
In the `BatchAnonymizerEngine` we decided to allow None values to pass, as tables often have empty cells and the basic `AnonymizerEngine` would raise an error if an empty (or `None`) value is passed.

You are correct that the type hints in this case should be `List[Optional[Union[str, bool, int, float]]]` (which is identical to `Union[str, bool, int, float, None]` but conforms better with the rest of the type hints in the library). 

While the `BatchAnonymizerEngine` doesn't enforce the types, the `BatchAnalyzerEngine` does. If you try to pass something other than None, str, bool, int, float, it would fail.

If you are interested in raising a PR, that would be great!

**Comment by JosephSBoyle** [comment]
Closing as completed.
