### ISSUE TITLE
Use the Presidio Transformers pipeline with a model which is stored locally/ in an S3 bucket

### ISSUE THREAD

**Issue by aayushisanghi** [microsoft/presidio#1260]
Hi! I’m considering Presidio for a de-identification pipeline. However, I don’t want to install models directly from huggingface. Instead, I want to use models stored either locally or in an S3 bucket (which have been pre-installed from huggingface). Does Presidio support this, currently? If yes, can you point me to an example, please? Thank you!

PS - the models I’m referring to can be used in the huggingface transformer pipeline, for the token-classification task.

**Comment by omri374** [comment]
Hi, according to the `spacy-huggingface-pipelines` and `transformers` documentation, you should be able to pass the path to the local model as the in the `model_name` param:

```py
models = [
    {
        "lang_code": "en",
        "model_name": {
            "spacy": "en_core_web_sm",
            "transformers": "path/to/model",
        },
    }
]
```

See more on configuration [here](https://microsoft.github.io/presidio/analyzer/nlp_engines/transformers/#creating-a-configuration-file).

Hope this helps, feel free to post another message if not, or close the issue if yes.

**Comment by aayushisanghi** [comment]
Thank you!
