### ISSUE TITLE
Enhancement Request: Documentation for the New presidio-structured Package

### ISSUE THREAD

**Issue by ebotiab** [microsoft/presidio#1261]
The recently integrated presidio-structured package in the Presidio repository currently lacks comprehensive documentation outlining its core functionalities. To facilitate better understanding and usability of this new addition, I propose the integration into existing documentation. That is, amend the primary documentation sections to include presidio-structured as a distinct module of Presidio. This should encompass a clear description of its capabilities, its role within the Presidio ecosystem, and illustrative examples of its applications.

Alternatively, considering presidio-structured is a recent addition, it may be prudent to introduce a specialized page solely dedicated to this package. This page would detail the novel features, ongoing developments, and potential future enhancements. Such a dedicated space would not only highlight the package's uniqueness but also provide a centralized resource for updates and user guidance.

In either approach, the aim is to ensure that users have clear, accessible information about the presidio-structured package, enabling them to effectively utilize its features and integrate it into their data protection and privacy workflows.

**Comment by omri374** [comment]
Thanks @ebotiab, this is definitely next on our roadmap for the new package.
