### ISSUE TITLE
Presidio demo website seems to be down: https://presidio-demo.azurewebsites.net/

### ISSUE THREAD

**Issue by mdrakiburrahman** [microsoft/presidio#1263]
https://presidio-demo.azurewebsites.net/

![image](https://github.com/microsoft/presidio/assets/46581776/6c04ab74-cf7c-4edc-90ef-e689eb5c4a72)

**Comment by omri374** [comment]
You can use the demo website on Huggingface:
https://huggingface.co/spaces/presidio/presidio_demo
