### ISSUE TITLE
Sample code for LemmaContextAwareEnhancer does not return the expected results

### ISSUE THREAD

**Issue by ckarras** [microsoft/presidio#1265]
**Describe the bug**
I'm testing the sample code in https://github.com/microsoft/presidio/blob/main/docs/tutorial/06_context.md for LemmaContextAwareEnhancer. According to this tutorial, the result should be 0.46 but it is actually 0.01 (exactly the same result as without LemmaContextAwareEnhance)r, so I suspect something is missing from the tutorial.

**To Reproduce**
Download the required spacy model: 
```
python -m spacy download en_core_web_lg
```

Use the following code from the tutorial:
```
from presidio_analyzer import (
    Pattern,
    PatternRecognizer,
    RecognizerRegistry,
    AnalyzerEngine,
)

# Define the regex pattern
regex = r"(\b\d{5}(?:\-\d{4})?\b)"  # very weak regex pattern
zipcode_pattern = Pattern(name="zip code (weak)", regex=regex, score=0.01)

# Define the recognizer with the defined pattern
zipcode_recognizer = PatternRecognizer(
    supported_entity="US_ZIP_CODE", patterns=[zipcode_pattern]
)

registry = RecognizerRegistry()
registry.add_recognizer(zipcode_recognizer)
analyzer = AnalyzerEngine(registry=registry)

from presidio_analyzer import AnalyzerEngine, RecognizerRegistry
from presidio_analyzer.context_aware_enhancers import LemmaContextAwareEnhancer

context_aware_enhancer = LemmaContextAwareEnhancer(
    context_similarity_factor=0.45, min_score_with_context_similarity=0.4
)

registry = RecognizerRegistry()
registry.add_recognizer(zipcode_recognizer)
analyzer = AnalyzerEngine(
    registry=registry, context_aware_enhancer=context_aware_enhancer
)

# Test
results = analyzer.analyze(text="My zip code is 90210", language="en")
print("Result:")
print(results)

```

**Expected behavior**
Confidence score should be 0.46 as mentioned in the tutorial, but it is 0.01

Actual result:
```
Result:
[type: US_ZIP_CODE, start: 15, end: 20, score: 0.01]
```

**Screenshots**

**Additional context**

**Comment by omri374** [comment]
Hi, in the tutorial, the pattern recognizer is created twice. Once without the context and once with. Make sure you use the one with the context words:
```py
from presidio_analyzer import PatternRecognizer

# Define the recognizer with the defined pattern and context words
zipcode_recognizer_w_context = PatternRecognizer(
    supported_entity="US_ZIP_CODE",
    patterns=[zipcode_pattern],
    context=["zip", "zipcode"],
)
```

**Comment by ckarras** [comment]
Thanks, it works as expected by modifying the code to use the variable named zipcode_recognizer_w_context  instead of zipcode_recognizer.

In this case, the tutorial is using the wrong variable, lines 86 and 114 of docs\tutorial\06_context.md should be updated to use the variable named zipcode_recognizer_w_context  instead of zipcode_recognizer.

**Comment by omri374** [comment]
Thanks! We'll fix that.
