### ISSUE TITLE
Combination of FlairRecognizer with different PatternRecognizers (and defining their order of execution)

### ISSUE THREAD

**Issue by danilyef** [microsoft/presidio#1273]
Hello,

I have a general question about combination of the `FlairRecognizer` with different `PatternRecognizers`.

Suppose I have created a `FlairRecognizer`:

```
from presidio_analyzer import RecognizerRegistry
from presidio_analyzer.nlp_engine import NlpEngine, NlpEngineProvider
from presidio_analyzer import AnalyzerEngine, RecognizerRegistry, PatternRecognizer, Pattern

configuration = {
    "nlp_engine_name": "spacy",
    "models": [
        {"lang_code": "de", "model_name": "de_core_news_lg"}
    ],
}


# Create NLP engine based on configuration
provider = NlpEngineProvider(nlp_configuration=configuration)
nlp_engine = provider.create_engine()



# Default recognizer
registry = RecognizerRegistry()
registry.load_predefined_recognizers()

# Analyzer
analyzer = AnalyzerEngine(registry=registry, nlp_engine=nlp_engine, supported_languages=["de"])

# Flair Recognizer
flair_recognizer = FlairRecognizer(supported_language="de")
analyzer.registry.add_recognizer(flair_recognizer)
registry.remove_recognizer("SpacyRecognizer")
```

I also have defined some of `PatternRecognizers`:

```
email_regex = r"[\w\.-]+@[\w\.-]+\.\w+"
email_pattern = Pattern(name="email_pattern", regex=email_regex, score=0.9)
email_recognizer = PatternRecognizer(supported_entity="EMAIL", patterns=[email_pattern],name = 'EMAIL_RECOGNIZER')

phone_regex = r'(?:\+43|0043|0)?\s?(?:660|678|665|686|690|663|670|699)\s?(?:\d{3})\s?(?:\d\s*\d\s*\d\s*\ds*\d|\d\s*\d\s*\d\s*\d|\d{4,5})'
phone_pattern = Pattern(name="phone_pattern", regex=phone_regex, score=0.9)
phone_recognizer = PatternRecognizer(supported_entity="PHONE", patterns=[phone_pattern],name = 'PHONE_RECOGNIZER')
```

But when I add them to the analyzer, I don't succeed:

```
analyzer.registry.add_recognizer(link_recognizer)
analyzer.registry.add_recognizer(phone_recognizer)
print(analyzer.get_recognizers()) #outputs only Flair Recognizer
```

My question is: is it possible to add additional PatternRecognizers to the Flair and if yes then how? 
Another question is: is it possible(if yes then how?) to define the order of the execution of the Recognizers?

**Comment by omri374** [comment]
Looks like the issue is with thesupported languages. Your pattern recognizers have no language definition, hence they are supporting English by default, but your Analyzer Engine is defined to support only German, so non-German supporting recognizers are ignored.

Can you please try to pass a language parameter to the pattern recognizer and try again?

**Comment by danilyef** [comment]
That worked, thank you!

Another question: do you know is there is a specific order in which, recognizers are executed? 

- If yes, is there any quick way to define it? Because if you do a guick for loop it looks like they are in the random order:
```
for i in analyzer.get_recognizers():
    print(i.name)
```
