### ISSUE TITLE
Tutorial on how to custom a new field_type

### ISSUE THREAD

**Issue by teo-chenglim** [Microsoft/presidio#128]
**Describe the bug**
Please create an Tutorial on how to custom a new field_type

**To Reproduce**
N/A

**Expected behavior**
A good framework shall allow public to contribute

**Screenshots**
N/A

**Additional context**
Give me a head start, I may able to contribute.

**Comment by omri374** [comment]
Hi @teo-chenglim 
On our next release there will be documentation + support for new field types. Release should take place in the next few days.

**Comment by eladiw** [comment]
https://github.com/Microsoft/presidio/pull/132

**Comment by omri374** [comment]
Documentation was updated. Closing issue
