### ISSUE TITLE
Anonymizer does not work if not separated by spaces

### ISSUE THREAD

**Issue by Siddhartha90** [microsoft/presidio#1301]
**Describe the bug**

`test data 630-596-1111`

redacts ok to give back `test data`

but `test data630-596-1111`

does not redact the phone number.

**To Reproduce**

```

text_to_anonymize="test data630-596-1111"
try:
    nlp = spacy.load("en_core_web_lg")
except OSError:
    # Model not found, download it
    spacy.cli.download("en_core_web_lg")
    nlp = spacy.load("en_core_web_lg")

analyzer = AnalyzerEngine()
anonymizer = AnonymizerEngine()

analyzer_results = analyzer.analyze(
    text=text_to_anonymize,
    entities=["PHONE_NUMBER", "EMAIL_ADDRESS", "URL", "LOCATION"],
    language="en",
)
scrubbed_text = anonymizer.anonymize(
    text=text_to_anonymize,
    analyzer_results=analyzer_results,
    operators={"DEFAULT": OperatorConfig("redact", {})},
).text

print(scrubbed_text)

```

**Expected behavior**
Phone number gets scrubbed.

I'm on:

**presidio-analyzer==2.2.351
presidio-anonymizer==2.2.351
spacy==3.7.2
spacy-legacy==3.0.12
spacy-loggers==1.0.5
**

**Comment by omri374** [comment]
Presidio uses the [phonenumbers](https://github.com/daviddrysdale/python-phonenumbers) package to detect phone numbers, and it seems that the package's logic doesn't detect phone numbers without spaces before and after. As @VMD7 suggested on the other issue, you can try using a NER model which was trained on phone numbers and see if you get better results. Alternatively, you can create a custom pattern recognizer to detect phone numbers with no spaces around them.

**Comment by Siddhartha90** [comment]
Thanks @omri374, does your PR above with the leniency param help here as well? I'm not sure if that's a parameter exposed via the library

**Comment by omri374** [comment]
Yes it should, but it's not released yet. Once it is (or if you clone the repo), you should be able to adjust it, for example:
```py
from presidio_analyzer import AnalyzerEngine, RecognizerRegistry

registry = RecognizerRegistry()
registry.load_predefined_recognizers()

phone_recognizer = [rec for rec in registry.recognizers if rec.name == "PhoneRecognizer"][0]
phone_recognizer.leniency = 0 # update phone number leniency

analyzer_engine = AnalyzerEngine(registry=registry)

analyzer_engine.analyze(text="My US number is415 555-1032", language="en")
```

Note that this is `leniency` parameter is only supported for phone numbers. Other entities have other detection methods and could still fail to identify a number not separated by spaces.
