### ISSUE TITLE
What does `annotate_spans_key` do in the `TransformersNlpEngine`?

### ISSUE THREAD

**Issue by AAnirudh07** [microsoft/presidio#1326]
Hello,
I was going through the source code for `TransformersNlpEngine` and noticed that the `nlp.add_pipe` method accepts a parameter named `annotate_spans_key`. This is hard-coded as "bert-base-ner", regardless of the transformers NER model used. Is this a default or placeholder value that enables the use of `annotate="spans"`? Alternatively, could I set `annotate_spans_key` to the name of the transformers model I'm using? 

[Here's](https://github.com/microsoft/presidio/blob/1911a3d6befd48e0cac327cbdffd1f7f37565fcc/presidio-analyzer/presidio_analyzer/nlp_engine/transformers_nlp_engine.py#L94) where `annotate_spans_key` is set to the constant value, and [here's](https://github.com/microsoft/presidio/blob/1911a3d6befd48e0cac327cbdffd1f7f37565fcc/presidio-analyzer/presidio_analyzer/nlp_engine/transformers_nlp_engine.py#L71) where it's defined.

Thank you!

**Comment by omri374** [comment]
It is an internal key used by tge 'spacy-huggingface-pipelines' package. It doesn't affect the prediction process.

**Comment by AAnirudh07** [comment]
got it, thanks a lot!
