### ISSUE TITLE
Is it possible to redact entities not supported by presidio?

### ISSUE THREAD

**Issue by AAnirudh07** [microsoft/presidio#1327]
Hello,
Is it possible to use spacy & transformer models with entity types that are not supported by presidio? Earlier this was possible using something like this:

```python
nlp_engine = SpacyNlpEngine(...)
entity_types = [...] # E.g. "MONEY", "PERSON" etc.

registry = RecognizerRegistry()
registry.load_predefined_recognizers()
registry.remove_recognizer("SpacyRecognizer")

spacy_label_groups = [({ent}, {ent}) for ent in entity_types]
sr = SpacyRecognizer(
            supported_language="en",
            supported_entities=entity_types
            check_label_groups=spacy_label_groups,
)

registry.add_recognizer(sr)
self.analyzer: AnalyzerEngine = AnalyzerEngine(
            registry=registry,
            supported_languages="en",
            nlp_engine=nlp_engine,
)

```

Now, It looks like this is not possible due to the model_to_presidio_entity_mapping parameter. Any help would be greatly appreciated!

**Comment by omri374** [comment]
Hi, any entity specified in the model_to_presidio_entity_mapping would be added to the supported entities. You can add any entity the model is capable of predicting.

**Comment by AAnirudh07** [comment]
got it, ty!
