### ISSUE TITLE
96c word is being incorrectly identified as PERSON

### ISSUE THREAD

**Issue by bhanu-pappala** [microsoft/presidio#1352]
**Describe the bug**
96c word is being incorrectly identified as PERSON if the query is like "what is letter 96c".
It is fine if I remove letter word.

**Expected behavior**
what is letter 96c

**Screenshots**
![image](https://github.com/microsoft/presidio/assets/67595337/d76370d7-f9d0-409b-bd33-62242734ee97)
**Additional context**
Model being used is spacy encore web lg
Package used: presidio-analyzer 
Tried versions 2.2.351, 2.2.354.

**Comment by omri374** [comment]
Each NER model could have false positives. Consider looking into other models, such as those coming from huggingface or flair. Our demo website allows you to easily experiment with a few selected models, and the documentation has details on how to integrate models other than spaCy en_core_web_lg

- Demo: https://huggingface.co/spaces/presidio/presidio_demo
- Docs: https://microsoft.github.io/presidio/analyzer/customizing_nlp_models/
