### ISSUE TITLE
cannot import name 'AnonymizerConfig'

### ISSUE THREAD

**Issue by benstoneham** [microsoft/presidio#1399]
**Describe the bug**
I'm seeing this error when trying to import AnonymizerConfig from presidio_anonymizer:

ImportError: cannot import name 'AnonymizerConfig' from 'presidio_anonymizer' (presidio/venv/lib64/python3.9/site-packages/presidio_anonymizer/__init__.py)

**To Reproduce**
1. Python 3.9 venv environment.
2. Pip install presidio_anonymizer presidio-anonymizer  [all dependencies including SPACY automatically imported)
presidio-analyzer   2.2.354
presidio-anonymizer 2.2.354
3. run: python3 -c "from presidio_anonymizer import AnonymizerConfig; print(AnonymizerConfig)"

**Expected behaviour**
AnonymizerConfig is imported

**List of installed packages**
Package             Version
annotated-types     0.7.0
blis                0.7.11
catalogue           2.0.10
certifi             2024.6.2
charset-normalizer  3.3.2
click               8.1.7
cloudpathlib        0.18.1
confection          0.1.5
cymem               2.0.8
filelock            3.15.1
idna                3.7
Jinja2              3.1.4
langcodes           3.4.0
language_data       1.2.0
marisa-trie         1.2.0
markdown-it-py      3.0.0
MarkupSafe          2.1.5
mdurl               0.1.2
murmurhash          1.0.10
numpy               1.26.4
packaging           24.1
phonenumbers        8.13.39
pip                 24.0
preshed             3.0.9
presidio-analyzer   2.2.354
presidio-anonymizer 2.2.354
pycryptodome        3.20.0
pydantic            2.7.4
pydantic_core       2.18.4
Pygments            2.18.0
PyYAML              6.0.1
regex               2024.5.15
requests            2.32.3
requests-file       2.1.0
rich                13.7.1
setuptools          59.6.0
shellingham         1.5.4
smart-open          7.0.4
spacy               3.7.5
spacy-legacy        3.0.12
spacy-loggers       1.0.5
srsly               2.4.8
thinc               8.2.4
tldextract          5.1.2
tqdm                4.66.4
typer               0.12.3
typing_extensions   4.12.2
urllib3             2.2.1
wasabi              1.1.3
weasel              0.4.1
wrapt               1.16.0

**Comment by omri374** [comment]
Presidio doesn't have an object called `AnonymizerConfig` since version 2. Could you please provide more details on what you are trying to achieve?

**Comment by benstoneham** [comment]
Thank you for your reply, sorry for the slow response. I was experimenting with Presidio and following an old set of docs - now resolved so thank you again!
