### ISSUE TITLE
feature request: analyser shall return the matching string and original text

### ISSUE THREAD

**Issue by teo-chenglim** [microsoft/presidio#143]
**Describe the bug**
from
https://github.com/Microsoft/presidio/blob/master/docs/tutorial_service.md
Sample 4: Custom anonymization

*** Currently the result return is
{
    "field": {
      "name": "US_DRIVER_LICENSE"
    },
    "score": 0.65,
    "location": {
      "start": 176,
      "end": 184,
      "length": 8
    }
  }

*** it would be good if you can return so that it is easier to debug

    "field": {
      "name": "US_DRIVER_LICENSE"
    },
    "score": 0.65,
    "location": {
      "start": 176,
      "end": 184,
      "length": 8
    }
    "match_text": "AC333991"
  }

**** it will be good if you can also return the original "text"
{
.
.
.
"text":"John Smith lives in New York. We met yesterday morning in Seattle. I called him before on (212) 555-1234 to verify the appointment. He also told me that his drivers license is AC333991"
}

**To Reproduce**

```bash
$ echo -n '{"text":"John Smith lives in New York. We met yesterday morning in Seattle. I called him before on (212) 555-1234 to verify the appointment. He also told me that his drivers license is AC333991", "analyzeTemplate":{"allFields":true}  }' | http -F --verify=no https://192.168.1.44/api/v1/projects/1/analyze
```

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
it is very common that API also return original text plus matching string.

**Comment by omri374** [comment]
Hi @teo-chenglim,
This is definitely doable. The reason why we didn't include it in the first place, is because in some cases the next part in the pipeline is supposed to be 'PII free'. The matched text is the PII entity. However we'll give it some thought and update in case this gets implemented. 

Is taking the original text from the request and extracting the matched substring using start and end indices an option?

**Comment by teo-chenglim** [comment]
Like your demo here https://presidio-demo.westeurope.cloudapp.azure.com/

Is taking the original text from the request and extracting the matched substring using start and end indices an option? Yes. However return original string is also good for debugging propose. Could be optional and hidden, but good to have.

When we have more than 1 entity, using start and end replace the string the position would move after first replaced. One way is to use reverse matching base on "start position", replace from "last entity" to "first entity".. other people would do marker/markup. However this will need you to sort the entity matching "start position" also.

*** Marker example
from:
Credit card: 4095-2609-9393-4932
to:
**** Design 1
Credit card:  <credit_card_start>4095-2609-9393-4932<credit_card_end>
**** Design 2
Credit card:  <CREDIT_CARD>4095-2609-9393-4932<CREDIT_CARD>
**** Design 3
Credit card:  <CREDIT_CARD>

*** Suggestion

echo -n '{"text":"The APA is an Amaris product", "analyzeTemplate":{"allFields":true}, "show_original_text": true, "show_matching_text": true  }' | http -F --verify=no https://192.168.1.44/api/v1/projects/1/analyze

**Comment by omri374** [comment]
Small update: We're considering an implementation of this enhancement, but it is not planned to be actively worked on during the following 4 weeks.

**Comment by CodeRunRepeat** [comment]
Change in the project's backlog. Not planned for implementation within the next 2 months.
