### ISSUE TITLE
Adding a French Date Recognizer 

### ISSUE THREAD

**Issue by cpetresc** [microsoft/presidio#1431]
**Is your feature request related to a problem? Please describe.**
Dear Presidio Team at Microsoft,

When I try to use your library, Presidio, on French text using the SpaCy model, I am unable to detect French dates. For example, '3 janvier 2001', 'janvier 2001', or '3 janvier' are not recognized.

**Describe the solution you'd like**
I would like to have the capability to detect French dates with a dedicated French date recognizer

**Describe alternatives you've considered**
I have written a class called FrDateRecognizer that can detect French dates using regex. You can find this class in the file attached to this issue.
[fr_date_recognizer.zip](https://github.com/user-attachments/files/16511260/fr_date_recognizer.zip)

**Additional context**

**Comment by omri374** [comment]
Hi, have you tried using a French NER model from either spaCy or Huggingface? They usually have good support for dates and there's no need for rule based logic.
