### ISSUE TITLE
Presidio Image Redactor for Korean Documents

### ISSUE THREAD

**Issue by khawar-islam** [microsoft/presidio#1441]
Dear Presidio Team,

Thanks for your great work. I am looking for presidio image redactor work for Korean language and I have also find that there is Korean model available in SpaCy models. How I can use it for images? Are there any tutorials ? I have images and PDF 

https://spacy.io/models/ko

Regards,
Khawar

**Comment by omri374** [comment]
The image capabilities in Presidio (presidio-image-redactor) build upon the text version. You can adapt Presidio to handle text in Korean, and then use this adapted version for image redaction. See examples here: https://github.com/microsoft/presidio/issues/1411 (which is for DICOM images, but works similarly for regular images too)

**Comment by khawar-islam** [comment]
thanks for you comment. Do you have any example or procedure where u added some new language for instance Japanese?  I will adapt the same procedure for Korean.
