### ISSUE TITLE
SegmentedAdaptiveThreshold in image_processing_engine typo?

### ISSUE THREAD

**Issue by emmantel** [microsoft/presidio#1442]
Hello, first time describing a 'bug' (not sure if this is the right place) 

In the presidio_image_redactor, image_processing_engine.py, class SegmentedAdaptiveThreshold, preprocess_image(),
line 191, 

```
if isinstance(image, np.ndarray):
            image = self.convert_image_to_array(image)
```

I believe this should be

```
if not isinstance(image, np.ndarray):
            image = self.convert_image_to_array(image)
```

since the point of this line is to convert PIL images to np ndarray and passing in an ndarray will simply return it unchanged. I was getting an error trying to run preprocess_image with a PIL Image as input, but changing that line fixed it. Let me know if I ma misunderstanding something!

Best,
Emma

**Comment by omri374** [comment]
Hi @emmantel, you're right, this is indeed a bug. Are you interested in creating a PR?

**Comment by omri374** [comment]
cc @ayabel
