### ISSUE TITLE
Context with hash marks do not work as expected 

### ISSUE THREAD

**Issue by claesmk** [microsoft/presidio#1452]
**Describe the bug**
In the predefined US_SSN recognizer [context](https://github.com/microsoft/presidio/blob/4aeb56bf5e2e1187dd535785cc41590ca3a4d5eb/presidio-analyzer/presidio_analyzer/predefined_recognizers/us_ssn_recognizer.py#L24) the ssn# and ss# context words do not work as expected because spacy tokenizes the hash mark: 
```
[decision_process][INFO][None][nlp artifacts:{"entities": ["My ssn#"], "tokens": ["My", "ssn", "#", "is", "123", "-", "45", "-", "1234"], "lemmas": ["my", "ssn", "#", "be", "123", "-", "45", "-", "1234"], "tokens_indices": [0, 3, 6, 8, 11, 14, 15, 17, 18], "keywords": ["ssn", "123", "45", "1234"], "scores": [0.85]}]
```
**ssn#** works OK because this is tokenized as ["ssn" and "#"] and ssn is also in the context list, however, **ss#** does not work 

```
[decision_process][INFO][None][nlp artifacts:{"entities": [], "tokens": ["My", "ss", "#", "is", "123", "-", "45", "-", "1234"], "lemmas": ["my", "ss", "#", "be", "123", "-", "45", "-", "1234"], "tokens_indices": [0, 3, 5, 7, 10, 13, 14, 16, 17], "keywords": ["ss", "123", "45", "1234"], "scores": []}]
```

**To Reproduce**
1. Use US_SSN entity and a string with ss# 
2. See that it is not detected as context (0.5 default score is not improved)
```
{'recognizer': 'UsSsnRecognizer', 'pattern_name': 'SSN5 (medium)', 'pattern': '\\b([0-9]{3})[- .]([0-9]{2})[- .]([0-9]{4})\\b'...edium)`', 'score_context_improvement': 0, 'supportive_context_word': '', 'validation_result': None, 'regex_flags': regex.I|M|S}
````

**Expected behavior**
All words in the predefined [context](https://github.com/microsoft/presidio/blob/4aeb56bf5e2e1187dd535785cc41590ca3a4d5eb/presidio-analyzer/presidio_analyzer/predefined_recognizers/us_ssn_recognizer.py#L24) should be detected correctly.  If values with a hash mark cannot be detected correctly they should at least be removed from the list.

**Screenshots**
See logging and debugger output above

**Additional context**
n/a

**Comment by omri374** [comment]
Thanks, and apologies for the delay in answering. The context words are currently used by the existing context mechanism (`LemmaContextAwareEnhancer`) but there are alternative implementations one can think of, for example comparing substrings. Therefore, I don't think it's a good idea to remove those. if you or anyone else is interested in creating an alternative context approach, we'd be happy to review it and incorporate it into the package.

**Comment by claesmk** [comment]
@omri374 that's fine - however in the meanwhile do you think it makes sense to remove ss# and ssn# from the [default](https://github.com/microsoft/presidio/blob/c54ce2b9cf8795a168711a9fc6954d47d3269683/presidio-analyzer/presidio_analyzer/predefined_recognizers/us_ssn_recognizer.py#L30) CONTEXT since they don't actually work?

**Comment by omri374** [comment]
Sure, that makes sense. Would you like to create a PR?
