### ISSUE TITLE
AzureAILanguageRecognizer not working through the yaml configuration

### ISSUE THREAD

**Issue by omri374** [microsoft/presidio#1457]
I have an AI application and middleware proxy which makes a call to the Presidio Analyzer and Anonymizer containers with the users' prompt, and expects to receive a callback with the PII (e.g. names replaced by <PERSON>) deleted.

The default SpaCY NLP model misses some less common names, so I want to integrate the commercial AAI service as [described here](https://microsoft.github.io/presidio/samples/python/text_analytics/). In my Docker deploy-compose.override.yml file I have the following services defined:

```
  presidio-anonymizer:
    image: http://mcr.microsoft.com/presidio-anonymizer
    restart: always
    ports:
      - "127.0.0.1:5001:3000"
  presidio-analyzer:
    image: http://mcr.microsoft.com/presidio-analyzer
    restart: always
    ports:
      - "127.0.0.1:5002:3000"
    environment:
      - AZURE_AI_KEY=REDACTED
      - AZURE_AI_ENDPOINT=https://REDACTED.azure.com/
    volumes:
      - ./presidio/default_recognizers.yaml:/usr/bin/presidio-analyzer/presidio_analyzer/conf/default_recognizers.yaml
```

I am attempting to use the predefined recognizer at https://github.com/microsoft/presidio/blob/main/presidio-analyzer/presidio_analyzer/predefined_recognizers/azure_ai_language.py by adding the following lines to the default_recognizers.yaml file which I am bind mounting into the Analyzer container with the following lines added:

```
  - name: AzureAILanguageRecognizer
    type: predefined

```
Unfortunately when I attempt to start up the Analyzer container, it crash loops with this error in the container logs:

```
Traceback (most recent call last):
  File "/usr/bin/presidio-analyzer/app.py", line 138, in <module>
    server = Server()
  File "/usr/bin/presidio-analyzer/app.py", line 44, in __init__
    self.engine: AnalyzerEngine = AnalyzerEngineProvider(
  File "/usr/bin/presidio-analyzer/presidio_analyzer/analyzer_engine_provider.py", line 75, in create_engine
    registry = self._load_recognizer_registry(
  File "/usr/bin/presidio-analyzer/presidio_analyzer/analyzer_engine_provider.py", line 121, in _load_recognizer_registry
    registry = provider.create_recognizer_registry()
  File "/usr/bin/presidio-analyzer/presidio_analyzer/recognizer_registry/recognizer_registry_provider.py", line 59, in create_recognizer_registry
    recognizers = RecognizerListLoader.get(
  File "/usr/bin/presidio-analyzer/presidio_analyzer/recognizer_registry/recognizers_loader_utils.py", line 229, in get
    recognizer_instances.append(recognizer_cls(**kwargs))
TypeError: __init__() got an unexpected keyword argument 'context'
```

Would you be able to provide any guidance what I can do in order to get the integration working? It's not totally clear to me from the documentation how to add the AAI service to the Recognizer Registry – what additionally I need to do.

Thanks in advance.

_Originally posted by @whalygood in https://github.com/microsoft/presidio/discussions/1456_

**Comment by omri374** [comment]
Hi @whalygood, there's indeed a bug here. The AzureAILanguageRecognizer should include a context parameter as input (even if it's not using it). I'll create a PR shortly.

**Comment by whalygood** [comment]
Hi @omri374, thanks for getting back on this. I see that the PR is now merged.
But upon pulling the container I don't believe there is a new version of the image. 
If I wish to build the presidio-analyzer container from the Dockerfile, are these the correct steps to follow?

1. Add these lines to the Dockerfile after the `RUN pip install poetry` line
```
RUN pip install azure-textanalytics
RUN pip install azure-core
RUN pip install "presidio-analyzer[azure-ai-language]"
```

2. Add these after line 81 in app.py

```
AZURE_AI_KEY = "<YOUR_AI_LANGUAGE_KEY>"
AZURE_AI_ENDPOINT = ""<YOUR_AI_LANGUAGE_ENDPOINT>/"
azure_ai_language = AzureAILanguageRecognizer()
recognizer_result_list.add_recognizer(azure_ai_language)
```

3. Rebuild the container? Any special flags I should pass when building?

**Comment by whalygood** [comment]
Preferably I want to set the AZURE_AI_KEY and AZURE_AI_ENDPOINT as an env variable instead of hard coding it into app.py. Also, I am not sure that I want to create a class for AzureAILanguageRecognizer() through app.py, if it is possible to do it through configuration in the default_recognizers.yaml file.

Once the patched image is pushed to the MCR repo, can I simply bind mount a default_recognizers.yaml file into the container with these lines added? 

```
  - name: AzureAILanguageRecognizer
    type: predefined
```

Is it perhaps required to include `ta_client: "test"` also as I saw that as part of the commits? 
Then start up the container with those env variables for the Azure credentials, correct?

**Comment by omri374** [comment]
closing as the PR addressed the core bug in this issue
