### ISSUE TITLE
Expose allow_list in REST AnalyzeRequest

### ISSUE THREAD

**Issue by nickzelei** [microsoft/presidio#1470]
**Is your feature request related to a problem? Please describe.**
I see examples in documentation around specifying an `allow_list` when invoking the analyzer, but it doesn't seem to be exposed via the REST interface.

**Describe the solution you'd like**
Expose the `allow_list` in the body of the AnalyzeRequest POST.

POST `/analyze`
```
{
    "text": "John Smith drivers license is AC432223 and the zip code is 12345",
    "language": "en",
    "score_threshold": 0.6,
    "allow_list": ["John"]
}
```

**Describe alternatives you've considered**
None

**Additional context**
I'm using Presidio in a REST format as the code I'm writing is not written in Python.

**Comment by omri374** [comment]
Thanks for your suggestion. Will you be interested in creating a pull request?
