### ISSUE TITLE
Add .NET Support for Microsoft.Extensions.AI / Aspire

### ISSUE THREAD

**Issue by luisquintanilla** [microsoft/presidio#1481]
As a .NET developer, I want access to Presidio's PII redaction capabilities. However, since there's no .NET SDK, I'm unable to use it. 

That said, it's possible to integrate into my .NET applications using the container. 

It'd be great to add 2 .NET resources to this repo.

- [.NET Aspire Integration](https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/integrations-overview)
  - Hosting (Provisions container)
  - Client (Registers HTTPClient to access Presidio endpoints)
- [Microsoft.Extensions.AI Middleware](https://github.com/dotnet/ai-samples/blob/main/src/microsoft-extensions-ai/abstraction-implementations/AbstractionImplementationExamples/LoggingChatClient.cs) - Given a Presidio HTTPClient, implementations of Microsoft.Extensions.AI can leverage it as part of their inferencing pipeline.

For more details:

- [Microsoft.Extensions.AI](https://devblogs.microsoft.com/dotnet/introducing-microsoft-extensions-ai-preview/)
- [.NET Aspire](https://learn.microsoft.com/en-us/dotnet/aspire/get-started/aspire-overview)

**Comment by omri374** [comment]
Hi, it'd be great adding this as a sample in the repo, and can be done using the OpenAPI definition. Supporting an official .Net package is currently not on our roadmap.
