### ISSUE TITLE
spacy_nlp_engine: missing spacy.cli

### ISSUE THREAD

**Issue by tigersoldier** [microsoft/presidio#1487]
**Describe the bug**
In spacy_nlp_engine.py, it only imports spacy but calls `spacy.cli.download`: https://github.com/microsoft/presidio/blob/a21a17c2cbcb212b36489c1e8d73118b28ff8ff9/presidio-analyzer/presidio_analyzer/nlp_engine/spacy_nlp_engine.py#L64

This will throw the following exception for spacy <= 3.7.0

```
    @staticmethod
    def _download_spacy_model_if_needed(model_name: str) -> None:
        if not (spacy.util.is_package(model_name) or Path(model_name).exists()):
            logger.warning(f"Model {model_name} is not installed. Downloading...")
>           spacy.cli.download(model_name)
E           AttributeError: module 'spacy' has no attribute 'cli'

.venv/lib/python3.10/site-packages/presidio_analyzer/nlp_engine/spacy_nlp_engine.py:65: AttributeError
```

Spacy 3.7.1 has `spacy.cli` imported when you import spacy only. So either fixed the code to explicitly import spacy.cli, or update the dependency requirement to depend on spacy>=3.7.1

**To Reproduce**
1. Install spacy==3.7.0
2. Call `create_engine` that triggers this path

**Expected behavior**
Should not throw this exception

**Screenshots**
N/A

**Additional context**
N/A

**Comment by omri374** [comment]
Thanks, this is a change in behavior that the spaCy team quickly reverted:
https://github.com/explosion/spaCy/issues/13039
https://github.com/explosion/spaCy/pull/13040

**Comment by omri374** [comment]
As far as I know, this issue happens only in version 3.7.0, so 3.6.9 and 3.7.1 should still work.

**Comment by omri374** [comment]
Yes. Would you be interested in creating a PR?
