### ISSUE TITLE
Using Patterns as post-processing to improve NER

### ISSUE THREAD

**Issue by aliceIRB** [microsoft/presidio#1492]
I am not using the default spaCy model but instead use GLiNER. I want to detect person names in my script and have the label "PERSON NAME" in my list of entities (GLiNER requires you to be a bit specific in your labels). However, I still have problems with it detecting nouns like "customer" or "owner" and a person name. 

I tried to add a custom recognizer like so:
```
# # Define the regex pattern in a Presidio `Pattern` object:
name_pattern = Pattern(name="name_pattern", regex="\b[A-Z][a-z]*?\b", score=0.85)

# # Define the recognizer with one or more patterns
name_recognizer = PatternRecognizer(supported_entity="PERSON NAME", patterns=[name_pattern])
```
However that didn't help because it acts independently from my model. Is there a way to apply regex to specific entities as a sort of post processing method? So I let GLiNER detect all my "PERSON NAME" entities and then it also looks to see if it meets the case of my pattern, in which one word in the string must start with a capital letter. 

I also saw that analyze method has the "allow_list_match" parameter but I couldn't get this to work either, where it should ignore strings that only contain lower case letters like so:

`analyzer.analyze(text=text, language="en", entities=["PERSON NAME"], return_decision_process=True, allow_list_match=r"^[a-z\s]+$")`

Of course I could apply a post-processing technique myself fairly easily but I feel like I am not correctly understanding how to user patterns and custom recognizers.

**Comment by omri374** [comment]
Hi,
One way to achieve this is to create a custom `EntityRecognizer` which calls both the GLiNER model, and the pattern validation. in the `analyze` method of this class, you would first call the model, and then validate the output using the regex. 

Hope this helps!

**Comment by aliceIRB** [comment]
Perfect, that's exactly what I need. Thanks!
