### ISSUE TITLE
PII Masking Not Working for Languages (i.e French, Spanish) Other Than English

### ISSUE THREAD

**Issue by IbrarBabar** [microsoft/presidio#1493]
**Describe the bug**
 PII masking works fine for English text but throws an error for French text. The error message states that no matching recognizers were found. This might be due to missing or unsupported models for French.

**To Reproduce For English:**
```
from presidio_analyzer import AnalyzerEngine
from presidio_anonymizer import AnonymizerEngine
text = "My name is John Doe. My phone number is 123-456-7890, and my email is john.doe@example.com."
analyzer = AnalyzerEngine()
results = analyzer.analyze(text=text, language='en')
anonymizer = AnonymizerEngine()
anonymized_text = anonymizer.anonymize(text=text, analyzer_results=results)
print(anonymized_text)
```
**Output**
`My name is <PERSON>. My phone number is <PHONE_NUMBER>, and my email is <EMAIL_ADDRESS>.`

**For French**
```
from presidio_analyzer import AnalyzerEngine
from presidio_anonymizer import AnonymizerEngine
text = "Je m'appelle John Doe. Mon numéro de téléphone est le 123-456-7890, et mon e-mail est john.doe@example.com."
analyzer = AnalyzerEngine()
results = analyzer.analyze(text=text, language='fr')
anonymizer = AnonymizerEngine()
anonymized_text = anonymizer.anonymize(text=text, analyzer_results=results)
print(anonymized_text)
```
**Error**
`ValueError: No matching recognizers were found to serve the request.
`

**Expected behavior** The tool should anonymize PII in French text the same way it does for English.
**Additional context** It seems the issue might be related to missing language models or recognizers for French. **Please advise on how to resolve this or if there is a specific model to download for French or other languages.**

**Comment by omri374** [comment]
Please see this: https://microsoft.github.io/presidio/analyzer/languages/

**Comment by omri374** [comment]
Closing issue, please re-open if something isn't clear or there are other issues.
