### ISSUE TITLE
Custom Operator creates unknown strings in the output.

### ISSUE THREAD

**Issue by mroxdf** [microsoft/presidio#1494]
**Describe the bug**
I added a Custom Operator that replaces a postal code with the according state via an api_request. 
When i use the operator, the anonymizer returns the string "PII" and afterwards the PLZ itself. 

The PII strings raise several errors in my code which i could work around but i prefer a cleaner solution.

```

class ErsetzPLZmitBundesland(Operator):


    def __call__(self, text: str) -> str:
        return self.operate(text)
    
    def operate(self, text: str = None, params: Dict = None) -> str:
        
        try: 
            print(text)
            if text.isdigit() and len(text) == 5:

                api_url = f"https://zip-api.eu/api/v1/info/DE-{text}"
                antwort = requests.get(api_url)
                antwort.raise_for_status()


                api_antwort = antwort.json()

                bundesland = api_antwort.get("state")

                if api_antwort.get("error") == True and not bundesland:
                    raise ValueError(text, "ist keine bekannte Postleitzahl")
                    return "[PLZ %s nicht erkannt]" % text
                

                return "[Ort in %s]" % bundesland
            
            else:
                raise ValueError("Inkorrekter Input")
        
        except Exception as e:
            return "[Inkorrekter Input]"


    def validate(self, params: Dict) -> None:
        """Validate that the parameters are correct (in this case, no extra validation needed)."""
        pass

    def operator_name(self) -> str:
        """Return the operator name."""
        return "ErsetzPLZmitBundesland"

    def operator_type(self) -> str:
        """Return the operator type."""
        return "Anonymize"

```

and i call the function with: 

```
Text = "Hallo. Ich wohne glücklich seit 23330 Tagen und 30 Jahren in meiner Heimatstadt in 10409 Buxtehude und bin 45 Jahre alt."


Ergebnis = AnalyzerEngineDE.analyze(
    text=Text,
    language="de",
    score_threshold=0.1,
    context=AlterIdentifikator.context
    )


print(Ergebnis)


Anonymisierer = AnonymizerEngine()
Anonymisierer.add_anonymizer(ErsetzPLZmitBundesland)


operators = {"PLZ": OperatorConfig("custom", {"lambda": ErsetzPLZmitBundesland()})}


# Führt die Anonymisierung durch, inkl. der PLZ-Bundesland-Umwandlung
Anonymized_text = Anonymisierer.anonymize(
    text=Text,
    analyzer_results=Ergebnis,
    operators=operators
)

nurtext = Anonymized_text.text

print(nurtext)
```

Which results in the output: 

['PERSON', 'EMAIL', 'LOCATION', 'AGE', 'ORGANIZATION', 'PLZ', 'NRP', 'DATE_TIME', 'ID', 'PHONE_NUMBER', 'ALTER']
[type: PLZ, start: 83, end: 88, score: 0.9, type: LOCATION, start: 89, end: 98, score: 0.85, type: ALTER, start: 107, end: 109, score: 0.8, type: ALTER, start: 48, end: 50, score: 0.6000000000000001, type: PLZ, start: 32, end: 37, score: 0.5]
PII   ###These are from a debug print command just following the "try:"-line in the ReplaceFunction
10409
PII
23330
Hallo. Ich wohne glücklich seit [Inkorrekter Input] Tagen und <ALTER> Jahren in meiner Heimatstadt in [Ort in Berlin] <LOCATION> und bin <ALTER> Jahre alt.

**To Reproduce**
I hope the error can be reproduced with the supplied code.

**Expected behavior**
I expect the PII strings to not be in my output.

**Additional context**

**Comment by omri374** [comment]
Hi,
In this line:
```py
operators = {"PLZ": OperatorConfig("custom", {"lambda": ErsetzPLZmitBundesland()})}
```
You are passing the new operator as a lambda, instead of an operator. Please try adapting to this and see if it helps:
```py
operators={"PLZ": OperatorConfig("ErsetzPLZmitBundesland",{})}
```

**Comment by mroxdf** [comment]
Thank you very much. I used the lambda bc i got some new value error. 
Turns out i messed up my brackets. 


The intent is to resolve a zip code to a state. Since Berlin is a state itself i guess in this case its also resolving to a city xd.

**Comment by omri374** [comment]
Closing the issue, feel free to reopen if needed.
