### ISSUE TITLE
Documentation request: Sink and Scanner Service

### ISSUE THREAD

**Issue by teochenglim** [microsoft/presidio#158]
**Describe the bug**
Is the Sink Service and Scanner Service available. If so, can you create documentation to start? Thanks.

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by teochenglim** [comment]
From: https://github.com/microsoft/presidio/blob/master/docs/tutorial_scheduler.md

```bash
$ http --verify=no -f GET https://[ip]/api/v1/projects/test/schedule-scanner-cronjob
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 18
Content-Type: text/plain
Date: Wed, 15 May 2019 09:53:03 GMT
Server: nginx/1.15.10
Strict-Transport-Security: max-age=15724800; includeSubDomains

404 page not found

```

**Comment by omri374** [comment]
Hi @teochenglim,
Thanks for raising this issue. We will look into it and provide resolution within the upcoming weeks.

**Comment by omri374** [comment]
See https://github.com/microsoft/presidio/blob/master/CONTRIBUTING.md#adding-new-connectors

**Comment by teochenglim** [comment]
Many thanks! =)
