### ISSUE TITLE
Database scanner module - Analyze and anonymize sensitive content that exists within database tables

### ISSUE THREAD

**Issue by torosent** [Microsoft/presidio#17]
This module can scan various RDBMS databases such as MSSQL, MySQL and PostgreSQL

Features:

Create a Kubernetes Job definition. Optional Cron Job

Scan database records specific tables.

Analyze each cell content.

Optional - Anonymize text.

Save results in a DB or DW for further analysis and reports.

The module needs to support:

- ODBC connections
- Multiple tables
- Pause/resume actions.

**Comment by omri374** [comment]
Moving to internal backlog
