### ISSUE TITLE
Build takes a lot of time and eventually crashes

### ISSUE THREAD

**Issue by rahulraina7** [microsoft/presidio#183]
**Describe the bug**
Following the instructions to build docker images. My build process is stuck at `pipenv sync` and eventually crashes

**To Reproduce**
1. RUN ` make DOCKER_REGISTRY=${DOCKER_REGISTRY} PRESIDIO_LABEL=${PRESIDIO_LABEL} docker-build-deps`

Fails while pipenv sync. Below is the log:

```

Step 10/12 : RUN pipenv sync
 ---> Running in a0dbab69a607
Creating a virtualenv for this project…
Pipfile: /usr/bin/presidio-analyzer/Pipfile
Using /usr/local/bin/python (3.7.1) to create virtualenv…
⠼ Creating virtual environment...Already using interpreter /usr/local/bin/python
Using base prefix '/usr/local'
New python executable in /root/.local/share/virtualenvs/presidio-analyzer-p_bm8iFt/bin/python
Installing setuptools, pip, wheel...
done.

✔ Successfully created virtual environment!
Virtualenv location: /root/.local/share/virtualenvs/presidio-analyzer-p_bm8iFt
Installing dependencies from Pipfile.lock (6725d2)…
The command '/bin/sh -c pipenv sync' returned a non-zero code: 137
make: *** [docker-build-deps] Error 137

```
This is after about 2 hours.

**Expected behavior**
Build successfully completes. 

**Additional context**
I have a pretty fast internet connection, and I know pipenv can be slow. But I didn't expect it to fail.
Looking at: [durations](https://dev.azure.com/csedevil/Presidio/_build?definitionId=128&view=ms.vss-pipelineanalytics-web.new-build-definition-pipeline-analytics-view-cardmetrics)
I see the builds are actually very slow ~80 mins

What can I do to fasten this or even the build to succeed.

**Comment by omri374** [comment]
Hi @rahulraina7, Thanks for your feedback. We're looking into your feedback and making builds faster in general, and will keep you updated.

**Comment by omri374** [comment]
@rahulraina7 Which environment are you trying to build Presidio on?

**Comment by eladiw** [comment]
Hi @rahulraina7
Thanks for your feedback. exit code 137 is Out of memory.
Try to allocate more memory and try again

Regarding the build time, we will try to improve this in the near future.

**Comment by omri374** [comment]
Reopening as we are looking into providing a simpler installation experience either by decreasing build time or by leveraging prebuilt images.

**Comment by Guppster** [comment]
Please consider adding a note about the build time on the installation page. 
I gave up after 30 minutes at the `pipenv sync` step before reading this issue

**Comment by omri374** [comment]
Thanks @Guppster. We're working on improving our build time.

**Comment by omri374** [comment]
Some thoughts on long build times:
1. Pipenv takes a lot of time. We should do some research on whether there's an option of making Pipenv run faster. 
2. Evaluate other alternatives such as [poetry](https://github.com/sdispater/poetry)
3. Provide pre built images for dependencies (python and go) as these take the longest to build, and most users don't need to rebuild them.

**Comment by omri374** [comment]
#252
