### ISSUE TITLE
While running analyser engine,  the program will crash.

### ISSUE THREAD

**Issue by Huang-YiYi** [microsoft/presidio#186]
**Describe the bug**
https://github.com/microsoft/presidio/blob/master/docs/tutorial_analyzer.md

Tested on the analyzer python code below, but the program crashed and came out with a few errors.

<img width="914" alt="Screenshot 2019-06-14 at 3 54 51 PM" src="https://user-images.githubusercontent.com/50318926/59493004-cc0e5d00-8ebc-11e9-9614-e4b3d7bff86a.png">

These are the errors.

![error2](https://user-images.githubusercontent.com/50318926/59493499-8d2cd700-8ebd-11e9-98e4-6127c92810b1.png)

![59493230-43dc8780-8ebd-11e9-980b-9e2f146dd5e9](https://user-images.githubusercontent.com/50318926/59816049-2c821c00-934d-11e9-8567-1c0e8d673330.png)

**Comment by omri374** [comment]
Hi,
Thanks for letting us know. We'll look into it and return an answer. 

Omri

**Comment by omri374** [comment]
Hi @Huang-YiYi,
Could you please provide some more information about the way you ran this?
Did you clone the repo and run this test? Have you installed it using pipenv? Are the unit tests passing?

**Comment by Huang-YiYi** [comment]
Hi,

Q. Could you please provide some more information about the way you ran this?
We attached a screenshot of the steps of how we run it and sample python code.

Steps of running Presidio
![Screenshot from 2019-06-18 14-27-34](https://user-images.githubusercontent.com/50318926/59658952-a85a5800-91d7-11e9-869e-90058036ebc7.png)

Sample Python code
![Screenshot from 2019-06-18 14-36-04](https://user-images.githubusercontent.com/50318926/59659045-de97d780-91d7-11e9-8d3f-080ecc39e5fb.png)


Q.Did you clone the repo and run this test? 
Yes, we clone it.

Q.Have you installed it using pipenv? 
Run Pipenv in the pip files in Presidio-Analzyer. So the Presidio-Analzer is the virtual environment. 
Installed all the pip packages. 

Q.Are the unit tests passing? 
We did not reach the stage to test the unit yet.

Additionally, we attached a document of the steps of how we installed Presidio. Hope it will help.

[Presidio Installation Guide.docx](https://github.com/microsoft/presidio/files/3300128/Presidio.Installation.Guide.docx)

YiYi

**Comment by Huang-YiYi** [comment]
Hi,

We had managed to solve the problem on our side. 

Thanks for your help.

YiYi.

**Comment by Huang-YiYi** [comment]
Hi,

I had redone everything, followed the steps again and it works. 

Thank you.

YiYi.
