### ISSUE TITLE
How is it different from NER?

### ISSUE THREAD

**Issue by SandeepBhutani** [microsoft/presidio#203]
This is not a bug but a question. The solution looks promising. But wondering how is this different from an NER system (or LUIS entity recognition) ? I can see this spacy NER being used. Is it an extension to NER system, exposed as a service or there is some other intelligence added to the system.

**Comment by omri374** [comment]
This is an entire solution for PII anonymization, not just a model. You can deploy it to your production environment without additional operationalization needed.

We do use Spacy NER, but only for certain PII entities. NER is not the right tool for some entities, like credit card numbers (that require checksum) and others. Presidio lets you implement your own recognizers using NER, regex, black-list and most, or use the predefined recognizers already implemented.

**Comment by SandeepBhutani** [comment]
Thanks
