### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by afolarin** [microsoft/presidio#210]
**Describe the bug**

**To Reproduce**
https://presidio-demo.westeurope.cloudapp.azure.com/  not working on demo text (tested on Chrome, Safari, Firefox)

**Expected behavior**
Should replace example PII

**Comment by omri374** [comment]
Hi afolarin, thanks for your feedback. We are working on fixing it ASAP.

**Comment by SandeepBhutani** [comment]
Still not fixed?

**Comment by omri374** [comment]
Fixed on a different URL: https://presidio-demo-dev.azurewebsites.net/
We'll have the URL restored today.

**Comment by omri374** [comment]
Hi, the demo is fixed but with a different URL: https://presidio-demo-dev.azurewebsites.net/
We'll have the URL updated soon.
