### ISSUE TITLE
How to install on simple unix box

### ISSUE THREAD

**Issue by ghost** [microsoft/presidio#219]
Hi,
This is a question. As per installation instructions it can be installed with either docker or with helm (reddis etc).      
Can't we simply install presido on windows or unix box like pip or git clone?

**Comment by omri374** [comment]
Hi @SandeepBhutani, 

We are currently working on allowing users to pip install the presidio-analyzer module. In the meantime, you can create a wheel package from the analyzer code using this documentation (on the development branch): 

https://github.com/microsoft/presidio/blob/development/docs/install.md#install-presidio-analyzer-as-a-python-package

**Comment by bballamudi** [comment]
@omri374 

I followed the instructions to installing the wheel package from the analyzer code and it is functioning just fine. However, the time to load this package is prohibitively long. Do you suspect something wrong in my installation of the setup?

**Comment by omri374** [comment]
Hi @bballamudi, could you please provide more details? We haven't encountered such issue. The only thing that might take some time is the loading (or downloading if missing) of the en_core_web_lg Spacy model.
