### ISSUE TITLE
404 on "Try Presidio on your own data" link in readme.md

### ISSUE THREAD

**Issue by Zambonilli** [microsoft/presidio#224]
**Describe the bug**
The link to the demo website in the readme.md returns a 404. The link's URL is https://presidio-demo.azurewebsites.net/

**To Reproduce**
1. Go to readme.md in a browser
2. Click on 'Try Presidio on your own data"
3. See 404

**Expected behavior**
A HTTP 200

**Comment by omri374** [comment]
Hi @Zambonilli, thanks for raising this issue. The demo website is now fixed.
