### ISSUE TITLE
fieldTypes API should returns all fields, including custom ones

### ISSUE THREAD

**Issue by omri374** [microsoft/presidio#235]
**Describe the bug**
Currently a call to the fieldTypes API returns the list of fields defined in the proto file. Since Presidio allows to extend this list by adding custom recognizers and field types, this API should return all field types (entity types) supported by a Presidio deployment

**To Reproduce**
1. Create a new entity recognizer using the API
2. Call the fieldTypes API (e.g. https://presidio-api.westeurope.cloudapp.azure.com/api/v1/fieldTypes)
3. The newly added field type supported by the new recognizer is not in this list.

**Expected behavior**
New types supported by custom recognizers should be added to the list

**Comment by LaraSchvartzman** [comment]
While using a Presidio Instance I found online, I get the same problem when trying to get all field types. I'm currently working with my own Presidio Instance installed via Docker with minimum requirements.
On the other hand, by following the guide for creation and usage of custom fields (https://microsoft.github.io/presidio/custom_fields.html where the example creates a rocket recognizer) my instance is unable to recognize the new field, i.e. I request the analysis of the text "Jane Doe is looking at a projectile. John Smith has a rocket science major." and the software only recognizes two PERSON entities, where it should also recognize two custom ROCKET entitites.
How did you manage to succesfully create custom recognizers? Did you install your Presidio with any given specification? Thanks!

**Comment by omri374** [comment]
Hi @LaraSchvartzman 
Please see #239 
In order to have custom recognizers added via API (as opposed to adding them as code when deploying presidio), you need the full deployment on Kubernetes with Redis. We use Redis to store all the new API based recognizers in a persistent way.
So there are two options:
1. Add your new recognizer as code (there are some examples on the documentation, kindly let us know if you need more information)
2. Perform a full deployment of Presidio including Redis.

**Comment by LaraSchvartzman** [comment]
Hi @omri374, thank you so much for your help. I just consulted with my team and they told me we followed the first installation from the guide: https://github.com/microsoft/presidio/blob/master/docs/install.md
which uses Docker but still includes Redis.
We are now planning on trying the second version of the installation (installing it as a service), but is this necessary? Could the problem be solved once we do this?

**Comment by omri374** [comment]
Hi Lara, 
Installing it using docker would not have Redis included and therefore we would not have a persistent cache for custom recognizers. Installing it as a service with helm would solve this problem.
Another option to consider is to add these recognizers via code and not via API. You could look at some examples of predefined recognizers if you need a reference. For example: https://github.com/microsoft/presidio/blob/master/presidio-analyzer/analyzer/predefined_recognizers/us_itin_recognizer.py

**Comment by LaraSchvartzman** [comment]
Hi @omri374 , we reinstalled it as a service and it worked! Thank you for all the help

**Comment by omri374** [comment]
Great!
