### ISSUE TITLE
Custom recognizers won't work

### ISSUE THREAD

**Issue by apresmoi** [microsoft/presidio#239]
Hello.

For some reason custom recognizers don't work on my current presidio instance.

I'm following the documentation:

I post into `api/v1/analyzer/recognizers/spaceship`
`
{
	"value": {
		"entity": "SPACESHIP",
		"language": "en", 
		"patterns": [
			{
				"name": "spaceship regex",
				"regex": "\\W*(spaceship)\\W*",
				"score": 0.9
			}
		]
	}
}
`

And then I try to run the analyzer posting into `/api/v1/projects/testing/analyze` in two ways:
`
{
	"text":"They went inside the spaceship", 
	"analyzeTemplate": {
		"allFields": true
	}
}
`
Response:
`
"No results"
`

`
{
	"text":"They went inside the spaceship", 
	"analyzeTemplate": {
		"fields": [
			{ "name": "SPACESHIP" }
                ]
	}
}
`
Response
`
"rpc error: code = Unknown desc = Exception calling application: No matching recognizers were found to serve the request."
`

Any thoughts ?

Regards.

**Comment by omri374** [comment]
Hello @apresmoi, could you please provide some more details on your deployment? Custom recognizers by API require a Kubernetes deployment with Redis (deployed together with Presidio)

cc @eladiw

**Comment by omri374** [comment]
Closing as more info from the issue opener was not received.

**Comment by navalev** [comment]
I assume the services were deployed using the build.sh script. The services in the script were not configured properly and the analyzer did not communicate with the recognizers store.
PR #260 is fixing the build script and all tests cases manined in this issue pass.

**Comment by kevin-yauris** [comment]
> I assume the services were deployed using the build.sh script. The services in the script were not configured properly and the analyzer did not communicate with the recognizers store.
> PR #260 is fixing the build script and all tests cases manined in this issue pass.

hi @navalev and @omri374, is this mean custom recognizers by API can be done with deployment using docker on local? 
I tried to run `echo -n '{"value": {"entity": "ROCKET","language": "en", "patterns": [{"name": "rocket-regex","regex": "\\W*(rocket)\\W*","score": 1}]}}' | http -f POST http://0.0.0.0:8080/api/v1/analyzer/recognizers/rocket`
but the response is 
```
HTTP/1.1 500 Internal Server Error
Content-Length: 0
```

I also try to get all recognizers enable using 
`http http://0.0.0.0:8080/api/v1/analyzer/recognizers` responded with 
```
HTTP/1.1 301 Moved Permanently
Content-Length: 64
Content-Type: text/html; charset=utf-8
Date: Mon, 05 Oct 2020 02:41:52 GMT
Location: /api/v1/analyzer/recognizers/

<a href="/api/v1/analyzer/recognizers/">Moved Permanently</a>.
```
Tried with ` http http://0.0.0.0:8080/api/v1/analyzer/recognizers/` but got null instead of the list of recognizers
```
HTTP/1.1 200 OK
Content-Length: 4
Content-Type: application/json; charset=utf-8
Date: Mon, 05 Oct 2020 04:15:38 GMT

null
```

**Comment by zoubinirani** [comment]
I'm also getting the same responses as @kevin-yauris when submitting the same requests. Furthermore, when sending text to analyzer, I'm getting the same errors/responses as @apresmoi. 

Steps to recreate:
- Set up AWS EC2 Ubuntu 18.04 instance and SSH in
- Prepare the development environment similar to steps here: https://medium.com/@mileshill_40155/install-microsoft-presidio-on-ubuntu-18-04-3b83f67e6bb0
- Try sending http requests to analyzer via API container (which looks like it defaults to port `8080`). e.g. `echo -n '{"text":"John Smith lives in New York. We met yesterday morning in Seattle. I called him before on (212) 555-1234 to verify the appointment. He also told me that his drivers license is AC111921", "analyzeTemplate":{"fields":[]}  }' | http -F --verify=no  http://0.0.0.0:8080/api/v1/projects/1/analyze`
 
Any help would be appreciated.

**Comment by zoubinirani** [comment]
@kevin-yauris check out https://github.com/microsoft/presidio/issues/381 and see if this solves your problem.
