### ISSUE TITLE
Standalone Analyzer On Spark

### ISSUE THREAD

**Issue by shayan90** [microsoft/presidio#242]
Hi, 

Have you guys tried to run the analyzer as a spark job ? how would suggest handle loading the spacy model for each worker and also how to handle serialization?

would appreciate some suggestions around this, is there any plan to support this use case ?

 Thanks

**Comment by omri374** [comment]
Hi,
We haven't experienced with this, and I don't think Spacy can run on top of spark (although we haven't tested this).
Is deploying Presidio on K8S and calling it from a Spark pipeline an option?

**Comment by CodeRunRepeat** [comment]
@shayan90 , were you able to consider @omri374 's suggestion?

**Comment by omri374** [comment]
Closing for now. Feel free to reopen if you have additional questions/issues
