### ISSUE TITLE
Can it be used in ETL flow

### ISSUE THREAD

**Issue by SatyaBhagat** [microsoft/presidio#244]
Hi,

We perform ETL operations to move data from blob storage into ADLS datalake and SQL Servers.
Can this software be used as a potential transformation tool in the ETL load process to identify and hash the PII data?

I followed the analyzer document and it gave some good results on when passed a text file in a standalone python executor. Do you have any documentation on how to start working with anonymizer and scanning pictures?

Thank You

**Comment by omri374** [comment]
Hi SatyaBhagat. We're actually working on documentation. See #245

**Comment by SatyaBhagat** [comment]
Hi @omri374 ,

Can we expect some information regarding the Cron scheduled job output and handling zip files with presidio in the documentation?

**Comment by omri374** [comment]
I can't refer to zip files specifically, but the new documentation PR provides references to examples and methods for adding new sources and targets.

**Comment by SatyaBhagat** [comment]
Hi @omri374,

Thank you for the quick response.
1. What would be the size of Redis and what happens to the scanning process
if the Redis is  down?
2. How do we track already scanned files in the previous runs, how to
recognize the modified files from the last run to scan again?
3. What would be the approximate time to scan 100 TB of data?
4. Can we scan scan a datalake folder if we provide the endpoints to the
presidio-api?

It would be very helpful, if you can help us with these questions.

Regards,
Satya
satyabhagat.pichikala@7-11.com
7-Eleven, Inc.

**Comment by omri374** [comment]
Hi @SatyaBhagat ,
I will get back to you ASAP with answers. Sorry for the delay

**Comment by omri374** [comment]
Hi @SatyaBhagat,
1. The redis cache is used for storing templates, recognizers added using the API and the such. Therefore it is lightweight and doesn't require special compute or storage requirements.
2. We currently don't support tracking previously scanned documents. We've added this to our backlog and we'll prioritize it.
3. We don't have specific performance tests on such dataset. Here are some results from a benchmarks performed on a K8S cluster with a single pod. Hope this could be used to derive the expected duration of a 100TB task.

### Azure DV3 VM size (2.4 GHz Intel Xeon® E5-2673 v3)

- Response times (95 percentile) of 10 words is between 35ms and 59ms.
- Response times (95 percentile) of 100 words is between 54ms and 80ms.
- Response times (95 percentile) of 1000 words is between 150ms and 270ms.

### Azure F2 VM size (3.4 GHz Intel® Xeon® Platinum 8168)
- Response times (95 percentile) of 10 words is between 12ms and 14ms.s
- Response times (95 percentile) of 100 words is between 22ms and 25ms.
- Response times (95 percentile) of 1000 words is between 117ms and 200ms.

4. A connection to Azure DataLake is currently WIP. We don't have an official connection yet.
