### ISSUE TITLE
Make error during installation using docker

### ISSUE THREAD

**Issue by SatyaBhagat** [microsoft/presidio#247]
During the installation with Docker, it is giving make error

make DOCKER_REGISTRY=${DOCKER_REGISTRY} PRESIDIO_LABEL=${PRESIDIO_LABEL} docker-build

make: *** [Makefile:181: go-test-style] Error 1
The command '/bin/sh -c make go-test' returned a non-zero code: 2
make: *** [docker-build-base] Error 2

It would be very helpful, if someone canhelp with the solution

Thank You

-----------------------------------------------
$ make DOCKER_REGISTRY=${DOCKER_REGISTRY} PRESIDIO_LABEL=${PRESIDIO_LABEL} docker-build
docker build --build-arg REGISTRY=presidio --build-arg PRESIDIO_DEPS_LABEL='latest'      -t presidio/presidio-golang-base -f Dockerfile.golang.base .
Sending build context to Docker daemon  1.261MB
Step 1/7 : ARG REGISTRY=presidio.azurecr.io
Step 2/7 : ARG PRESIDIO_DEPS_LABEL=latest
Step 3/7 : FROM ${REGISTRY}/presidio-golang-deps:${PRESIDIO_DEPS_LABEL}
 ---> b2929920eb09
Step 4/7 : WORKDIR $GOPATH/src/github.com/Microsoft/presidio
 ---> Using cache
 ---> 04324948e601
Step 5/7 : ADD . $GOPATH/src/github.com/Microsoft/presidio
 ---> Using cache
 ---> ecf194963a5e
Step 6/7 : RUN dep ensure
 ---> Using cache
 ---> 4d1681ebd2c6
Step 7/7 : RUN make go-test
 ---> Running in aa4cea2b1b88
gometalinter --config ./gometalinter.json ./...
pkg/cache/cache.go:1::warning: file is not gofmted with -s (gofmt)
pkg/cache/mock/cache.go:1::warning: file is not gofmted with -s (gofmt)
pkg/cache/redis/redis.go:1::warning: file is not gofmted with -s (gofmt)
pkg/logger/logger.go:1::warning: file is not gofmted with -s (gofmt)
pkg/logger/logger_test.go:1::warning: file is not gofmted with -s (gofmt)
pkg/platform/kube/client.go:1::warning: file is not gofmted with -s (gofmt)
pkg/platform/kube/cronjob.go:1::warning: file is not gofmted with -s (gofmt)
pkg/platform/kube/cronjob_test.go:1::warning: file is not gofmted with -s (gofmt)
pkg/platform/kube/job.go:1::warning: file is not gofmted with -s (gofmt)
pkg/platform/kube/job_test.go:1::warning: file is not gofmted with -s (gofmt)
pkg/platform/kube/kube.go:1::warning: file is not gofmted with -s (gofmt)
pkg/platform/kube/secret.go:1::warning: file is not gofmted with -s (gofmt)
pkg/platform/kube/secret_test.go:1::warning: file is not gofmted with -s (gofmt)
pkg/platform/local/job.go:1::warning: file is not gofmted with -s (gofmt)
pkg/platform/local/local.go:1::warning: file is not gofmted with -s (gofmt)
pkg/platform/local/secret.go:1::warning: file is not gofmted with -s (gofmt)
pkg/platform/local/secret_test.go:1::warning: file is not gofmted with -s (gofmt)
pkg/platform/platform.go:1::warning: file is not gofmted with -s (gofmt)
pkg/presidio/presidio.go:1::warning: file is not gofmted with -s (gofmt)
pkg/presidio/services/services.go:1::warning: file is not gofmted with -s (gofmt)
pkg/presidio/templates/templates.go:1::warning: file is not gofmted with -s (gofmt)
pkg/presidio/templates/templates_test.go:1::warning: file is not gofmted with -s (gofmt)
pkg/queue/queue.go:1::warning: file is not gofmted with -s (gofmt)
pkg/queue/rabbitmq/rabbitmq.go:1::warning: file is not gofmted with -s (gofmt)
pkg/queue/rabbitmq/rabbitmq_test.go:1::warning: file is not gofmted with -s (gofmt)
pkg/rpc/client.go:1::warning: file is not gofmted with -s (gofmt)
pkg/rpc/server.go:1::warning: file is not gofmted with -s (gofmt)
pkg/server/server.go:1::warning: file is not gofmted with -s (gofmt)
pkg/storage/storage.go:1::warning: file is not gofmted with -s (gofmt)
pkg/stream/eventhubs/eventhubs.go:1::warning: file is not gofmted with -s (gofmt)
pkg/stream/kafka/kafka.go:1::warning: file is not gofmted with -s (gofmt)
pkg/stream/mock/mock.go:1::warning: file is not gofmted with -s (gofmt)
pkg/stream/mock/mock_test.go:1::warning: file is not gofmted with -s (gofmt)
pkg/stream/stream.go:1::warning: file is not gofmted with -s (gofmt)
pkg/version/version.go:1::warning: file is not gofmted with -s (gofmt)
presidio-anonymizer-image/cmd/presidio-anonymizer-image/anonymizer/anonymizer.go:1::warning: file is not gofmted with -s (gofmt)
presidio-anonymizer-image/cmd/presidio-anonymizer-image/main.go:1::warning: file is not gofmted with -s (gofmt)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/anonymizer.go:1::warning: file is not gofmted with -s (gofmt)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/anonymizer_test.go:1::warning: file is not gofmted with -s (gofmt)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/common.go:1::warning: file is not gofmted with -s (gofmt)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/fpe_config.go:1::warning: file is not gofmted with -s (gofmt)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/fpe_config_test.go:1::warning: file is not gofmted with -s (gofmt)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/hash_config.go:1::warning: file is not gofmted with -s (gofmt)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/hash_config_test.go:1::warning: file is not gofmted with -s (gofmt)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/mask_config.go:1::warning: file is not gofmted with -s (gofmt)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/mask_config_test.go:1::warning: file is not gofmted with -s (gofmt)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/redact_config.go:1::warning: file is not gofmted with -s (gofmt)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/replace_config.go:1::warning: file is not gofmted with -s (gofmt)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/replace_config_test.go:1::warning: file is not gofmted with -s (gofmt)
presidio-anonymizer/cmd/presidio-anonymizer/main.go:1::warning: file is not gofmted with -s (gofmt)
presidio-api/cmd/presidio-api/api/analyze/analyze.go:1::warning: file is not gofmted with -s (gofmt)
presidio-api/cmd/presidio-api/api/analyze/analyze_test.go:1::warning: file is not gofmted with -s (gofmt)
presidio-api/cmd/presidio-api/api/anonymize-image/anonymize-image.go:1::warning: file is not gofmted with -s (gofmt)
presidio-api/cmd/presidio-api/api/anonymize-image/anonymize-image_test.go:1::warning: file is not gofmted with -s (gofmt)
presidio-api/cmd/presidio-api/api/anonymize/anonymize.go:1::warning: file is not gofmted with -s (gofmt)
presidio-api/cmd/presidio-api/api/anonymize/anonymize_test.go:1::warning: file is not gofmted with -s (gofmt)
presidio-api/cmd/presidio-api/api/api.go:1::warning: file is not gofmted with -s (gofmt)
presidio-api/cmd/presidio-api/api/mocks/mocks.go:1::warning: file is not gofmted with -s (gofmt)
presidio-api/cmd/presidio-api/api/recognizers/recognizers.go:1::warning: file is not gofmted with -s (gofmt)
presidio-api/cmd/presidio-api/api/recognizers/recognizers_test.go:1::warning: file is not gofmted with -s (gofmt)
presidio-api/cmd/presidio-api/api/scanner-cron-job/scanner-cron-job.go:1::warning: file is not gofmted with -s (gofmt)
presidio-api/cmd/presidio-api/api/stream-job/stream-job.go:1::warning: file is not gofmted with -s (gofmt)
presidio-api/cmd/presidio-api/api/templates/templates.go:1::warning: file is not gofmted with -s (gofmt)
presidio-api/cmd/presidio-api/main.go:1::warning: file is not gofmted with -s (gofmt)
presidio-api/cmd/presidio-api/methods.go:1::warning: file is not gofmted with -s (gofmt)
presidio-collector/cmd/presidio-collector/main.go:1::warning: file is not gofmted with -s (gofmt)
presidio-collector/cmd/presidio-collector/processor/processor.go:1::warning: file is not gofmted with -s (gofmt)
presidio-collector/cmd/presidio-collector/scanner/factory.go:1::warning: file is not gofmted with -s (gofmt)
presidio-collector/cmd/presidio-collector/scanner/scanner.go:1::warning: file is not gofmted with -s (gofmt)
presidio-collector/cmd/presidio-collector/scanner/storage-item.go:1::warning: file is not gofmted with -s (gofmt)
presidio-collector/cmd/presidio-collector/scanner/storage-scanner.go:1::warning: file is not gofmted with -s (gofmt)
presidio-collector/cmd/presidio-collector/streams/streams.go:1::warning: file is not gofmted with -s (gofmt)
presidio-datasink/cmd/presidio-datasink/cloudstorage/cloudstorage.go:1::warning: file is not gofmted with -s (gofmt)
presidio-datasink/cmd/presidio-datasink/cloudstorage/cloudstorage_test.go:1::warning: file is not gofmted with -s (gofmt)
presidio-datasink/cmd/presidio-datasink/database/database.go:1::warning: file is not gofmted with -s (gofmt)
presidio-datasink/cmd/presidio-datasink/database/database_test.go:1::warning: file is not gofmted with -s (gofmt)
presidio-datasink/cmd/presidio-datasink/datasink-factory.go:1::warning: file is not gofmted with -s (gofmt)
presidio-datasink/cmd/presidio-datasink/datasink/datasink.go:1::warning: file is not gofmted with -s (gofmt)
presidio-datasink/cmd/presidio-datasink/main.go:1::warning: file is not gofmted with -s (gofmt)
presidio-datasink/cmd/presidio-datasink/main_test.go:1::warning: file is not gofmted with -s (gofmt)
presidio-datasink/cmd/presidio-datasink/stream/stream.go:1::warning: file is not gofmted with -s (gofmt)
presidio-datasink/cmd/presidio-datasink/stream/stream_test.go:1::warning: file is not gofmted with -s (gofmt)
presidio-ocr/cmd/presidio-ocr/main.go:1::warning: file is not gofmted with -s (gofmt)
presidio-ocr/cmd/presidio-ocr/ocr/ocr.go:1::warning: file is not gofmted with -s (gofmt)
presidio-recognizers-store/cmd/presidio-recognizers-store/main.go:1::warning: file is not gofmted with -s (gofmt)
presidio-recognizers-store/cmd/presidio-recognizers-store/recognizers_store_test.go:1::warning: file is not gofmted with -s (gofmt)
presidio-scheduler/cmd/presidio-scheduler/main.go:1::warning: file is not gofmted with -s (gofmt)
presidio-scheduler/cmd/presidio-scheduler/scheduler_test.go:1::warning: file is not gofmted with -s (gofmt)
presidio-tester/cmd/presidio-tester/tester.go:1::warning: file is not gofmted with -s (gofmt)
tests/common/common.go:1::warning: file is not gofmted with -s (gofmt)
tests/functional_http_test.go:1::warning: file is not gofmted with -s (gofmt)
tests/functional_recognizers_test.go:1::warning: file is not gofmted with -s (gofmt)
tests/functional_storage_scanner_test.go:1::warning: file is not gofmted with -s (gofmt)
tests/integration_anonymize_image_test.go:1::warning: file is not gofmted with -s (gofmt)
tests/integration_eventhub_test.go:1::warning: file is not gofmted with -s (gofmt)
tests/integration_kafka_test.go:1::warning: file is not gofmted with -s (gofmt)
tests/integration_redis_test.go:1::warning: file is not gofmted with -s (gofmt)
tests/integration_tesseract_test.go:1::warning: file is not gofmted with -s (gofmt)
pkg/cache/cache.go:1::warning: file is not goimported (goimports)
pkg/cache/mock/cache.go:1::warning: file is not goimported (goimports)
pkg/cache/redis/redis.go:1::warning: file is not goimported (goimports)
pkg/logger/logger.go:1::warning: file is not goimported (goimports)
pkg/logger/logger_test.go:1::warning: file is not goimported (goimports)
pkg/platform/kube/client.go:1::warning: file is not goimported (goimports)
pkg/platform/kube/cronjob.go:1::warning: file is not goimported (goimports)
pkg/platform/kube/cronjob_test.go:1::warning: file is not goimported (goimports)
pkg/platform/kube/job.go:1::warning: file is not goimported (goimports)
pkg/platform/kube/job_test.go:1::warning: file is not goimported (goimports)
pkg/platform/kube/kube.go:1::warning: file is not goimported (goimports)
pkg/platform/kube/secret.go:1::warning: file is not goimported (goimports)
pkg/platform/kube/secret_test.go:1::warning: file is not goimported (goimports)
pkg/platform/local/job.go:1::warning: file is not goimported (goimports)
pkg/platform/local/local.go:1::warning: file is not goimported (goimports)
pkg/platform/local/secret.go:1::warning: file is not goimported (goimports)
pkg/platform/local/secret_test.go:1::warning: file is not goimported (goimports)
pkg/platform/platform.go:1::warning: file is not goimported (goimports)
pkg/presidio/presidio.go:1::warning: file is not goimported (goimports)
pkg/presidio/services/services.go:1::warning: file is not goimported (goimports)
pkg/presidio/templates/templates.go:1::warning: file is not goimported (goimports)
pkg/presidio/templates/templates_test.go:1::warning: file is not goimported (goimports)
pkg/queue/queue.go:1::warning: file is not goimported (goimports)
pkg/queue/rabbitmq/rabbitmq.go:1::warning: file is not goimported (goimports)
pkg/queue/rabbitmq/rabbitmq_test.go:1::warning: file is not goimported (goimports)
pkg/rpc/client.go:1::warning: file is not goimported (goimports)
pkg/rpc/server.go:1::warning: file is not goimported (goimports)
pkg/server/server.go:1::warning: file is not goimported (goimports)
pkg/storage/storage.go:1::warning: file is not goimported (goimports)
pkg/stream/eventhubs/eventhubs.go:1::warning: file is not goimported (goimports)
pkg/stream/kafka/kafka.go:1::warning: file is not goimported (goimports)
pkg/stream/mock/mock.go:1::warning: file is not goimported (goimports)
pkg/stream/mock/mock_test.go:1::warning: file is not goimported (goimports)
pkg/stream/stream.go:1::warning: file is not goimported (goimports)
pkg/version/version.go:1::warning: file is not goimported (goimports)
presidio-anonymizer-image/cmd/presidio-anonymizer-image/anonymizer/anonymizer.go:1::warning: file is not goimported (goimports)
presidio-anonymizer-image/cmd/presidio-anonymizer-image/main.go:1::warning: file is not goimported (goimports)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/anonymizer.go:1::warning: file is not goimported (goimports)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/anonymizer_test.go:1::warning: file is not goimported (goimports)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/common.go:1::warning: file is not goimported (goimports)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/fpe_config.go:1::warning: file is not goimported (goimports)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/fpe_config_test.go:1::warning: file is not goimported (goimports)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/hash_config.go:1::warning: file is not goimported (goimports)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/hash_config_test.go:1::warning: file is not goimported (goimports)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/mask_config.go:1::warning: file is not goimported (goimports)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/mask_config_test.go:1::warning: file is not goimported (goimports)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/redact_config.go:1::warning: file is not goimported (goimports)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/replace_config.go:1::warning: file is not goimported (goimports)
presidio-anonymizer/cmd/presidio-anonymizer/anonymizer/transformations/replace_config_test.go:1::warning: file is not goimported (goimports)
presidio-anonymizer/cmd/presidio-anonymizer/main.go:1::warning: file is not goimported (goimports)
presidio-api/cmd/presidio-api/api/analyze/analyze.go:1::warning: file is not goimported (goimports)
presidio-api/cmd/presidio-api/api/analyze/analyze_test.go:1::warning: file is not goimported (goimports)
presidio-api/cmd/presidio-api/api/anonymize-image/anonymize-image.go:1::warning: file is not goimported (goimports)
presidio-api/cmd/presidio-api/api/anonymize-image/anonymize-image_test.go:1::warning: file is not goimported (goimports)
presidio-api/cmd/presidio-api/api/anonymize/anonymize.go:1::warning: file is not goimported (goimports)
presidio-api/cmd/presidio-api/api/anonymize/anonymize_test.go:1::warning: file is not goimported (goimports)
presidio-api/cmd/presidio-api/api/api.go:1::warning: file is not goimported (goimports)
presidio-api/cmd/presidio-api/api/mocks/mocks.go:1::warning: file is not goimported (goimports)
presidio-api/cmd/presidio-api/api/recognizers/recognizers.go:1::warning: file is not goimported (goimports)
presidio-api/cmd/presidio-api/api/recognizers/recognizers_test.go:1::warning: file is not goimported (goimports)
presidio-api/cmd/presidio-api/api/scanner-cron-job/scanner-cron-job.go:1::warning: file is not goimported (goimports)
presidio-api/cmd/presidio-api/api/stream-job/stream-job.go:1::warning: file is not goimported (goimports)
presidio-api/cmd/presidio-api/api/templates/templates.go:1::warning: file is not goimported (goimports)
presidio-api/cmd/presidio-api/main.go:1::warning: file is not goimported (goimports)
presidio-api/cmd/presidio-api/methods.go:1::warning: file is not goimported (goimports)
presidio-collector/cmd/presidio-collector/main.go:1::warning: file is not goimported (goimports)
presidio-collector/cmd/presidio-collector/processor/processor.go:1::warning: file is not goimported (goimports)
presidio-collector/cmd/presidio-collector/scanner/factory.go:1::warning: file is not goimported (goimports)
presidio-collector/cmd/presidio-collector/scanner/scanner.go:1::warning: file is not goimported (goimports)
presidio-collector/cmd/presidio-collector/scanner/storage-item.go:1::warning: file is not goimported (goimports)
presidio-collector/cmd/presidio-collector/scanner/storage-scanner.go:1::warning: file is not goimported (goimports)
presidio-collector/cmd/presidio-collector/streams/streams.go:1::warning: file is not goimported (goimports)
presidio-datasink/cmd/presidio-datasink/cloudstorage/cloudstorage.go:1::warning: file is not goimported (goimports)
presidio-datasink/cmd/presidio-datasink/cloudstorage/cloudstorage_test.go:1::warning: file is not goimported (goimports)
presidio-datasink/cmd/presidio-datasink/database/database.go:1::warning: file is not goimported (goimports)
presidio-datasink/cmd/presidio-datasink/database/database_test.go:1::warning: file is not goimported (goimports)
presidio-datasink/cmd/presidio-datasink/datasink-factory.go:1::warning: file is not goimported (goimports)
presidio-datasink/cmd/presidio-datasink/datasink/datasink.go:1::warning: file is not goimported (goimports)
presidio-datasink/cmd/presidio-datasink/main.go:1::warning: file is not goimported (goimports)
presidio-datasink/cmd/presidio-datasink/main_test.go:1::warning: file is not goimported (goimports)
presidio-datasink/cmd/presidio-datasink/stream/stream.go:1::warning: file is not goimported (goimports)
presidio-datasink/cmd/presidio-datasink/stream/stream_test.go:1::warning: file is not goimported (goimports)
presidio-ocr/cmd/presidio-ocr/main.go:1::warning: file is not goimported (goimports)
presidio-ocr/cmd/presidio-ocr/ocr/ocr.go:1::warning: file is not goimported (goimports)
presidio-recognizers-store/cmd/presidio-recognizers-store/main.go:1::warning: file is not goimported (goimports)
presidio-recognizers-store/cmd/presidio-recognizers-store/recognizers_store_test.go:1::warning: file is not goimported (goimports)
presidio-scheduler/cmd/presidio-scheduler/main.go:1::warning: file is not goimported (goimports)
presidio-scheduler/cmd/presidio-scheduler/scheduler_test.go:1::warning: file is not goimported (goimports)
presidio-tester/cmd/presidio-tester/tester.go:1::warning: file is not goimported (goimports)
tests/common/common.go:1::warning: file is not goimported (goimports)
tests/functional_http_test.go:1::warning: file is not goimported (goimports)
tests/functional_recognizers_test.go:1::warning: file is not goimported (goimports)
tests/functional_storage_scanner_test.go:1::warning: file is not goimported (goimports)
tests/integration_anonymize_image_test.go:1::warning: file is not goimported (goimports)
tests/integration_eventhub_test.go:1::warning: file is not goimported (goimports)
tests/integration_kafka_test.go:1::warning: file is not goimported (goimports)
tests/integration_redis_test.go:1::warning: file is not goimported (goimports)
tests/integration_tesseract_test.go:1::warning: file is not goimported (goimports)
make: *** [Makefile:181: go-test-style] Error 1
The command '/bin/sh -c make go-test' returned a non-zero code: 2
make: *** [docker-build-base] Error 2

**Comment by omri374** [comment]
Hey @SatyaBhagat. Do you mind sharing what was the case and how was it resolved?

**Comment by SatyaBhagat** [comment]
Hi Omri,

Sorry for the inconvenience.
I tried installation by cloning the master into a separate folder, it
worked.
I downloaded Presidio files from 2 sources, one is from (
https://github.com/microsoft/presidio) and I don't recall the other
source. The only difference I find between the two folders is git folder
naming convention.(.github and .git)
Please let me know if you need any other information.

Regards,
Satya

**Comment by omri374** [comment]
Thank you
