### ISSUE TITLE
word boundaries

### ISSUE THREAD

**Issue by Cherchercher** [microsoft/presidio#254]
I have a lot of customed PII that I want to add.
I am running into a lot of issue where numbers result in overlapping classification.

For example,
 1234567890 9844412312312323 at https://presidio-demo.azurewebsites.net results in <DATE_TIME>UMBER>.

I am very curious in learning about how this scenario occurs to best resolve the issue.

**Comment by omri374** [comment]
Hi @Cherchercher. Overlaps make sense as we are running multiple recognizers independently.

Some things to consider in this case:
1. Use a threshold to ignore identified PII with low score
2. Come up with a logic to handle these overlaps. For example, this code (on our research repo) handles overlaps in a naive way: 
https://github.com/microsoft/presidio-research/blob/65f4239cd41360b362252fbd0557231a23e52fc3/presidio_evaluator/span_to_tag.py#L60
It looks at each token's prediction score to come up with a non-overlapping representation. 
Perhaps the unit tests would give a better hunch on how this works : https://github.com/microsoft/presidio-research/blob/65f4239cd41360b362252fbd0557231a23e52fc3/tests/test_span_to_tag.py#L160
