### ISSUE TITLE
Using protocol buffers to add new parameters

### ISSUE THREAD

**Issue by LaraSchvartzman** [microsoft/presidio#255]
Hi! I'm using and editing the Presidio analyzer software as a python module to fit my requirements. One of the things I'd like to do is to add a parameter to the process, for example, passing the country to the AnalyzerEngine().analyze method (in addition to the existing parameters like text, language, entities, etc).
I managed to change the code for this purpose, adding a new parameter to the analyze method of entity_recognizer, local_recognizer, pattern_recognizer and a few other scripts, I did this very carefully but it doesn't work because some of the _pb2_grpc automatically generated scripts (using Google's protocol buffer) control the supported variables.
I was wondering if there's a way of regenerating this scripts using the existing (edited) code to add supported parameters.
Thank you so much for the attention!

**Comment by omri374** [comment]
Hi @LaraSchvartzman 
On the Presidio-Genproto repo, you can find some documentation on how to manipulate the proto files and generate new ones:
https://github.com/microsoft/presidio-genproto#changing-presidios-api

You would have to copy the new pb2 files into the analyzer folder once you generated new ones.

**Comment by LaraSchvartzman** [comment]
Thanks @omri374 !!! It's exactly what I needed.
