### ISSUE TITLE
Instructions do not clean up everything created

### ISSUE THREAD

**Issue by jasonshortphd** [microsoft/presidio#265]
**Describe the bug**
Following setup instructions and then the delete portion does not clean up everything in the subscription.

NetworkWatcherRG is left in the subscription.

**To Reproduce**
1. Setup everything using the instructions
2. Follow Clean Up Your Environment

**Expected behavior**
Everything should be removed

**Additional context**
NetworkWatcherRG is the only thing left at the end.

**Comment by navalev** [comment]
Hi @jasonshortphd 
Thanks for raising this issue. We will look into it and provide resolution within the upcoming weeks.

**Comment by jasonshortphd** [comment]
Sorry I think I posted this on the wrong project!
