### ISSUE TITLE
Links not working on documentation

### ISSUE THREAD

**Issue by DavidHernandez** [microsoft/presidio#267]
**Describe the bug**
There are a few links in the development documentation that are broken ( https://github.com/Microsoft/presidio/blob/master/docs/development.md )

**To Reproduce**
On https://github.com/Microsoft/presidio/blob/master/docs/development.md
- Link `Installing presidio-analyzer as a standalone Python package` links to https://github.com/microsoft/presidio/blob/omri374/new_dev_doc/docs/deploy.md#install-presidio-analyzer-as-a-python-package (404)
- Link `Adding new custom recognizers` links to https://github.com/microsoft/presidio/blob/omri374/new_dev_doc/docs/custom_fields.md (404)

**Comment by omri374** [comment]
Thanks @DavidHernandez 
We'll fix this shortly

**Comment by omri374** [comment]
PR  #268
