### ISSUE TITLE
Create a library version of presidio analyzer that can be shipped

### ISSUE THREAD

**Issue by PrahathessRaghavan** [microsoft/presidio#274]
Presidio as a library would be super helpful , running quick analyzer checks without a network call.

**Presidio Library:**

1. Very minimal compared to the service , just the analyzer, model and the recognizers.
2. Take in a text , a pattern library (the default ones will do ) and a confidence return true or false
3. Cross platform

**Comment by ammills01** [comment]
You may want to check out the following links:

https://github.com/microsoft/presidio/blob/master/docs/deploy.md#install-presidio-analyzer-as-a-python-package

https://github.com/microsoft/presidio-research

**Comment by omri374** [comment]
Hi PrahathessRaghavan. We are actively working on providing the analyzer as a standalone Python package downloadable from PyPI. You can either create your own wheel using the link provided by ammills01 or wait for the PyPI instance to be ready.

**Comment by sdolenc** [comment]
@omri374 , is this the official pypi package? https://pypi.org/project/presidio-analyzer/

If not, is there any estimate for when the package will arrive on pypi?

**Comment by omri374** [comment]
Hi @sdolenc, it is official but still in beta. 

We are mainly missing documentation and some tests around this use case, but it is essentially the same code as the analyzer service so no problem using it.
