### ISSUE TITLE
Presidio analyzer context only detects lemmatized terms and not phrases

### ISSUE THREAD

**Issue by omri374** [microsoft/presidio#287]
**Describe the bug**
When using Presidio's context detection, it only leverages lemmatized words as context. Adding support for phrases ("account number", "phone number") and not only lemmatized unigrams ("account","bank") could improve detection accuracy.

**Expected behavior**
Presidio recognizers could declare phrases as context terms, and these would be used during analysis.

**Comment by hummingbird1989** [comment]
@omri374 I opened a new issue #901 , but this seems relevant. Was there any progress on this?

**Comment by omri374** [comment]
Yes there was, see my answer on #901
