### ISSUE TITLE
Inconsistent anonymize results between Stream job and API calls

### ISSUE THREAD

**Issue by ammills01** [microsoft/presidio#294]
**Describe the bug**
When text is passed in that has no matching items, the API calls will return your original text. However, when you have a Stream job hooked up it only sends results to the sink if they have matching entities.

**To Reproduce**
1. Call the anonymize API endpoint with text like "It is a great afternoon" and any template
2. Observe the result, you should get back { "text": "It is a great afternoon" }
3. Now, publish an event to Kafka with the same text (I have not tested other job types)
4. Start a Streams job with a Kafka source and whatever sink you desire
5. Notice there is no result sent to your sink

**Expected behavior**
We should always get the text back, even if there are no items to anonymize.

**Additional context**
I have not tried to debug locally but looking at the code, this seems to be caused by the if statement in [./presidio-collector/cmd/presidio-collector/processor/processor.go](https://github.com/microsoft/presidio/blob/master/presidio-collector/cmd/presidio-collector/processor/processor.go), method ReceiveEventsFromStream. As far as I can tell nothing is blowing up, despite there being the possibility of a null reference exception checking analyzerResponse.AnalyzeResults.

`
		analyzerResponse, err := services.AnalyzeItem(ctx, text, streamRequest.AnalyzeTemplate)
		if err != nil {
			err = fmt.Errorf("error analyzing message: %s, error: %q", text, err.Error())
			return err
		}

		if len(analyzerResponse.AnalyzeResults) > 0 {
			anonymizerResult, err := services.AnonymizeItem(ctx, analyzerResponse.AnalyzeResults, text, streamRequest.AnonymizeTemplate)

			if err != nil {
				err = fmt.Errorf("error anonymizing item: %s/%s, error: %q", partition, sequence, err.Error())
				return err
			}

			err = services.SendResultToDatasink(ctx, analyzerResponse.AnalyzeResults, anonymizerResult, fmt.Sprintf("%s/%s", partition, sequence))
			if err != nil {
				err = fmt.Errorf("error sending message to datasink: %s/%s, error: %q", partition, sequence, err.Error())
				return err
			}
			log.Debug("%d results were sent to the datasink successfully", len(analyzerResponse.AnalyzeResults))

		}
		return nil
	})
`

As you can see, if there are no results in the analyzerResponse it skips the AnonymizerItem and SendResultToDatasink functions.

When you compare that to how Anonymize in [./presidio-api/cmd/presidio-api/api/anonymize/anonymize.go](https://github.com/microsoft/presidio/blob/master/presidio-api/cmd/presidio-api/api/anonymize/anonymize.go) handles it, it's clearly different. In this case, I assume analyzeRes is not nil, therefore the results are sent to AnonymizeItem and returned as the original text. I don't see any errors in the logs to indicate anything is blowing up.

`
	analyzeRes, err := api.Services.AnalyzeItem(ctx, anonymizeAPIRequest.Text, anonymizeAPIRequest.AnalyzeTemplate)
	if err != nil {
		return nil, err
	}
	if analyzeRes == nil {
		return nil, fmt.Errorf("No analyze results")
	}

	anonymizeRes, err := api.Services.AnonymizeItem(ctx, analyzeRes.AnalyzeResults, anonymizeAPIRequest.Text, anonymizeAPIRequest.AnonymizeTemplate)
	if err != nil {
		return nil, err
	} else if anonymizeRes == nil {
		return nil, fmt.Errorf("No anonymize results")
	}
	return anonymizeRes, nil
`

**Edit: I'm not sure why those code snippets are show some in, and some out of the code block. I've tried to fix it with no luck.

**Comment by omri374** [comment]
Hi @ammills01 
Thanks for your issue. This indeed looks like a bug, similar to https://github.com/microsoft/presidio/issues/206

If you get to fix this, a contribution would be great. Otherwise we'll triage it and try to get to it soon.

**Comment by eladiw** [comment]
Hi @ammills01,
We will check it out soon. thanks!
