### ISSUE TITLE
Reorganize protobuf files in analyzer

### ISSUE THREAD

**Issue by dhpollack** [microsoft/presidio#297]
It would be nice if the protobuf files were in a separate directory from the application files.  This requires a few tweaks to the current code base, but is not very difficult to do.  The general steps are that you need to make the generated protobufs [use relative imports](https://github.com/protocolbuffers/protobuf/issues/1491#issuecomment-438138293) and then change any reference to the protobufs to `import mydir.myproto_pb2`.  It would make the repo a lot cleaner and easier to work with for new people looking to contribute to the project.

**Comment by omri374** [comment]
Thanks @dhpollack
This is in our backlog. If you're interested in proposing a change in a PR, that would be great

**Comment by dhpollack** [comment]
@omri374 do you have a preference on the name of the directory?  I've actually implemented this on a local copy of presidio where I used `protobuf_models` as the directory name.  If that's fine then I can probably create a PR for this relatively quickly.

**Comment by omri374** [comment]
@dhapollack Thanks! `protobul_models` sounds good.
