### ISSUE TITLE
Streams job should maintain source key when producing to sink.

### ISSUE THREAD

**Issue by ammills01** [microsoft/presidio#298]
The streams process, specifically Kafka, should allow us to persist the source key to the sink.

1. Send keyed data to a source Kafka topic, use a GUID or ID of some sort
2. Start a Streams job to pull from the previous topic and dump into a Kafka sink
3. Consume data from the Kafka sink and notice the key is a DateTime, not the original key

Keyed data from a Kafka source, and possibly other sources like SQL, should maintain their key when produced to a sink. Having this capability would allow users who are using streaming tools, like KStreams, to more easily JOIN the data to other streams.

**Comment by LizaShak** [comment]
Hi Andrew, 
Thank you for creating the FR. It sounds like a nice and important feature to support! You are welcome to submit a PR to implement this FR. 
We will also add it to our backlog, so we can keep track of it.
