### ISSUE TITLE
presidio analyzer - config dir error

### ISSUE THREAD

**Issue by dhpollack** [microsoft/presidio#302]
**Describe the bug**
The presidio analyzer should have the default dir for the config to be in the user's home, but instead it creates a folder in the run dir named `~`.

**To Reproduce**
run the presidio analyzer

**Expected behavior**
`~` expands to the user home path

**Additional context**
The cli does not properly [expand the user dir](https://github.com/microsoft/presidio/blob/master/presidio-analyzer/presidio_analyzer/__main__.py#L152).  

**Solution**
`os.path.expanduser`

**Comment by eladiw** [comment]
Hi @dhpollack 
Thanks for opening this issue.

We will look into this issue. If you can contribute a PR it will be appreciated.
