### ISSUE TITLE
Typo in us_bank_recognizer misses key word 

### ISSUE THREAD

**Issue by gitcarbs** [microsoft/presidio#309]
**Describe the bug**

A simple sentence such as `this is my bank number 23431222` does not get detected as containing a US Bank number even though the regex matches. There's a typo in the recognizer which combines bank and check causing it to miss the context. 

**To Reproduce**

Run the analyzer against the sentence above. A bank entity won't be found.

**Expected behavior**
A `US_BANK_NUMBER` entity `23431222` is returned 

**Screenshots**

**Additional context**

**Comment by omri374** [comment]
Hi @gitcarbs, thanks for the PR!
