### ISSUE TITLE
The scan scheduler sample in the documentation doesn't work

### ISSUE THREAD

**Issue by akazemis** [microsoft/presidio#314]
**Describe the bug**
When you follow the sample JSON for the "schedule-scanner-cronjob" in the documents the API result would be HTTP 400 Bad Request with message: "ScannerCronJobTemplateId or ScannerCronJobRequest must be supplied"

**To Reproduce**
1. Go to 'https://microsoft.github.io/presidio/tutorial_scheduler.html'
2. Copy the JSON sample in the documentation and set it up with proper values
3. Call the "/api/v1/projects/<my-project>/schedule-scanner-cronjob" API on your Presidio API service
4. See error:
"ScannerCronJobTemplateId or ScannerCronJobRequest must be supplied"
HTTP 400
Bad Request

**Expected behavior**
No Error to be returned, HTTP 200 OK is expected

**Screenshots**
![image](https://user-images.githubusercontent.com/8045056/80060163-37ab6700-8571-11ea-93d7-8783573de64e.png)

**Additional context**
N/A

**Comment by LizaShak** [comment]
Hi @akazemis ,
Thank you for raising this issue and solving it in the PR :) We will review your PR as soon as possible.

**Comment by akazemis** [comment]
No worries, thanks Liza! Happy to contribute to this awesome project.

**Comment by navalev** [comment]
closing this issue as resolved in PR #315
