### ISSUE TITLE
assert_result_within_score_range() always uses range of 0-to-1 over range values passed as arguments

### ISSUE THREAD

**Issue by willsthompson** [microsoft/presidio#318]
**Describe the bug**
The function `assert_result_within_score_range()` in `presidio-analyzer/tests/assertions.py` always uses 0 and 1 as the expected min and max range boundaries, regardless of what range values are passed in through the `expected_score_min` and `expected_score_max` arguments. 

**To Reproduce**
1. Choose any recognizer test from `presidio-analyzer/tests/`
2. Change the range values to conflict with the current expected range (forcing it to fail)
3. The test still passes

**Expected behavior**
Min/max expected range arguments should take precedence over global min/max and constrain range of expected values beyond 0 and 1.

**Additional context**
The problem is that calls to `min()` and `max()` are swapped in the utility library, here:
https://github.com/microsoft/presidio/blob/master/presidio-analyzer/tests/assertions.py#L23-L24

**Comment by LizaShak** [comment]
Hi @willsthompson  ,
Thank you for raising this issue and fixing it in the PR :)
