### ISSUE TITLE
Update to go 1.14 and go modules

### ISSUE THREAD

**Issue by torosent** [microsoft/presidio#326]
Go services needs to be updated to latest go version and migrate to go modules.
This will remove the dependency on the obsolete dep tool.
**note:** make sure client-go import is up to date as well.

I also suggest to switch to [distroless](https://github.com/GoogleContainerTools/distroless) containers and golangci-lint instead of gometalinter

**Comment by omri374** [comment]
Hi @torosent, thanks for the information. We have both items on our backlog. Updating Go requires some complex refactoring. Feel free to propose a PR ;)

**Comment by omri374** [comment]
Deprecating Go in V2
