### ISSUE TITLE
broken urls under https://github.com/microsoft/presidio#developing-presidio

### ISSUE THREAD

**Issue by AlexanderTyan** [microsoft/presidio#328]
**Describe the bug**
A lot of hyperlinks under `https://github.com/microsoft/presidio#developing-presidio` are 404.

**To Reproduce**
1. Go to `https://github.com/microsoft/presidio#developing-presidio`
2. Click on e.g. "Create Reusable Templates"
~~3. Scroll down to '....'~~
4. See error 404

**Expected behavior**
links to lead to .md files

**Comment by omri374** [comment]
Hi @AlexanderTyan, thanks for the issue.
Should be fixed now.
