### ISSUE TITLE
broken hyperlink at https://github.com/microsoft/presidio/blob/master/docs/install.md#L5

### ISSUE THREAD

**Issue by AlexanderTyan** [microsoft/presidio#332]
**Describe the bug**
In https://github.com/microsoft/presidio/blob/master/docs/tutorial_analyzer.md#using-the-analyzer-service  "Install Presidio" link goes to 404 

**To Reproduce**
1. Go to https://github.com/microsoft/presidio/blob/master/docs/tutorial_analyzer.md#using-the-analyzer-service
2. Click on "Install Presidio"
~~3. Scroll down to '....'~~
4. See error 404

**Expected behavior**
Presidio install instructions .md

**Screenshots**

**Additional context**

**Comment by omri374** [comment]
Hi @AlexanderTyan , we've renamed "install.md" to "deploy.md" and probably missed this reference. A contribution would be great if you're interested. 
Should reference to https://github.com/microsoft/presidio/blob/master/docs/deploy.md

**Comment by AlexanderTyan** [comment]
cool just did a PR
