### ISSUE TITLE
OCR_SVC_ADDRESS is not supplied

### ISSUE THREAD

**Issue by iomatters** [microsoft/presidio#336]
I might have possibly missed something, I was using build.sh to deploy dockers, presidio-api outputs "ocr service address is empty" when started, apparently the OCR_SVC_ADDRESS is not being supplied to the container. 
Accordingly, presidio-api fails to anonymise images generating go runtime panic:

2020/06/04 03:26:59 [Recovery] 2020/06/04 - 03:26:59 panic recovered:
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:513 (0x42c3d8)
/usr/local/go/src/runtime/panic.go:82 (0x42b52d)
/usr/local/go/src/runtime/signal_unix.go:390 (0x441b81)
/go/src/github.com/Microsoft/presidio/pkg/presidio/services/services.go:309 (0x10ca683)
/go/src/github.com/Microsoft/presidio/presidio-api/cmd/presidio-api/api/anonymize-image/anonymize-image.go:109 (0x128f8e2)
/go/src/github.com/Microsoft/presidio/presidio-api/cmd/presidio-api/api/anonymize-image/anonymize-image.go:57 (0x128f15e)
 ....

Please advise on what may be wrong with the build.

**Comment by omri374** [comment]
Hi @iomatters, thank you for the information. We'll review this and get back to you.

**Comment by omri374** [comment]
Hi @iomatters, the build.sh is a simple deployment using Docker for a subset of Presidio's services. 
The image anonymization service is not a part of this deployment. Please refer to the [deployment doc](https://github.com/microsoft/presidio/blob/master/docs/deploy.md) on the different ways to deploy Presidio as a whole.
Another option is to alter the build.sh to contain the additional services (`presidio-anonymizer-image` and `presidio-ocr`)

Closing for now, feel free to re-open if you have additional issues or questions.
