### ISSUE TITLE
Errors will happen when upgrading the libraries

### ISSUE THREAD

**Issue by KateGo520** [microsoft/presidio#342]
(The purpose of this report is to alert `microsoft/presidio` to the possible problems when `microsoft/presidio` try to upgrade the following dependencies)

### github.com/Azure/azure-event-hubs-go  
-Latest Version: v3.3.0 (Latest commit 9898ba6 13 days ago)
-Where did you use it: 
https://github.com/microsoft/presidio/search?q=Azure%2Fazure-event-hubs-go&unscoped_q=Azure%2Fazure-event-hubs-go
-Detail: 
>[github.com/Azure/azure-event-hubs-go/go.mod](https://github.com/Azure/azure-event-hubs-go/blob/v3.3.0/go.mod#L1)
```
module github.com/Azure/azure-event-hubs-go/v3
go 1.13
require (
	github.com/Azure/azure-amqp-common-go/v3 v3.0.0
	…
) 
```

>[github.com/Azure/azure-event-hubs-go/eph/eph.go](https://github.com/Azure/azure-event-hubs-go/blob/v3.3.0/eph/eph.go#L36)
```
package eph
import (
	"github.com/Azure/azure-amqp-common-go/v3/auth"
	"github.com/Azure/azure-amqp-common-go/v3/conn"
	"github.com/Azure/azure-amqp-common-go/v3/sas"
	"github.com/Azure/azure-amqp-common-go/v3/uuid"
	"github.com/Azure/azure-event-hubs-go/v3"
	"github.com/Azure/azure-event-hubs-go/v3/persist"
	…
) 
```
This problem was introduced since **_Azure/azure-event-hubs-go v2.0.0_** . Now you used version v1.1.2 . If you try to upgrade **Azure/azure-event-hubs-g** to version ** v2.0.0** and **above**, you will get an error--- **_no package exists at "github.com/Azure/azure-event-hubs-go/v3" and "github.com/Azure/azure-amqp-common-go/v3"_**

## I investigated the libraries'  (**Azure/azure-event-hubs-go >= v2.0.0**)  release information and found the root cause of this issue is that---- 
1.	These dependencies all added [Go modules](https://github.com/golang/go/wiki/Modules) in the recent versions.

2.	They all comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation. Quoting the specification:
> A package that has migrated to Go Modules _must_ include the major version in the import path to reference any v2+ modules. For example,  Repo github.com/my/module migrated to Modules on version v3.x.y.  Then this repo should declare its module path with MAJOR version suffix "/v3"  (e.g., module `github.com/my/module/v3`), and its downstream project should use `"github.com/my/module/v3/mypkg"` to import this repo’s package.

3.	This "github.com/my/module/v3/mypkg" is not the `physical path`. So earlier versions of Go (including those that don't have minimal module awareness) plus all tooling (like dep, glide, govendor, etc) don't have `minimal module awareness` as of now and therefore don't handle import paths correctly See [golang/dep#1962](https://github.com/golang/dep/issues/1962), [golang/dep#2139](https://github.com/golang/dep/issues/2139).
> Note: creating a new branch is not required. If instead you have been previously releasing on master and would prefer to tag v3.0.0 on master, that is a viable option. (However, be aware that introducing an incompatible API change in master can cause issues for non-modules users who issue a go get -u given the go tool is not aware of semver prior to Go 1.11 or when module mode is not enabled in Go 1.11+).
> Pre-existing dependency management solutions such as dep currently can have problems consuming a v2+ module created in this way. See for example dep#1962.
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

### 1. Migrate to Go Modules.
Go Modules is the general trend of ecosystem, if you want a better upgrade package experience, migrating to Go Modules is a good choice.

Migrate to modules will be accompanied by the introduction of virtual paths(It was discussed above).
> This "github.com/my/module/v3/mypkg" is not the `physical path`. So Go versions older than 1.9.7 and 1.10.3 plus all third-party dependency management tools (like dep, glide, govendor, etc) don't have `minimal module awareness` as of now and therefore don't handle import paths correctly.

Then the downstream projects might be negatively affected in their building if they are module-unaware (Go versions older than 1.9.7 and 1.10.3; Or use third-party dependency management tools, such as: Dep, glide, govendor…).

### 2. Maintaining v2+ libraries that use Go Modules in Vendor directories. 
If `microsoft/presidio` want to keep using the dependency manage tools (like dep, glide, govendor, etc), and still want to upgrade the dependencies, can choose this fix strategy.
Manually download the dependencies into the vendor directory and do compatibility dispose(materialize the virtual path or delete the virtual part of the path). Avoid fetching the dependencies by virtual import paths. This may add some maintenance overhead compared to using modules.

As the import paths have different meanings between the projects adopting module repos and the non-module repos, materialize the virtual path is a better way to solve the issue, while ensuring compatibility with downstream module users. A textbook example provided by repo `github.com/moby/moby` is here:
https://github.com/moby/moby/blob/master/VENDORING.md
https://github.com/moby/moby/blob/master/vendor.conf
In the vendor directory, `github.com/moby/moby` adds the **/vN** subdirectory in the corresponding dependencies.
**This will help more downstream module users to work well with your package.**

### 3. Request upstream to do compatibility processing.
The `Azure/azure-event-hubs-go` have 1 module-unaware user1 in github, such as: entsearch11/apm…
https://github.com/search?q=Azure%2Fazure-event-hubs-go+filename%3Avendor.conf+filename%3Avendor.json+filename%3Aglide.toml+filename%3AGodep.toml+filename%3AGodep.json

## Summary
You can make a choice when you meet this DM issues by balancing your own development schedules/mode against the affects on the downstream projects.

For this issue, Solution 1 can maximize your benefits and with minimal impacts to your downstream projects the ecosystem. 

## References
* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

Do you plan to upgrade the libraries in near future?
Hope this issue report can help you ^_^
Thank you very much for your attention.

Best regards,
Kate

**Comment by itye-msft** [comment]
Hi @KateGo520 , we are investigating on how to upgrade the GO version.

**Comment by KateGo520** [comment]
Thanks for your reply. This report is a warm prompt for you to prevent or combat this issue. Just let you know the problem if you upgrade these dependencies in near future, before migrating to Go modules. By the way, the dependency manager dep does not work well with Go modules. The projects in Go modules still do not have module awareness if they use dep.
Hope this can help you.

Thanks again.
Kate

**Comment by omri374** [comment]
Closing as Go services are no longer supported.
