### ISSUE TITLE
Ignore certain words during anonymization

### ISSUE THREAD

**Issue by armaan6651** [microsoft/presidio#361]
I want to ignore certain medical terms during anonymization as Presidio is identifying them as Person names. 

I don't want to run anonymization on medical terms. Is there a way to make Presidio ignore certain words from a list/dictionary?

**Comment by omri374** [comment]
Hi @armaan6651. There is currently no functionality to ignore certain words. A simple solution could be to ignore a specific entity (e.g. Person) by passing a list of fields that you want to be analyzed. This would ignore all Person entities.
Another option is to change the acceptance threshold, which can help in case there are too many false positives.

**Comment by armaan6651** [comment]
Hi @omri374. Thank you for your reply. I noticed that the analyzer always gives a score of 0.85 to all names.

**Comment by omri374** [comment]
Yes, the ML model we're using (spacy) does not output prediction confidences, so these are hard-coded at 0.85.

**Comment by omri374** [comment]
A few more complex alternatives:
1. Replace the NER model we are using. See an evaluation we did [here](https://towardsdatascience.com/nlp-approaches-to-data-anonymization-1fb5bde6b929)
2. Adapt the `AnayzerEngine` to accept a list of words to ignore. 
3. Filter out some of the `RecognizerResult`s outputted by presidio-analyzer after analysis has completed and before anonymization takes place.
4. Create a new anonymization mechanism with built-in filter.

**Comment by armaan6651** [comment]
> A few more complex alternatives:
> 
> 1. Replace the NER model we are using with a more accurate one. See an evaluation we did [here](https://towardsdatascience.com/nlp-approaches-to-data-anonymization-1fb5bde6b929).
> 2. Adapt the `AnayzerEngine` to accept a list of words to ignore.
> 3. Filter out some of the `RecognizerResult`s outputted by presidio-analyzer after analysis has completed and before anonymization takes place.
> 4. Create a new anonymization mechanism with built-in filter.

Great! Thank you
