### ISSUE TITLE
US SSN recognizer very weak match test fails

### ISSUE THREAD

**Issue by willsthompson** [microsoft/presidio#362]
**Describe the bug**

I'm not sure if this is a bug, but one of the recognizer tests is disabled with the comment `TODO figure out why this fails` here: https://github.com/microsoft/presidio/blob/master/presidio-analyzer/tests/test_us_ssn_recognizer.py#L20-L21

The very weak match tests use `"078-05112"` and `"07805-112"` as input, but `UsSsnRecognizer`'s `invalidate_result()` function rejects SSNs with only one delimiter: https://github.com/microsoft/presidio/blob/master/presidio-analyzer/presidio_analyzer/predefined_recognizers/us_ssn_recognizer.py#L51

The comment in `invalidate_result()` suggests the purpose of the delimiter check is to reject mismatched delimiters. If that's all it's supposed to do, then I think this is a bug (and the function should probably check the number of delimiters before considering it mismatched).

**Comment by omri374** [comment]
@diwu1989 perhaps you can take a look?

**Comment by shridhardamle** [comment]
SSN recognizer is failing in demo too. If you load https://presidio-demo.azurewebsites.net/ SSN is exposed. If you edit it, it fixes the issue. For example delete 078 and put it back; now it recognizes it and then its anonymized.

**Comment by omri374** [comment]
Thanks @shridhardamle! We'll take a look.

**Comment by shridhardamle** [comment]
Appears to be fixed in demo https://presidio-demo.azurewebsites.net/

**Comment by omri374** [comment]
Fixed in v2.0.0
