### ISSUE TITLE
Unecessary logging in SpacyNlpEngine

### ISSUE THREAD

**Issue by leomehr-lumos** [microsoft/presidio#364]
**Describe the bug**
The SpacyNlpEngine always prints model info, even if the log level is not debug.

Specifically this line is the issue:
https://github.com/microsoft/presidio/blob/e5fe414fd6108095e9fade11280d8143a9948f88/presidio-analyzer/presidio_analyzer/nlp_engine/spacy_nlp_engine.py#L31

Note that spacy.info() is always called (even if the log level is > debug).

You can see from the spacy source that `silent=False` by default. https://github.com/explosion/spaCy/blob/3ec231f7e14422de3ba2efafe363cde37a45215e/spacy/cli/info.py#L20 

To reproduce, simply create an instance of the SpacyNlpEngine, and observe the terminal output.
```
SpacyNlpEngine(models={'en': 'en_core_web_md'})
```

This will _always_ generate the following output, even if the logging level is increased:
```
===================== Info about model 'en_core_web_md' =====================

lang             en
name             core_web_md
license          MIT
author           Explosion
url              https://explosion.ai
email            contact@explosion.ai
...
```

Lastly, more generally (not a bug, just a feature request) presidio doesn't seem to provide a good way to globally control logging -- it would be amazing if it were easier to configure logging across all of presidio, if it were more transparent from the docs, and if by default there was only WARNING logs, rather than INFO logging to stdout.

**Comment by omri374** [comment]
FYI, this is going to be fixed in V2

**Comment by navalev** [comment]
Hi @leomehr-lumos this issue was resolved in the latest release (V2). I will close this issue, but please re-open if you still face a problem
