### ISSUE TITLE
[NOT A ISSUE] [HELP REQUIRED] How to get the output of "what is anonymized in the image in a json/any other format"

### ISSUE THREAD

**Issue by devesh23** [microsoft/presidio#366]
I am trying to determine the accuracy of Presidio to integrate into my product. For that, I want to test it out against annotated images for which I have the annotation available in JSON. 

I am trying to figure out any way that I can get an output in JSON using presidio. Is it possible?

**Comment by omri374** [comment]
Hi @devesh23, not sure if this is still relevant, but we have released a new image redactor written in Python. It might be easier to tweak it to return a json instead of the redacted image.

**Comment by navalev** [comment]
@devesh23 we will be closing this. If there is still an issue, please re-open
