### ISSUE TITLE
Not bug: Need documentation on how to test the Azure K8 deployment

### ISSUE THREAD

**Issue by fd98279** [microsoft/presidio#368]
**Describe the bug**
Could you let me know how to test the anonymizer api? I deployed the helm chart and chart deployed fine. I set the port forwarding to local port 8080

 $ kubectl port-forward -n presidio $(kubectl get pod -n presidio -l app=presidio-demo-presidio-api -o jsonpath='{.items[0].metadata.name}') 8080:8080
:~/presidio/deployment$ kubectl port-forward -n presidio $(kubectl get pod -n presidio -l app=presidio-demo-presidio-api -o jsonpath='{.items[0].metadata.name}') 8080:8080
Forwarding from [::1]:8080 -> 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080
Handling connection for 8080

I get 404 not found when I test with demo data.

**To Reproduce**

$ curl 'http://localhost:8080/api/anonymize'   -H 'Connection: keep-alive'   -H 'accept: application/json'   -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.125 Safari/537.36'   -H 'content-type: application/json'   -H 'Origin: https://presidio-demo.azurewebsites.net'   -H'Sec-Fetch-Site: same-origin'   -H 'Sec-Fetch-Mode: cors'   -H 'Sec-Fetch-Dest: empty'   -H 'Referer: https://presidio-demo.azurewebsites.net/'   -H 'Accept-Language: en-US,en;q=0.9'   -H 'Cookie: ai_user=XdaKc|2020-07-27T14:34:31.902Z; ssm_au_c=ky3AGAJymQDytpZKa6gkpcru/+qA2uRdPl0vMdBPwUVwgAAAAK9KCnsyPMkqjN6/JFm26n0e8tGelCZizk/4kHi1jJno=; ai_session=b/wPs|1600113713962|1600113730465.705'   --data-binary $'{"input":"Here are a few examples sentences we currently support:\\n\\nHello, my name is David Johnson and I live in Maine. \\nMy credit card number is 4095-2609-9393-4932 and my Crypto wallet id is 16Yeky6GMjeNkAiNcBY7ZhrLoMSgg1BoyZ. \\n \\nOn September 18 I visited microsoft.com and sent an email to test@microsoft.com,  from the IP 192.168.0.1. \\n\\nMy passport: 191280345 and my phone number: (212) 555-1234. \\n\\nThis is a valid IBAN: IL150120690000003111111 . Can you please check the status on bank account 154567876544 in PresidiBank? \\n\\nKate\'s social security number is 078-05-1120.  Her driver license? it is 1234567A.\\n \\n\\nThis project welcomes contributions and suggestions. Most contributions require you to agree to a Contributor License Agreement (CLA) declaring that you have the right to, and actuallydo, grant us the rights to use your contribution. For details, visit https://cla.microsoft.com \\nWhen you submit a pull request, a CLA-bot will automatically determine whetheryou need to provide a CLA and decorate the PR appropriately (e.g., label, comment). \\nSimply follow the instructions provided by the bot. You will only need to do this once across all repos using our CLA. \\nThis project has adopted the Microsoft Open Source Code of Conduct. \\n\\nFor more information see the Code of Conduct FAQ or contact opencode@microsoft.com with any additional questions or comments.","filters":[{"name":"EMAIL_ADDRESS"},{"name":"LOCATION"},{"name":"PHONE_NUMBER"},{"name":"US_PASSPORT"},{"name":"US_SSN"},{"name":"CRYPTO"},{"name":"US_ITIN"},{"name":"DATE_TIME"},{"name":"IP_ADDRESS"},{"name":"US_BANK_NUMBER"},{"name":"US_DRIVER_LICENSE"},{"name":"CREDIT_CARD"},{"name":"DOMAIN_NAME"},{"name":"IBAN_CODE"},{"name":"NRP"},{"name":"PERSON"},{"name":"UK_NHS"}],"transformations":[{"fields":[{"name":"EMAIL_ADDRESS"}],"transformation":{"replaceValue":{"newValue":"<EMAIL_ADDRESS>"}}},{"fields":[{"name":"LOCATION"}],"transformation":{"replaceValue":{"newValue":"<LOCATION>"}}},{"fields":[{"name":"PHONE_NUMBER"}],"transformation":{"replaceValue":{"newValue":"<PHONE_NUMBER>"}}},{"fields":[{"name":"US_PASSPORT"}],"transformation":{"replaceValue":{"newValue":"<US_PASSPORT>"}}},{"fields":[{"name":"US_SSN"}],"transformation":{"replaceValue":{"newValue":"<US_SSN>"}}},{"fields":[{"name":"CRYPTO"}],"transformation":{"replaceValue":{"newValue":"<CRYPTO>"}}},{"fields":[{"name":"US_ITIN"}],"transformation":{"replaceValue":{"newValue":"<US_ITIN>"}}},{"fields":[{"name":"DATE_TIME"}],"transformation":{"replaceValue":{"newValue":"<DATE_TIME>"}}},{"fields":[{"name":"IP_ADDRESS"}],"transformation":{"replaceValue":{"newValue":"<IP_ADDRESS>"}}},{"fields":[{"name":"US_BANK_NUMBER"}],"transformation":{"replaceValue":{"newValue":"<US_BANK_NUMBER>"}}},{"fields":[{"name":"US_DRIVER_LICENSE"}],"transformation":{"replaceValue":{"newValue":"<US_DRIVER_LICENSE>"}}},{"fields":[{"name":"CREDIT_CARD"}],"transformation":{"replaceValue":{"newValue":"<CREDIT_CARD>"}}},{"fields":[{"name":"DOMAIN_NAME"}],"transformation":{"replaceValue":{"newValue":"<DOMAIN_NAME>"}}},{"fields":[{"name":"IBAN_CODE"}],"transformation":{"replaceValue":{"newValue":"<IBAN_CODE>"}}},{"fields":[{"name":"NRP"}],"transformation":{"replaceValue":{"newValue":"<NRP>"}}},{"fields":[{"name":"PERSON"}],"transformation":{"replaceValue":{"newValue":"<PERSON>"}}},{"fields":[{"name":"UK_NHS"}],"transformation":{"replaceValue":{"newValue":"<UK_NHS>"}}}]}'   --compressed
404 page not found$

**Expected behavior**
Should return Anonymized text

**Comment by eladiw** [comment]
Seems like the URL is incorrect. try the following endpoint
http://localhost:8080/api/v1/projects/123/anonymize

where the project can be any string (e.g. 123)

**Comment by fd98279** [comment]
Thanks, that helped: I consolidated the curl commands here:

kubectl port-forward -n presidio $(kubectl get pod -n presidio -l app=presidio-demo-presidio-api -o jsonpath='{.items[0].metadata.name}') 8080:8080
```

# Simple text analyze:
```bash
URL=http://localhost:8080/api/v1/projects/123/analyze
curl $URL \
-H 'Content-Type: application/json' \
-d '{"text":"John Smith lives in New York. We met yesterday morning in Seattle. I called him before on (212) 555-1234 to verify the appointment. He also told me that his drivers license is AC333991", "analyzeTemplate":{"allFields":true}  }'

[{"field":{"name":"PERSON"},"score":0.85,"location":{"end":10,"length":10}},{"field":{"name":"LOCATION"},"score":0.85,"location":{"start":20,"end":28,"length":8}},{"field":{"name":"DATE_TIME"},"score":0.85,"location":{"start":37,"end":46,"length":9}},{"field":{"name":"DATE_TIME"},"score":0.85,"location":{"start":47,"end":54,"length":7}},{"field":{"name":"LOCATION"},"score":0.85,"location":{"start":58,"end":65,"length":7}},{"field":{"name":"PERSON"},"score":0.85,"location":{"start":176,"end":184,"length":8}},{"field":{"name":"PHONE_NUMBER"},"score":0.7,"location":{"start":90,"end":104,"length":14}},{"field":{"name":"US_DRIVER_LICENSE"},"score":0.65,"location":{"start":176,"end":184,"length":8}}]
```

# Create a template
```bash
URL=http://localhost:8080/api/v1/templates/123/analyze/123
curl $URL \
-H 'Content-Type: application/json' \
-d '{"allFields":true}'
"Template added successfully"sampat@Azure:~$
```

# Detect Specific Entities
```bash
URL=http://localhost:8080/api/v1/templates/123/analyze/tmp-specific-entities
curl $URL \
-H 'Content-Type: application/json' \
-d '{"fields":[{"name":"PHONE_NUMBER"}, {"name":"LOCATION"}, {"name":"DATE_TIME"}]}'
"Template added successfully"sampat@Azure:~

URL=http://localhost:8080/api/v1/projects/123/analyze
curl $URL \
-H 'Content-Type: application/json' \
-d '{"text":"We met yesterday morning in Seattle and his phone number is (212) 555 1234", "AnalyzeTemplateId":"tmp-specific-entities"  }'

[{"field":{"name":"PHONE_NUMBER"},"score":1,"location":{"start":60,"end":74,"length":14}},{"field":{"name":"DATE_TIME"},"score":0.85,"location":{"start":7,"end":16,"length":9}},{"field":{"name":"DATE_TIME"},"score":0.85,"location":{"start":17,"end":24,"length":7}},{"field":{"name":"LOCATION"},"score":0.85,"location":{"start":28,"end":35,"length":7}}]
```

# Custom Anonymization
```bash
URL=http://localhost:8080//api/v1/templates/123/anonymize/tmp-custom-anonymization
curl $URL \
-H 'Content-Type: application/json' \
-d '{"fieldTypeTransformations":[{"fields":[{"name":"PHONE_NUMBER"}],"transformation":{"replaceValue":{"newValue":"\u003cphone-number\u003e"}}},{"fields":[{"name":"CREDIT_CARD"}],"transformation":{"redactValue":{}}}]}'
"Template added successfully"

URL=http://localhost:8080//api/v1/projects/123/anonymize
curl $URL \
-H 'Content-Type: application/json' \
-d '{"text":"my phone number is 057-555-2323 and my credit card is 4961-2765-5327-5913", "AnalyzeTemplateId":"tmp-specific-entities", "AnonymizeTemplateId":"tmp-custom-anonymization"}'

{"text":"my phone number is \u003cphone-number\u003e and my credit card is 4961-2765-5327-5913"
```

# Add Custom PII Entity Recognizer
```
URL=http://localhost:8080//api/v1/analyzer/recognizers/rocket
curl $URL \
-H 'Content-Type: application/json' \
-d '{"value": {"entity": "ROCKET","language": "en", "patterns": [{"name": "rocket-regex","regex": "\\W*(rocket)\\W*","score": 1}]}}'

"Recognizer was inserted successfully"
URL=http://localhost:8080/api/v1/projects/123/analyze
curl $URL \
-H 'Content-Type: application/json' \
-d '{"text":"They sent a rocket to the moon!", "analyzeTemplate":{"allFields":true}  }'
[{"field":{"name":"ROCKET"},"score":1,"location":{"start":11,"end":19,"length":8}}]
```
