### ISSUE TITLE
RecognizerRegistry uses root logger

### ISSUE THREAD

**Issue by ian-contiamo** [microsoft/presidio#372]
**Describe the bug**
The `RecognizerRegistry` class uses the root logger via `logging.info`:
https://github.com/microsoft/presidio/blob/master/presidio-analyzer/presidio_analyzer/recognizer_registry/recognizer_registry.py#L151

This makes logging quite verbose when analyzing thousands of strings, and - more importantly - difficult to suppress using the `logging` module.

**Expected behavior**
I would expect the recognizer registry module to use its own logger, so we can control it using something like:
```python
logging.getLogger("recognizer_registry").setLevel(logging.WARNING)
```

**Screenshots**
This is what I see repeated thousands of times in the logs:
```
2020-10-02 07:34:35,961 INFO     root       Returning a total of 16 recognizers (predefined + custom)
2020-10-02 07:34:35,970 INFO     root       Returning a total of 16 recognizers (predefined + custom)
2020-10-02 07:34:35,984 INFO     root       Returning a total of 16 recognizers (predefined + custom)
2020-10-02 07:34:35,992 INFO     root       Returning a total of 16 recognizers (predefined + custom)
```

**Comment by ian-contiamo** [comment]
**Edit** Thanks to this StackOverflow [answer](https://stackoverflow.com/a/64168240/5276797), I have managed to monkey-patch the logger:
```python
from presidio_analyzer.recognizer_registry import recognizer_registry

patched_logger = logging.getLogger("recognizer_registry")
patched_logger.setLevel(logging.WARNING)
recognizer_registry.logging = patched_logger
```

**Comment by omri374** [comment]
Hi @ian-contiamo, 
Thanks for the issue!
Are you interested in creating a PR? Instead of using the root logger, we can pass the [Presidio logger](https://github.com/microsoft/presidio/blob/master/presidio-analyzer/presidio_analyzer/presidio_logger.py) and use this one. We are using it in many other places, but probably missed some (like the `RecognizerRegistry`).

**Comment by omri374** [comment]
Fixed in V2

**Comment by omri374** [comment]
#469

**Comment by Welding-Torch** [comment]
If anyone still has logging problems with Presidio, add this to the beginning of your code to disable all loggers from imported modules:
```python
    # Disable loggers from all imported modules
    logging.config.dictConfig({
        'version': 1,
        'disable_existing_loggers': True,
    })
```
