### ISSUE TITLE
How to deal with different languages

### ISSUE THREAD

**Issue by rickgoud** [microsoft/presidio#373]
Hi,

Great repo! However only works for English. How would it work if we wanted to add classifiers for Dutch?  How to add them the best way and how does presidio know which classifiers to use depending on the language, or will it always run all (which feels like to much overkill, so should be a more intelligent way I don't fully understand yet.

Any help would be greatly appreciated!!

Regards,
Rick

**Comment by omri374** [comment]
Hi @rickgoud, thanks for your comment!

To get started with additional languages, see [here](https://github.com/microsoft/presidio/blob/master/docs/tutorial_analyzer.md#using-multiple-languages).
Note that you would have to create your own recognizers in Dutch. Presidio's architecture supports multiple languages and also supports spaCy and Stanza NLP frameworks which probably have language models in Dutch (I haven't checked myself).

For best practices on developing new recognizers, see [here](https://github.com/microsoft/presidio/blob/master/docs/developing_recognizers.md).

**Comment by Oheed911** [comment]
i can not find the files there, can you provide me the links, if they are updated? Thanks

**Comment by omri374** [comment]
Hi @Oheed911, please see the updated link here: https://microsoft.github.io/presidio/analyzer/languages/

**Comment by Oheed911** [comment]
Thanks!
