### ISSUE TITLE
Presidio Analyzer PyPi installation. 

### ISSUE THREAD

**Issue by walvekar** [microsoft/presidio#375]
Hello, 

Do you recommend installing the Presidio Analyzer via PyPi ? or would you rather have us use the wheel approach ?

Using PyPi simplifies our installation process, so we were inclined to use it. However, we were wondering if you will continue supporting installation via PyPi. Also do you see any advantages of using one approach over the other. 

Presidio Analyzer Installation via PyPI:  https://pypi.org/project/presidio-analyzer/ 
Wheel Approach: https://github.com/microsoft/presidio/blob/master/docs/deploy.md#install-presidio-analyzer-as-a-python-package

Thank you for creating and supporting this  project

**Comment by omri374** [comment]
Hi @walvekar 
You can definitely use the PyPI version (`pip install presidio-analyzer`). The PyPI version is aligned with the code in the master branch, and is not coupled with the official Presidio releases.
