### ISSUE TITLE
Analyze API can return Bad Request with certain text.

### ISSUE THREAD

**Issue by akrock** [microsoft/presidio#376]
**Describe the bug**
The analyze API can return a 400 status code with certain text.

Currently the following text causes this behavior.

`Galla's Pizza | 4849 Peachtree Road, Chamblee, GA 30341 770-500-3184`

**To Reproduce**
1. Send the text above to `/v1/projects/1/analyze`
2. Observe response.

**Expected behavior**
The normal response to the analyze method is returned.

**Current behavior**
A Status Code 400 is returned with the message:

"rpc error: code = Unknown desc = Exception calling application: invalid literal for int() with base 10: '341770-500-3184161000'"

**Additional context**
This result is observed with the container images that were available today, but processed as expected through: https://presidio-demo.azurewebsites.net/

**Comment by omri374** [comment]
Thanks, I was able to reproduce this. We're looking into it.

**Comment by omri374** [comment]
#377
