### ISSUE TITLE
Grpcio dependency version inconsistency 

### ISSUE THREAD

**Issue by walvekar** [microsoft/presidio#378]
Hello,

The version of `grpcio` in the  presidio-analyzer/Pipfile is set to the latest version. However, the version of grpcio in presidio-analyzer/setup.py is fixed to 1.21.1. 

Same is the case with protobuf. 

We are planning on using presidio-analyzer and are having a dependency conflict in our project due to this.  Would it be possible for you to update `setup.py` and have `grpcio` and `protobuf` point to the latest version ? Have both Pipfile and setup.py in sync. 

Thank you.

**Comment by omri374** [comment]
Hi @walvekar, would you consider creating a PR?

**Comment by omri374** [comment]
Fixed in version 2.0.0. grpcio is no longer a dependency
