### ISSUE TITLE
Unable to use the presidioservice

### ISSUE THREAD

**Issue by nikhil-neu** [microsoft/presidio#380]
I have deployed Presidio using the docker deployment
I see the 4 presidio docker containers running

i try to run this
$ echo -n '{"text":"John Smith lives in New York. We met yesterday morning in Seattle. I called him before on (212) 555-1234 to verify the appointment. He also told me that his drivers license is AC111921", "analyzeTemplate":{"fields":[]} }' | http -F --verify=
no http://172.105.253.118/api/v1/projects/1/analyze

and i get this
command not found

http: error: ConnectionError: HTTPConnectionPool(host='172.105.253.118', port=80): Max retries exceeded with url: /api/v1/projects/1/analyze (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fefb6735128>: Failed to establish a new connection: [Errno 111] Connection refused',)) while doing POST request to URL: http://172.105.253.118/api/v1/projects/1/analyze

**Comment by SujithThazhathveedu** [comment]
knock - knock

**Comment by sushilr007** [comment]
can you tell how are you running this service ?

**Comment by nikhil-neu** [comment]
@sushilr007 i just followed the deployment by docker documentation . I see the docker container running. Do i need to do anything else to the get the services running .

**Comment by fearghal** [comment]
@nikhil-neu I've gotten that connection error before from HTTPie when it can't reach the server, e.g. if I had a bad hostname in the url.

I've been deploying to the cloud, so I'm not sure how the local docker setup works, but I think it's most likely an incorrect IP address or a port-mapping issue.

Try hitting this url in the browser to see if you get a response.
http://172.105.253.118/api/v1/analyzer/recognizers/

There is also a 'command not found' error in your note. Maybe your shell doesn't have the 'echo' command?

Good luck!

**Comment by omri374** [comment]
Please try with the updated docs for Presidio version 2.0.0:

https://microsoft.github.io/presidio/samples/docker/
