### ISSUE TITLE
Presidio API not providing expected responses to requests

### ISSUE THREAD

**Issue by zoubinirani** [microsoft/presidio#381]
**Describe the bug**
The Presidio API is not providing expected responses to requests, suggesting that Presidio is not correctly set-up/working for me.

**To Reproduce**
1. Set up an AWS EC2 Ubuntu 18.04 instance (tried `t2.medium` and `t2.large`) and SSH in.
2. Prepare the development environment similar to steps here: https://medium.com/@mileshill_40155/install-microsoft-presidio-on-ubuntu-18-04-3b83f67e6bb0. I've also tested other development setups and had no additional success. 
3. Test sending requests to the API. Looks like the API is mounted to `http://0.0.0.0:8080` by default so I've sent my requests there.

**Expected behavior - Analyze Text**
_Request:_ `echo -n '{"text":"John Smith lives in New York. We met yesterday morning in Seattle. I called him before on (212) 555-1234 to verify the appointment. He also told me that his drivers license is AC111921", "analyzeTemplate":{"fields":[]} }' | http -F --verify=no http://0.0.0.0:8080/api/v1/projects/1/analyze`

_Response:_ `rpc error: code = Unknown desc = Exception calling application: No matching recognizers were found to serve the request.`

_Expected Response:_ I expect the service to analyze the text like this:

```
HTTP/1.1 200 OK
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/json; charset=utf-8
Date: Mon, 29 Apr 2019 08:14:42 GMT
Server: nginx/1.15.6
Transfer-Encoding: chunked
Vary: Accept-Encoding

[
    {
        "field": {
            "name": "PERSON"
        },
        "location": {
            "end": 10,
            "length": 10
        },
    ...
```

**Expected behavior - List Recognizers**

_Requests:_
`http http://0.0.0.0:8080/api/v1/analyzer/recognizers`
`http http://0.0.0.0:8080/api/v1/analyzer/recognizers/`

_Responses:_
```
HTTP/1.1 301 Moved Permanently
Content-Length: 64
Content-Type: text/html; charset=utf-8
Date: Mon, 05 Oct 2020 02:41:52 GMT
Location: /api/v1/analyzer/recognizers/

<a href="/api/v1/analyzer/recognizers/">Moved Permanently</a>.
```
```
HTTP/1.1 200 OK
Content-Length: 4
Content-Type: application/json; charset=utf-8
Date: Mon, 05 Oct 2020 04:15:38 GMT

null
```
_Expected Response:_ I expected one of the two responses to list the available recognizers.

**Additional context**
- Only HTTP requests could be processed (got a `ConnectionError` when sending HTTPS requests). 
- The problem I'm facing sounds really similar to issue #239 , which was due to the docker containers not being able to communicate with one another as a result of a `build.sh` error. Furthermore, it looks like another person has commented in that thread with a similar issue to mine. 

Please let me know if anything is unclear or more details are required.

**Comment by omri374** [comment]
Hi @zoubinirani,
From a first glance it looks like you are calling the Presidio analyzer with no requested fields (i.e. PII entities). You should either pass a list of fields (`"fields":["PERSON"]`) or to use all of them: `"analyzeTemplate":{"allFields":true}`.

**Comment by zoubinirani** [comment]
Hi @omri374 , 

I feel silly that seems to have fixed it. 

I should've looked at the examples provided more carefully to see if I was missing any details - `https://github.com/Microsoft/presidio/blob/master/docs/tutorial_service.md`.  Thanks for your quick help and response.

For others who may also have issues. I've included a few examples below.

**Analyzer:**
_Request:_ `echo -n '{"text":"John Smith lives in New York. We met yesterday morning in Seattle. I called him before on (212) 555-1234 to verify the appointment. He also told me that his drivers license is AC111921", "analyzeTemplate":{"allFields":true} }' | http -F --verify=no http://0.0.0.0:8080/api/v1/projects/1/analyze`

_Response:_ 
```
HTTP/1.1 200 OK
Content-Length: 616
Content-Type: application/json; charset=utf-8
Date: Thu, 03 Dec 2020 15:17:56 GMT
X-Correlation-Id: 0bb74ed1-cec4-4ee3-9e9e-10337d114db7

[
    {
        "field": {
            "name": "PERSON"
        },
        "location": {
            "end": 10,
            "length": 10
        },
        "score": 0.85
    },
    ...
```

**Redaction:**
_Requests:_
`echo -n '{"allFields":true}' | http -F --verify=no http://0.0.0.0:8080/api/v1/templates/1/analyze/analyze_all_fields`

```
echo -n '{"fieldTypeTransformations":[
{"fields":[{"name":"PHONE_NUMBER"}],"transformation":{"replaceValue":{"newValue":"\u003cPHONE_NUMBER\u003e"}}},
{"fields":[{"name":"CREDIT_CARD"}],"transformation":{"replaceValue":{"newValue":"\u003cCREDIT_CARD\u003e"}}},
{"fields":[{"name":"EMAIL_ADDRESS"}],"transformation":{"replaceValue":{"newValue":"\u003cEMAIL_ADDRESS\u003e"}}},
{"fields":[{"name":"IBAN_CODE"}],"transformation":{"replaceValue":{"newValue":"\u003cIBAN_CODE\u003e"}}},
{"fields":[{"name":"IP_ADDRESS"}],"transformation":{"replaceValue":{"newValue":"\u003cIP_ADDRESS\u003e"}}},
{"fields":[{"name":"NRP"}],"transformation":{"replaceValue":{"newValue":"\u003cNRP\u003e"}}},
{"fields":[{"name":"PERSON"}],"transformation":{"replaceValue":{"newValue":"\u003cPERSON\u003e"}}},
{"fields":[{"name":"PHONE_NUMBER"}],"transformation":{"replaceValue":{"newValue":"\u003cPHONE_NUMBER\u003e"}}},
{"fields":[{"name":"US_BANK_NUMBER"}],"transformation":{"replaceValue":{"newValue":"\u003cUS_BANK_NUMBER\u003e"}}},
{"fields":[{"name":"PHONE_NUMBER"}],"transformation":{"replaceValue":{"newValue":"\u003cPHONE_NUMBER\u003e"}}},
{"fields":[{"name":"US_DRIVER_LICENSE"}],"transformation":{"replaceValue":{"newValue":"\u003cUS_DRIVER_LICENSE\u003e"}}},
{"fields":[{"name":"US_ITIN"}],"transformation":{"replaceValue":{"newValue":"\u003cUS_ITIN\u003e"}}},
{"fields":[{"name":"US_PASSPORT"}],"transformation":{"replaceValue":{"newValue":"\u003cUS_PASSPORT\u003e"}}},
{"fields":[{"name":"US_SSN"}],"transformation":{"replaceValue":{"newValue":"\u003cUS_SSN\u003e"}}},
{"fields":[{"name":"UK_NHS"}],"transformation":{"replaceValue":{"newValue":"\u003cUK_NHS\u003e"}}}
]}' | http -F --verify=no http://0.0.0.0:8080/api/v1/templates/1/anonymize/redact_pii_fields
```

```
echo -n '{"text":"my phone number is 057-555-2323 and my credit card is 4961-2765-5327-5913",
 "AnalyzeTemplateId":"analyze_all_fields", "AnonymizeTemplateId": "redact_pii_fields" }' |
 http -F --verify=no http://0.0.0.0:8080/api/v1/projects/1/anonymize/
```

_Responses:_ 
```
HTTP/1.1 200 OK
Content-Length: 29
Content-Type: application/json; charset=utf-8
Date: Thu, 03 Dec 2020 15:33:41 GMT

"Template added successfully"
```

```
HTTP/1.1 200 OK
Content-Length: 29
Content-Type: application/json; charset=utf-8
Date: Thu, 03 Dec 2020 15:50:48 GMT

"Template added successfully"
```

```
HTTP/1.1 200 OK
Content-Length: 100
Content-Type: application/json; charset=utf-8
Date: Thu, 03 Dec 2020 15:51:12 GMT

{
    "text": "my phone number is <PHONE_NUMBER> and my credit card is <CREDIT_CARD>"
}
```
