### ISSUE TITLE
Unable to install presidio-analyzer in Python 3.8

### ISSUE THREAD

**Issue by sushilr007** [microsoft/presidio#382]
I am using Python 3.8 and its unable to install .whl from dist folder.
Presidio-analyzer is asking for grpcio==1.21.0 but it not able install in python 3.8.

**Screenshots**
![error](https://user-images.githubusercontent.com/35765579/100973597-da44b300-3560-11eb-90a9-8cb1a47fd64f.png)

**Comment by omri374** [comment]
Hi @sushilr007, we haven't tested Presidio on 3.8 yet. Best to use a virtual environment with 3.7

**Comment by sushilr007** [comment]
> Hi @sushilr007, we haven't tested Presidio on 3.8 yet. Best to use a virtual environment with 3.7

Thanks @omri374 its working in 3.7

**Comment by omri374** [comment]
FYI, this is going to be fixed in V2

**Comment by omri374** [comment]
Fixed in #392
