### ISSUE TITLE
presidio anonymizer for python

### ISSUE THREAD

**Issue by deepanshug** [microsoft/presidio#383]
Currently I can see presidio analyzer as python standalone package, is there any chance that python anonymizer or python recognizer package will be available?

it will be great if entire presidio can be available as python package.

**Comment by deepanshug** [comment]
It will be great if entire presidio can be available in python as package.

**Comment by omri374** [comment]
Thanks for your message @deepanshug 
The presidio anonymizer module is not a Python module, so we cannot release it as a Python package. However, most de-identification techniques (redaction, masking, replacing) are straightforward given the output of the Presidio Analyzer.

We don't have a python recognizer package. Did you mean the recognizer registry? Adding new recognizers via code is an alternative to the recognizer registry.

**Comment by deepanshug** [comment]
Hi,

Thanks for your response.
As you said, I just used python Analyzer and redacted words after that.

Regards
Deepanshu
________________________________

**Comment by omri374** [comment]
FYI, the plan for V2 is to have a python based anonymizer.

**Comment by deepanshug** [comment]
Thanks Omri for confirming. Looking forward to use it

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by omri374** [comment]
FYI, the `presidio-anonymizer` package/service in python is now available in alpha.
Using pip:
```sh
pip install presidio-anonymizer
```

From Dockerhub:
```
docker pull mcr.microsoft.com/presidio-anonymizer:v2-latest
```

[Initial documentation for the V2 anonymizer](https://github.com/microsoft/presidio/blob/V2/presidio-anonymizer/README.MD)

Any feedback is highly appreciated.

**Comment by deepanshug** [comment]
Thanks for the update.

________________________________
