### ISSUE TITLE
Architecture Question: Ability to process concurrent requests 

### ISSUE THREAD

**Issue by zoubinirani** [microsoft/presidio#384]
**Question:** does Presidio have the ability to process concurrent requests? And if so, is any configuration required?

**Background Information**
To give a bit of context, I'm currently parsing through a JSON document and want to send requests concurrently to the API endpoint for analysis/redaction. I have not been able to get Presidio to run requests concurrently and was wondering if there was any way to do so. 

From the documentation, the only information I could find about support for concurrency/parallelism is with the scheduler, saying that parallelism for scheduled jobs is **not supported**: https://microsoft.github.io/presidio/tutorial_scheduler.html.

**Comment by omri374** [comment]
Hi @zoubinirani ,
How did you deploy Presidio? Using Docker, python or Kubernetes?

In theory each call to the Presidio API is consecutive, but you can achieve parallelism using a Kubernetes deployment.

**Comment by zoubinirani** [comment]
> Hi @zoubinirani ,
> How did you deploy Presidio? Using Docker or Kubernetes?
> 
> In theory each call to the Presidio API is consecutive, but you can achieve parallelism using a Kubernetes deployment.

Thank you @omri374 for your quick response.

I've deployed using docker but am open to trying/testing k8 if the concurrency increase is significant.

A few follow-up questions:
- By consecutive do you mean that each call to the Presidio API is synchronous (i.e. Presidio will not start the next call before finishing the previous call)?
- Based on your response to https://github.com/microsoft/presidio/issues/244#issuecomment-566533112, it looks like Presidio performs faster when it has (1) less requests with more text vs. (2) more requests with less text. Do you recommend the approach of less requests with more text? As well, is there a maximum request length? 
- Is the only way to increase the number of concurrent jobs in Presidio by scaling the number of instances? i.e.:
   -  k8: scaling the number of pods
   - docker: adding more nodes and placing them behind a load balancer

**Comment by rahulraina7** [comment]
Maybe I can add a bit of more information for @zoubinirani 

> By consecutive do you mean that each call to the Presidio API is synchronous (i.e. Presidio will not start the next call before finishing the previous call)?

https://github.com/microsoft/presidio/blob/7935adf03c80a0ba5d53c6affb7d7c78198affaa/presidio-analyzer/presidio_analyzer/app.py#L80

As you can see this takes a thread pool, which executes RPC handlers

> Based on your response to #244 (comment), it looks like Presidio performs faster when it has (1) less requests with more text vs. (2) more requests with less text. Do you recommend the approach of less requests with more text? As well, is there a maximum request length?

More requests obviously would have more network overhead. Maybe do minibatch of requests to reduce overhead.

**Comment by zoubinirani** [comment]
Thanks @rahulraina7 . This helps a lot. 

Closing issue.
