### ISSUE TITLE
ERROR: Couldn't install package: pyre2

### ISSUE THREAD

**Issue by bhaveshkr** [microsoft/presidio#386]
**Describe the bug**
Build fails while installing packages in Pipfile.lock. It was working last week but seeing this since yesterday. There is no issue in installing https://github.com/torosent/pyre2/archive/release/0.2.23.zip using pip.

**To Reproduce**
clone presidio repo and run ./build

**Expected behavior**
It should install everything in Pipfile.lock without any error.

**Comment by sjoerd-dijkstra** [comment]
We were experiencing the same issue.

Using a workaround atm. From the [dev docs](https://github.com/microsoft/presidio/blob/master/docs/development.md#setting-up-the-python-environment-) it seems pyre2 is not mandatory. We disabled this package from the Pipfile and build using `pipenv install  --skip-lock`. I can confirm the resulting application works fine.

Will do some research on how to enable the package again. Maybe the offical [pip pyre2](https://pypi.org/project/pyre2/) can replace the one used in the [Pipfile](https://github.com/microsoft/presidio/blob/master/presidio-analyzer/Pipfile#L10)?

Cheers

**Comment by omri374** [comment]
Thanks @sjoerd-dijkstra for the provided workaround! We are actually looking onto removing the depdency on pyre2 and sticking with regex.

**Comment by omri374** [comment]
As mentioned above, pyre2 is indeed not mandatory. We will be removing it in the next version. For those interested in a workaround, just skip the installation of `pyre2` and Presidio will use `regex` as fallback.

**Comment by omri374** [comment]
Fixed in #467
