### ISSUE TITLE
Error in Azure DevOps pipeline downloading mcr.microsoft.com/presidio-golang-deps:latest

### ISSUE THREAD

**Issue by fearghal** [microsoft/presidio#389]
Hi,

I'm somewhat new to Presidio, so I'm not totally sure if what I'm doing is expected to work or if I'm doing something wrong. I see that the team is pretty responsive lately, so appreciate any guidance or insight.

My goal is to be able to implement some custom recognizers and deploy them to AKS cloud. I've deployed Presidio successfully to AKS, and now I'm trying to figure out how I can get my own fork of Presidio (with my custom recognizers) built, deployed and running in AKS.

I've got a Windows 10 development environment, so I was hoping to use Azure Cloud DevOps (projects + pipelines) to run the pipeline to build Presidio with my custom recognizers.

I've created a pipeline in Azure DevOps and pointed the pipelines tool to my (forked but unmodified) azure-pipelines.yml in GitHub. I've set the following variables in the pipeline: DOCKER_REGISTRY=mcr.microsoft.com, REGISTRY_NAME=presidio.cr.io.

When I run the pipeline manually from Azure DevOps, it fails with the error below. It looks like it can't find the manifest for presidio-golang-deps:latest on mcr.microsoft.com.

> Step 1/8 : ARG REGISTRY=presidio.azurecr.io
> Step 2/8 : ARG PRESIDIO_DEPS_LABEL=latest
> Step 3/8 : FROM ${REGISTRY}/presidio-golang-deps:${PRESIDIO_DEPS_LABEL}
> manifest for mcr.microsoft.com/presidio-golang-deps:latest not found: manifest unknown: manifest tagged by "latest" is not found
> Makefile:43: recipe for target 'docker-build-base' failed
> make: *** [docker-build-base] Error 1
> ##[error]Bash exited with code '2'.

I read somewhere (can't find the link) where it says that dockerhub is the place to search for / discover artifacts on mcr.microsoft.com. I don't see any presidio-golang-deps artifacts on dockerhub. Am I using the wrong settings to find this dependency?

Appreciate any insight from the team. If there's a better way to achieve my goal (i.e. develop custom recognizers on Windows 10 and deploy them to AKS with the rest of Presidio), I'm open to suggestions.

Thanks!
Fearghal.

PS: This is the full log from the Build & Test step of the pipeline.

Starting: Build & Test 
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.179.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/13ccd4f8-1a52-42e2-bf3c-155f1ee0cdb9.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  5230  100  5230    0     0  16829      0 --:--:-- --:--:-- --:--:-- 16870

ARCH = amd64
OS = linux
Will install into /home/vsts/work/1/s/gopath/bin
Fetching https://github.com/golang/dep/releases/latest..
Release Tag = v0.5.4
Fetching https://github.com/golang/dep/releases/tag/v0.5.4..
Fetching https://github.com/golang/dep/releases/download/v0.5.4/dep-linux-amd64..
Setting executable permissions.
Moving executable to /home/vsts/work/1/s/gopath/bin/dep
docker pull mcr.microsoft.com/presidio-golang-base: || echo "\nCould not pull shared base Go image from registry, building locally. If you planned to build locally, the previous error message can be ignored\n"
invalid reference format

Could not pull shared base Go image from registry, building locally. If you planned to build locally, the previous error message can be ignored

docker build --build-arg REGISTRY=mcr.microsoft.com --cache-from=mcr.microsoft.com/presidio-golang-base: --build-arg PRESIDIO_DEPS_LABEL='latest' -t mcr.microsoft.com/presidio-golang-base -f Dockerfile.golang.base .
Sending build context to Docker daemon   62.4MB

Step 1/8 : ARG REGISTRY=presidio.azurecr.io
Step 2/8 : ARG PRESIDIO_DEPS_LABEL=latest
Step 3/8 : FROM ${REGISTRY}/presidio-golang-deps:${PRESIDIO_DEPS_LABEL}
manifest for mcr.microsoft.com/presidio-golang-deps:latest not found: manifest unknown: manifest tagged by "latest" is not found
Makefile:43: recipe for target 'docker-build-base' failed
make: *** [docker-build-base] Error 1
##[error]Bash exited with code '2'.
Finishing: Build & Test

**Comment by omri374** [comment]
Hi @fearghal, If you have your own docker containers with a custom logic, you would have to use your own container registry as you will not be able to push your containers to the presidio container registry. See [Azure Container Registry](https://azure.microsoft.com/en-us/services/container-registry/).

Try replacing `presidio.azurecr.io` with your own container registry and see if this works. 

We are in the process of releasing more documentation on this, but it would take a few weeks before we have something ready.

**Comment by fearghal** [comment]
Hi @omri374 - thanks for taking the time to reply. 

I belatedly saw the note in Makefile about using your own container registry. 
# To use docker-build, you need to have Docker installed and configured. You should also set
# DOCKER_REGISTRY to your own personal registry if you are not pushing to the official upstream.

This makes sense. I did set up my own personal container registry and set the DOCKER_REGISTRY value to my own container registry.

However, I'm not sure if that's the problem here. I think the issue is in downloading the presidio-golang-deps container image. Is that something that my own pipeline is also supposed to build and upload, or can I pull it from an existing container registry?

Thanks again - appreciate any help.
Fearghal.

**Comment by omri374** [comment]
Hi @fearghal

In our CI pipeline there are two variables: REGISTRY and REGISTRY_NAME. You should put your ACR address on REGISTRY_NAME and your service principal in REGISTRY. This will in turn run the makefile with your private registry instead of presidio.azurecr.io.

CI pipeline: https://github.com/microsoft/presidio/blob/master/pipelines/CI-presidio.yaml

It's also possible to build the deps locally and push them to the container registry manually.

**Comment by fearghal** [comment]
Thanks @omri374, appreciate your feedback.

I eventually got a successful build in Azure pipelines thanks to your help.

You were right that I had to set the REGISTRY and REGISTRY_NAME variables for my own container registry (hosted on Azure) as you suggested. It took me a little while to figure out how to set up the service connection in Azure so that it could connect my container registry. In the end, it was straightforward.

However, I did have to build the three base images locally (presidio-golang-deps, presidio-golang-base, presidio-python-deps), and uploaded them manually to my container registry. I wasn't sure if I would be able to build these base containers on Windows, but I ran the build.sh script from a bash shell and it seemed to build the presidio-golang-deps and presidio-golang-base containers ok. I had to build the presidio-python-deps container manually. Is it worthwhile/possible to make these base containers available for download via docker hub? That might save people time to get up and running.

I also encountered the pyre2 build issue referenced in #386 and worked around that by removing the pyre2 dependency in my fork. I know you are migrating to v2 now, but you may want to consider fixing that in the v1 codebase as I think it breaks the build of the old codebase.

Thanks again - appreciate the notes on these forums. I've learned a lot from some of the other posts.
I will close this issue now. 
Fearghal.
