### ISSUE TITLE
Analyzer - NER context is limited

### ISSUE THREAD

**Issue by limorl** [Microsoft/presidio#40]
**Describe the bug**
NER (spacy) ability to increase score based on context is limited

**To Reproduce**
1. Go to 'analyzer/tests/tes_person.py
2. Run test with "Mr. Tailor" text
3. "Mr. Tailor" is not identified as a PERSON entity

**Expected behavior**
Should identify as person

**Comment by omri374** [comment]
Moving to internal backlog
