### ISSUE TITLE
Analyzer - Spacey NER recognized cities and countries as locations, but not addresses

### ISSUE THREAD

**Issue by limorl** [Microsoft/presidio#42]
**Describe the bug**
Only cities and countries are recognized as locations when using spacy NER

**To Reproduce**
1. analyze text of '5507 Ringgold Road, Chattanooga, TN 37412'
2. 5507 is recognized as DATE_TIME, the address is not reconized and Chattanooga is recognized . as location. TN is not recognized as a state,

**Comment by omri374** [comment]
Enhancement- add new address recognizer

**Comment by okpatil4u** [comment]
Hi there, I am having troubles recognizing address. Could you please point me to the commit where the address recognizer is added ?

**Comment by navalev** [comment]
Hi @okpatil4u a list of all supported entities can be found here https://microsoft.github.io/presidio/supported_entities/#list-of-supported-entities 
What issue are you facing, could you please provide an example?
