### ISSUE TITLE
Deploy presidio to Heroku

### ISSUE THREAD

**Issue by jay58** [microsoft/presidio#492]
When trying to deploy docker images from "mcr.microsoft.com" to Heroku facing issues.

Getting this error:
<img width="1199" alt="Heroku Logs" src="https://user-images.githubusercontent.com/18693532/107208492-ad60c080-6a27-11eb-812a-fdc154374622.png">

**Comment by omri374** [comment]
Hi @jay58,
We are very close to releasing a new set of containers. While they are still WIP, you can check out the [V2 branch](https://github.com/microsoft/presidio/tree/V2). This branch will replace the master branch in a few weeks from now.
If you'd like to try it out (**still in alpha!**), you can download the `v2-latest` tag from Dockerhub:
```sh
docker pull mcr.microsoft.com/presidio-analyzer:v2-latest
docker pull mcr.microsoft.com/presidio-anonymizer:v2-latest
```

The `presidio-api` image has been deprecated, as the `presidio-analyzer` and `presidio-anonymizer` services now support HTTP.

**Comment by omri374** [comment]
@jay58 please try with the new set of containers in version 2.0.0

For a similar deployment into Azure App Service, see this doc:
https://microsoft.github.io/presidio/samples/deployments/app-service/
