### ISSUE TITLE
SpaCy 3.0 support and installation error of version 2.3

### ISSUE THREAD

**Issue by m0canu1** [microsoft/presidio#583]
I got a lot of issues when installing presidio_analyzer via pip because of the 2.3 version of SpaCy. 

It would be nice to add the support to the newest SpaCy version.

**Comment by omri374** [comment]
Hi @m0canu1, we are looking into spacy 3.0 but an upgrade is not planned in the near future. Any contribution is mostly welcome.

What kind of issues are you facing?

**Comment by m0canu1** [comment]
Hi @omri374,

I get a lot of lines of error while trying to install it.

So i tried to install SpaCy 2.3.0 manually and, at the end of the error lines, I get:

`ERROR: Could not find a version that satisfies the requirement spacy==2.3.0
ERROR: No matching distribution found for spacy==2.3.0`

**Comment by navalev** [comment]
Hi @m0canu1 , presidio is currently support python 3.6 3.7 and 3.8. Can you please try with one of the supported version?

**Comment by navalev** [comment]
Hi @m0canu1 , Closing the issue for now, feel free to re-open if there is still an issue
