### ISSUE TITLE
How can I add Presidio-Analyzer Results as an input to Presidio-Anonymizer? 

### ISSUE THREAD

**Issue by EstebanTrujilloKriptos** [microsoft/presidio#597]
Hi everyone!

I've been testing presidio and I have one question regarding the integration of presidio-analyzer with presidio-anonymizer.
When I run presidio-analyzer, the result is the following: 

`results_analyzer_list = [type: PHONE_NUMBER, start: 19, end: 31, score: 0.85]`

What I want is to pass this result as an input to presidio-anonymizer. The normal way of doing is as following (manually setting the values):

`analyzer_results=[AnalyzerResult("PHONE_NUMBER", 19, 31, 0.85)]`

Is there a way of passing the complete result , avoiding to manually setting the values? Something like this:

`analyzer_results=[AnalyzerResult(results_analyzer_list)]`

Thanks for the help!

**Comment by omri374** [comment]
Hi @EstebanTrujilloKriptos,
Just checking, are you using version 2.0.1 or above? We fixed a bug on the integration of the analyzer and anonymizer. Results from the analyzer can directly pass into the anonymizer.

**Comment by EstebanTrujilloKriptos** [comment]
Thanks for the response @omri374 
Could you please leave an example of how to do it?
