### ISSUE TITLE
How to run 'ad-hoc' regex patterns or word lists in v2?

### ISSUE THREAD

**Issue by rickgoud** [microsoft/presidio#598]
We are using presidio to let different users define different 'triggers' to classify sensitive data 'n the fly' without having to program. With v2, this not seems possible anymore? Or how is this intended?
I understand you want to go stateless, but should be easy to let the parameters that previously where part of the post to create a pattern, now be a parameter in the get where then on the fly pattern recognition is done?
How do you envision users implement this feature, which was one of the best things of v1? Flexibility is killed if for every custom pattern to have to create a python script and restart your servers, right?

Thanks!

**Comment by omri374** [comment]
Hi @rickgoud,
Thanks for making us aware of your issue. We are currently looking into re-introducing this capability in V2. 
V2 is planned to grow iteratively, and this component is one of the highest priorities.
If you, or anyone else from the community, would like to contribute to this effort, please reach out to us at presidio@microsoft.com and we can discuss this further.

Some clarification on the recognizer store in V2: https://github.com/microsoft/presidio/discussions/584#discussioncomment-434562

**Comment by rickgoud** [comment]
Hi @omri374 ,

Thanks for the response! Do you have any ETA for adding this feature? Would be really a waste if that would limit people migrating to v2. If you let the users handle persistency by adding the required analyzers as parameters in the GET, presidio would not need a datastore (which you suggest in #584 ), right? That should make implementation much easier (large part can be copies from v2?) and not related to Kubernetes, right? I think with these 'ad-hoc' features added stateless, presidio v2 would be incredibly powerful!! Great indeed if the community could upvote this issue to support it's priority!

Thanks in advance people!

**Comment by omri374** [comment]
Hi @rickgoud
I'd like to make sure I understand what you mean by "If you let the users handle persistency by adding the required analyzers as parameters in the GET, presidio would not need a datastore".

Do you propose to add those regex patterns / deny-lists as part of the "analyze" request? So that I would not only send the text for analysis and the language, but also the actual patterns / lists to be used?

**Comment by rickgoud** [comment]
Hi @omri374 ,

Apologies for the unclarity. Indeed that is what I mean. I understand you want presidio to be stateless for scalability, which makes total sense. That would be possible if users can indeed add patterns in the analyze request, right?

Regards,
Rick

**Comment by olivierpaling** [comment]
Having the ability to have simple regex patterns / deny lists as part of the 'analyze request'  would be a great addition indeed for v2!

**Comment by sjoerd-dijkstra** [comment]
It would indeed be a nice feature of `v2` to be able to use 'custom recognizers' without having to change code and/or restart the analyzer application. To be able to dynamically do this in each `POST /analyze` request sounds nice! 😊

**Comment by rickgoud** [comment]
Hi @omri374 ; Anything you can share on if/when this issue gets picked-up? Apparently more people excitingly waiting for this! :). Also the context words in v1 were awesome!

**Comment by rickgoud** [comment]
@omri374, any updates/progress? Would be great!

**Comment by omri374** [comment]
Hi @rickgoud. Unfortunately I don't have an ETA for this. If you or any one else would be interested in contributing the stateless approach you mentioned in this issue, I would be happy to help with design, review or anything else needed. Feel free to reach out to presidio@microsoft.com.

**Comment by omri374** [comment]
Hi, please see PR #677

**Comment by rickgoud** [comment]
You are a rockstar @omri374!!
With this commit up to part with v1? Are there still some 'ToDo's' on your list? Specific things you would like to have feedback on?

Looking forward to giving it a spin!!

**Comment by omri374** [comment]
Thanks @rickgoud! This is still WIP, pending merge and release. 
As mentioned in this thread, this is not 100% in par with V1 as there is no state involved. Every ad-hoc recognizer would have to be attached to every request to the /analyze service. If you have a long list of ad-hoc recognizers, or a long list of strings in your deny list, for example, this payload could start becoming pretty large.

**Comment by olivierpaling** [comment]
Nice! Great effort @omri374 ! This MR includes ad-hoc recognizers for patterns and denylist, is the contexphrase extension also supported? Could not find a reference in the updated documentation. Thank you!

**Comment by omri374** [comment]
@olivierpaling should be! Good question, I will add tests to verify

**Comment by olivierpaling** [comment]
@omri374 great stuff! I was just testing your branch and noticed that when doing the /analyze POST without the 'entities' parameter, you get back all found recognizers including the add-hoc one. So far so good. If you define only the ad-hoc entity to narrow down the request it doesn't work. In the example I believe you use "US_DRIVER_LICENSE", "ZIP"] but if you only keep ZIP you get an error ["error": "No matching recognizers were found to serve the request."]. The other way around if you remove ZIP and keep US_DRIVER_LICENSE it still works and you get back both classifications. So it seems no need to put it in the entities parameter. 

Question of the day. Why is this the case and can we narrow down the request to ONLY analyzing based on the ad-hoc recognizer (ZIP in this example). 

Thank you!

**Comment by omri374** [comment]
Hi @livierpaling! Thanks for the feedback, this is still work in progress. Let me check exactly and update here.
