### ISSUE TITLE
combination of mulitple identities with proximity 

### ISSUE THREAD

**Issue by csyzhang** [microsoft/presidio#603]
I played presidio a bit today and it's pretty cool. I am wondering if I want to detect multiple identities within a given distance instead of single identity. what's the best practice to implement this? For example, if I want to detect any match of PERSON and Drivers License in a distance of at most 1000 characters, should I create a new recognizer and analyze the (start, end) output of each Person and drivers license match? or if there is any other better approaches? Thanks!

**Comment by omri374** [comment]
Hi @csyzhang, thanks for the feedback.

How about using the returned index values to perform the proximity detection? Presidio analyzer would return a list of `RecognizerResult`([source](https://github.com/microsoft/presidio/blob/main/presidio-analyzer/presidio_analyzer/recognizer_result.py)), each containing the start and end of the entity, as well as the detecting confidence (score). Leveraging those indices, you could probably find proximate ones and update the score, or perform some other form of post-processing.

Would this help in any way?

**Comment by csyzhang** [comment]
@omri374 , yeah, totally make sense. I also think the same way. It'd be great if we can generalize the second level analyzer for post-processing. :)

**Comment by omri374** [comment]
Thanks @csyzhang. We'll look into this and see if others have similar requirements. Closing the issue for now, feel free to re-open if you have additional questions or wish to re-discuss this.
