### ISSUE TITLE
How to add Custom Recognizer using patterns

### ISSUE THREAD

**Issue by kvrameshreddy** [microsoft/presidio#606]
Hi , 
How to add custom Recognizer using regex pattern. Please provide a example same as custom recognizer using deny_list.
when I try to pass a regex pattern in PatternRecognizer i am getting error as 
"
  File "C:\Users\admin\anaconda3\envs\presidio\lib\site-packages\presidio_analyzer\pattern_recognizer.py", line 182, in __analyze_patterns
    matches = re.finditer(pattern.regex, text, flags=flags)

AttributeError: 'str' object has no attribute 'regex' "

Thankyou.

**Comment by navalev** [comment]
Hi @kvrameshreddy, a sample for a regex based PII recognizer can be found in the presidio documentation https://github.com/microsoft/presidio/blob/main/docs/samples/python/customizing_presidio_analyzer.ipynb 
Please let us know if you still face any issues

**Comment by kvrameshreddy** [comment]
Thanks @navalev. Will check it out and open the issue if i face any problem.
