### ISSUE TITLE
Location recognition fails with context

### ISSUE THREAD

**Issue by cohsieh23** [microsoft/presidio#607]
**Describe the bug**
When I add context words nearby Locations, such as State, University, Institute, the location recognizer fails to detect as a location.

**To Reproduce**
I've tried using AnalyzerEngine on text phrases comparing locations vs universities with the same name, such as:
Florida vs University of Florida
Ohio vs. Ohio State
Massachusetts vs Massachusetts Institute of Technology
Toronto vs University of Toronto

**Expected behavior**
Location is detected regardless of context words around it.
i.e. University of Florida should recognize Florida

**Comment by navalev** [comment]
Thank you @cohsieh23, issue is logged and we will follow up on it

**Comment by omri374** [comment]
Hi @cohsieh23, thanks for your issue. 

Currently, only the pattern based recognizers leverage context words. For NER based recognizer (Person, location and others), the assumption is that the NER model would be using context words as part of the recognition process. 

The provided NER model (spaCy en_core_web_lg) has around 85% F1 score on these entities. There are more accurate models out there which you can plug into Presidio (like Flair or transformer based models in spaCy 3 which we're looking into incorporating). Another option is to train a model yourself. This could be a spaCy model, or other.

**Comment by omri374** [comment]
Closing this issue. Feel free to reopen if you have any additional questions or feedback.
