### ISSUE TITLE
Installing presidio_analyzer requires Visual C++ Build Tools?

### ISSUE THREAD

**Issue by lucazav** [microsoft/presidio#631]
I'm installing the analyzer in a conda environment with Python 3.9.1 on a Windows 10 x64 machine. I'm using the following code:

`pip install presidio_analyzer`

I'm getting an error saying:

> error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

But I didn't find any instruction in the README saying I need to install the Visual C++ build tools.
Then I installed the build tools removing all the optional features, but I get the same error. Do I need also any optional feature to be installed?

Maybe a reference about this issue in the README may help.

In details, here the full error message: 

> Collecting presidio_analyzer
>   Using cached presidio_analyzer-2.0.1-py3-none-any.whl (48 kB)
> Requirement already satisfied: regex==2020.11.13 in c:\users\lzavarella\miniconda3\envs\pbi_powerquery_env\lib\site-packages (from presidio_analyzer) (2020.11.13)
> Requirement already satisfied: pyyaml==5.4.1 in c:\users\lzavarella\miniconda3\envs\pbi_powerquery_env\lib\site-packages (from presidio_analyzer) (5.4.1)
> Collecting spacy==2.3
>   Using cached spacy-2.3.0.tar.gz (6.0 MB)
>   Installing build dependencies: started
>   Installing build dependencies: finished with status 'error'
>   ERROR: Command errored out with exit status 1:
>    command: 'C:\Users\LZavarella\miniconda3\envs\pbi_powerquery_env\python.exe' 'C:\Users\LZavarella\miniconda3\envs\pbi_powerquery_env\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\LZavarella\AppData\Local\Temp\pip-build-env-118enmk1\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cython>=0.25' 'cymem>=2.0.2,<2.1.0' 'preshed>=3.0.2,<3.1.0' 'murmurhash>=0.28.0,<1.1.0' thinc==7.4.1
>        cwd: None
>   Complete output (272 lines):
>   Collecting thinc==7.4.1
>     Using cached thinc-7.4.1.tar.gz (1.3 MB)
>   Collecting cymem<2.1.0,>=2.0.2
>     Using cached cymem-2.0.5-cp39-cp39-win_amd64.whl (36 kB)
>   Collecting cython>=0.25
>     Using cached Cython-0.29.22-py2.py3-none-any.whl (980 kB)
>   Collecting murmurhash<1.1.0,>=0.28.0
>     Using cached murmurhash-1.0.5-cp39-cp39-win_amd64.whl (21 kB)
>   Collecting preshed<3.1.0,>=3.0.2
>     Using cached preshed-3.0.5-cp39-cp39-win_amd64.whl (112 kB)
>   Collecting blis<0.5.0,>=0.4.0
>     Using cached blis-0.4.1.tar.gz (1.8 MB)
>   Collecting catalogue<1.1.0,>=0.0.7
>     Using cached catalogue-1.0.0-py2.py3-none-any.whl (7.7 kB)
>   Collecting numpy>=1.7.0
>     Using cached numpy-1.20.1-cp39-cp39-win_amd64.whl (13.7 MB)
>   Collecting plac<1.2.0,>=0.9.6
>     Using cached plac-1.1.3-py2.py3-none-any.whl (20 kB)
>   Collecting srsly<1.1.0,>=0.0.6
>     Using cached srsly-1.0.5-cp39-cp39-win_amd64.whl (177 kB)
>   Collecting tqdm<5.0.0,>=4.10.0
>     Using cached tqdm-4.59.0-py2.py3-none-any.whl (74 kB)
>   Collecting wasabi<1.1.0,>=0.0.9
>     Using cached wasabi-0.8.2-py3-none-any.whl (23 kB)
>   Collecting wheel
>     Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
>   Collecting setuptools
>     Using cached setuptools-54.1.3-py3-none-any.whl (785 kB)
>   Building wheels for collected packages: thinc, blis
>     Building wheel for thinc (setup.py): started
>     Building wheel for thinc (setup.py): finished with status 'error'
>     ERROR: Command errored out with exit status 1:
>      command: 'C:\Users\LZavarella\miniconda3\envs\pbi_powerquery_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LZavarella\\AppData\\Local\\Temp\\pip-install-5o8yiskq\\thinc_7afaa35e8d8c4b38bcfea3ed031b8421\\setup.py'"'"'; __file__='"'"'C:\\Users\\LZavarella\\AppData\\Local\\Temp\\pip-install-5o8yiskq\\thinc_7afaa35e8d8c4b38bcfea3ed031b8421\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\LZavarella\AppData\Local\Temp\pip-wheel-9kl_0gtu'
>          cwd: C:\Users\LZavarella\AppData\Local\Temp\pip-install-5o8yiskq\thinc_7afaa35e8d8c4b38bcfea3ed031b8421\
>     Complete output (173 lines):
>     running bdist_wheel
>     running build
>     running build_py
>     creating build
>     creating build\lib.win-amd64-3.9
>     creating build\lib.win-amd64-3.9\thinc
>     copying thinc\about.py -> build\lib.win-amd64-3.9\thinc
>     copying thinc\api.py -> build\lib.win-amd64-3.9\thinc
>     copying thinc\check.py -> build\lib.win-amd64-3.9\thinc
>     copying thinc\compat.py -> build\lib.win-amd64-3.9\thinc
>     copying thinc\config.py -> build\lib.win-amd64-3.9\thinc
>     copying thinc\describe.py -> build\lib.win-amd64-3.9\thinc
>     copying thinc\exceptions.py -> build\lib.win-amd64-3.9\thinc
>     copying thinc\i2v.py -> build\lib.win-amd64-3.9\thinc
>     copying thinc\loss.py -> build\lib.win-amd64-3.9\thinc
>     copying thinc\misc.py -> build\lib.win-amd64-3.9\thinc
>     copying thinc\rates.py -> build\lib.win-amd64-3.9\thinc
>     copying thinc\t2t.py -> build\lib.win-amd64-3.9\thinc
>     copying thinc\t2v.py -> build\lib.win-amd64-3.9\thinc
>     copying thinc\v2v.py -> build\lib.win-amd64-3.9\thinc
>     copying thinc\_registry.py -> build\lib.win-amd64-3.9\thinc
>     copying thinc\__init__.py -> build\lib.win-amd64-3.9\thinc
>     creating build\lib.win-amd64-3.9\thinc\tests
>     copying thinc\tests\conftest.py -> build\lib.win-amd64-3.9\thinc\tests
>     copying thinc\tests\strategies.py -> build\lib.win-amd64-3.9\thinc\tests
>     copying thinc\tests\test_api_funcs.py -> build\lib.win-amd64-3.9\thinc\tests
>     copying thinc\tests\test_config.py -> build\lib.win-amd64-3.9\thinc\tests
>     copying thinc\tests\test_util.py -> build\lib.win-amd64-3.9\thinc\tests
>     copying thinc\tests\util.py -> build\lib.win-amd64-3.9\thinc\tests
>     copying thinc\tests\__init__.py -> build\lib.win-amd64-3.9\thinc\tests
>     creating build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_about.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_affine.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_beam_search.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_check_exceptions.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_difference.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_feature_extracter.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_hash_embed.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_imports.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_linear.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_loss.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_mem.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_model.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_ops.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_pickle.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_pooling.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_pytorch_wrapper.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_rates.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\test_rnn.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     copying thinc\tests\unit\__init__.py -> build\lib.win-amd64-3.9\thinc\tests\unit
>     creating build\lib.win-amd64-3.9\thinc\tests\integration
>     copying thinc\tests\integration\test_affine_learns.py -> build\lib.win-amd64-3.9\thinc\tests\integration
>     copying thinc\tests\integration\test_basic_tagger.py -> build\lib.win-amd64-3.9\thinc\tests\integration
>     copying thinc\tests\integration\test_batch_norm.py -> build\lib.win-amd64-3.9\thinc\tests\integration
>     copying thinc\tests\integration\test_feed_forward.py -> build\lib.win-amd64-3.9\thinc\tests\integration
>     copying thinc\tests\integration\test_mnist.py -> build\lib.win-amd64-3.9\thinc\tests\integration
>     copying thinc\tests\integration\test_pickle.py -> build\lib.win-amd64-3.9\thinc\tests\integration
>     copying thinc\tests\integration\test_roundtrip_bytes.py -> build\lib.win-amd64-3.9\thinc\tests\integration
>     copying thinc\tests\integration\test_shape_check.py -> build\lib.win-amd64-3.9\thinc\tests\integration
>     copying thinc\tests\integration\__init__.py -> build\lib.win-amd64-3.9\thinc\tests\integration
>     creating build\lib.win-amd64-3.9\thinc\tests\linear
>     copying thinc\tests\linear\test_avgtron.py -> build\lib.win-amd64-3.9\thinc\tests\linear
>     copying thinc\tests\linear\test_linear.py -> build\lib.win-amd64-3.9\thinc\tests\linear
>     copying thinc\tests\linear\test_sparse_array.py -> build\lib.win-amd64-3.9\thinc\tests\linear
>     copying thinc\tests\linear\__init__.py -> build\lib.win-amd64-3.9\thinc\tests\linear
>     creating build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\linear\__init__.py -> build\lib.win-amd64-3.9\thinc\linear
>     creating build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\mem.py -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\pooling.py -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\train.py -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\util.py -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\vec2vec.py -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\vecs2vec.py -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\vecs2vecs.py -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\_custom_kernels.py -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\_lsuv.py -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\__init__.py -> build\lib.win-amd64-3.9\thinc\neural
>     creating build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\datasets.py -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\hpbff.py -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\load_nlp.py -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\visualizer.py -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\wrappers.py -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\__init__.py -> build\lib.win-amd64-3.9\thinc\extra
>     creating build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\affine.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\attention.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\batchnorm.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\convolution.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\difference.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\elu.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\embed.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\encoder_decoder.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\feature_extracter.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\feed_forward.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\function_layer.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\hash_embed.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\layernorm.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\maxout.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\mish.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\model.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\multiheaded_attention.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\relu.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\resnet.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\rnn.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\selu.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\softmax.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\static_vectors.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     copying thinc\neural\_classes\__init__.py -> build\lib.win-amd64-3.9\thinc\neural\_classes
>     creating build\lib.win-amd64-3.9\thinc\extra\_vendorized
>     copying thinc\extra\_vendorized\keras_datasets.py -> build\lib.win-amd64-3.9\thinc\extra\_vendorized
>     copying thinc\extra\_vendorized\keras_data_utils.py -> build\lib.win-amd64-3.9\thinc\extra\_vendorized
>     copying thinc\extra\_vendorized\keras_generic_utils.py -> build\lib.win-amd64-3.9\thinc\extra\_vendorized
>     copying thinc\extra\_vendorized\__init__.py -> build\lib.win-amd64-3.9\thinc\extra\_vendorized
>     creating build\lib.win-amd64-3.9\thinc\extra\wrapt
>     copying thinc\extra\wrapt\decorators.py -> build\lib.win-amd64-3.9\thinc\extra\wrapt
>     copying thinc\extra\wrapt\importer.py -> build\lib.win-amd64-3.9\thinc\extra\wrapt
>     copying thinc\extra\wrapt\wrappers.py -> build\lib.win-amd64-3.9\thinc\extra\wrapt
>     copying thinc\extra\wrapt\__init__.py -> build\lib.win-amd64-3.9\thinc\extra\wrapt
>     copying thinc\linalg.pyx -> build\lib.win-amd64-3.9\thinc
>     copying thinc\structs.pyx -> build\lib.win-amd64-3.9\thinc
>     copying thinc\typedefs.pyx -> build\lib.win-amd64-3.9\thinc
>     copying thinc\cpu.pxd -> build\lib.win-amd64-3.9\thinc
>     copying thinc\linalg.pxd -> build\lib.win-amd64-3.9\thinc
>     copying thinc\structs.pxd -> build\lib.win-amd64-3.9\thinc
>     copying thinc\typedefs.pxd -> build\lib.win-amd64-3.9\thinc
>     copying thinc\__init__.pxd -> build\lib.win-amd64-3.9\thinc
>     copying thinc\compile_time_constants.pxi -> build\lib.win-amd64-3.9\thinc
>     copying thinc\linalg.cpp -> build\lib.win-amd64-3.9\thinc
>     copying thinc\structs.cpp -> build\lib.win-amd64-3.9\thinc
>     copying thinc\typedefs.cpp -> build\lib.win-amd64-3.9\thinc
>     copying thinc\linear\avgtron.pyx -> build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\linear\features.pyx -> build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\linear\linear.pyx -> build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\linear\serialize.pyx -> build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\linear\sparse.pyx -> build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\linear\avgtron.pxd -> build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\linear\features.pxd -> build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\linear\serialize.pxd -> build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\linear\sparse.pxd -> build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\linear\__init__.pxd -> build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\linear\avgtron.cpp -> build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\linear\features.cpp -> build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\linear\linear.cpp -> build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\linear\serialize.cpp -> build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\linear\sparse.cpp -> build\lib.win-amd64-3.9\thinc\linear
>     copying thinc\neural\ops.pyx -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\optimizers.pyx -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\_aligned_alloc.pyx -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\cpu.pxd -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\ops.pxd -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\__init__.pxd -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\ops.cpp -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\optimizers.cpp -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\_aligned_alloc.cpp -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\_custom_kernels.cu -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\neural\_murmur3.cu -> build\lib.win-amd64-3.9\thinc\neural
>     copying thinc\extra\cache.pyx -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\eg.pyx -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\mb.pyx -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\search.pyx -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\cache.pxd -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\eg.pxd -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\mb.pxd -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\search.pxd -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\__init__.pxd -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\cache.cpp -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\eg.cpp -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\mb.cpp -> build\lib.win-amd64-3.9\thinc\extra
>     copying thinc\extra\search.cpp -> build\lib.win-amd64-3.9\thinc\extra
>     running build_ext
>     error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
>     ----------------------------------------
>     ERROR: Failed building wheel for thinc
>     Running setup.py clean for thinc
>     Building wheel for blis (setup.py): started
>     Building wheel for blis (setup.py): finished with status 'error'
>     ERROR: Command errored out with exit status 1:
>      command: 'C:\Users\LZavarella\miniconda3\envs\pbi_powerquery_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LZavarella\\AppData\\Local\\Temp\\pip-install-5o8yiskq\\blis_ef441a381adc4aadb401b9a8d43a3277\\setup.py'"'"'; __file__='"'"'C:\\Users\\LZavarella\\AppData\\Local\\Temp\\pip-install-5o8yiskq\\blis_ef441a381adc4aadb401b9a8d43a3277\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\LZavarella\AppData\Local\Temp\pip-wheel-daxopc00'
>          cwd: C:\Users\LZavarella\AppData\Local\Temp\pip-install-5o8yiskq\blis_ef441a381adc4aadb401b9a8d43a3277\
>     Complete output (21 lines):
>     BLIS_COMPILER? None
>     running bdist_wheel
>     running build
>     running build_py
>     creating build
>     creating build\lib.win-amd64-3.9
>     creating build\lib.win-amd64-3.9\blis
>     copying blis\about.py -> build\lib.win-amd64-3.9\blis
>     copying blis\benchmark.py -> build\lib.win-amd64-3.9\blis
>     copying blis\__init__.py -> build\lib.win-amd64-3.9\blis
>     creating build\lib.win-amd64-3.9\blis\tests
>     copying blis\tests\common.py -> build\lib.win-amd64-3.9\blis\tests
>     copying blis\tests\test_dotv.py -> build\lib.win-amd64-3.9\blis\tests
>     copying blis\tests\test_gemm.py -> build\lib.win-amd64-3.9\blis\tests
>     copying blis\tests\__init__.py -> build\lib.win-amd64-3.9\blis\tests
>     copying blis\cy.pyx -> build\lib.win-amd64-3.9\blis
>     copying blis\py.pyx -> build\lib.win-amd64-3.9\blis
>     copying blis\cy.pxd -> build\lib.win-amd64-3.9\blis
>     copying blis\__init__.pxd -> build\lib.win-amd64-3.9\blis
>     running build_ext
>     error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
>     --
>     ERROR: Failed building wheel for blis
>     Running setup.py clean for blis
>   Failed to build thinc blis
>   Installing collected packages: numpy, murmurhash, cymem, wasabi, tqdm, srsly, preshed, plac, catalogue, blis, wheel, thinc, setuptools, cython
>       Running setup.py install for blis: started
>       Running setup.py install for blis: finished with status 'error'
>       ERROR: Command errored out with exit status 1:
>        command: 'C:\Users\LZavarella\miniconda3\envs\pbi_powerquery_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LZavarella\\AppData\\Local\\Temp\\pip-install-5o8yiskq\\blis_ef441a381adc4aadb401b9a8d43a3277\\setup.py'"'"'; __file__='"'"'C:\\Users\\LZavarella\\AppData\\Local\\Temp\\pip-install-5o8yiskq\\blis_ef441a381adc4aadb401b9a8d43a3277\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\LZavarella\AppData\Local\Temp\pip-record-oximzx0b\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\LZavarella\AppData\Local\Temp\pip-build-env-118enmk1\overlay' --compile --install-headers 'C:\Users\LZavarella\AppData\Local\Temp\pip-build-env-118enmk1\overlay\Include\blis'
>            cwd: C:\Users\LZavarella\AppData\Local\Temp\pip-install-5o8yiskq\blis_ef441a381adc4aadb401b9a8d43a3277\
>       Complete output (21 lines):
>       BLIS_COMPILER? None
>       running install
>       running build
>       running build_py
>       creating build
>       creating build\lib.win-amd64-3.9
>       creating build\lib.win-amd64-3.9\blis
>       copying blis\about.py -> build\lib.win-amd64-3.9\blis
>       copying blis\benchmark.py -> build\lib.win-amd64-3.9\blis
>       copying blis\__init__.py -> build\lib.win-amd64-3.9\blis
>       creating build\lib.win-amd64-3.9\blis\tests
>       copying blis\tests\common.py -> build\lib.win-amd64-3.9\blis\tests
>       copying blis\tests\test_dotv.py -> build\lib.win-amd64-3.9\blis\tests
>       copying blis\tests\test_gemm.py -> build\lib.win-amd64-3.9\blis\tests
>       copying blis\tests\__init__.py -> build\lib.win-amd64-3.9\blis\tests
>       copying blis\cy.pyx -> build\lib.win-amd64-3.9\blis
>       copying blis\py.pyx -> build\lib.win-amd64-3.9\blis
>       copying blis\cy.pxd -> build\lib.win-amd64-3.9\blis
>       copying blis\__init__.pxd -> build\lib.win-amd64-3.9\blis
>       running build_ext
>       error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
> --
>   ERROR: Command errored out with exit status 1: 'C:\Users\LZavarella\miniconda3\envs\pbi_powerquery_env\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\LZavarella\\AppData\\Local\\Temp\\pip-install-5o8yiskq\\blis_ef441a381adc4aadb401b9a8d43a3277\\setup.py'"'"'; __file__='"'"'C:\\Users\\LZavarella\\AppData\\Local\\Temp\\pip-install-5o8yiskq\\blis_ef441a381adc4aadb401b9a8d43a3277\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\LZavarella\AppData\Local\Temp\pip-record-oximzx0b\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\LZavarella\AppData\Local\Temp\pip-build-env-118enmk1\overlay' --compile --install-headers 'C:\Users\LZavarella\AppData\Local\Temp\pip-build-env-118enmk1\overlay\Include\blis' Check the logs for full command output.
>  --
> ERROR: Command errored out with exit status 1: 'C:\Users\LZavarella\miniconda3\envs\pbi_powerquery_env\python.exe' 'C:\Users\LZavarella\miniconda3\envs\pbi_powerquery_env\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\LZavarella\AppData\Local\Temp\pip-build-env-118enmk1\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel 'cython>=0.25' 'cymem>=2.0.2,<2.1.0' 'preshed>=3.0.2,<3.1.0' 'murmurhash>=0.28.0,<1.1.0' thinc==7.4.1 Check the logs for full command output.

**Comment by SharonHart** [comment]
Hi @lucazav.
I think this is coming from spacy not having wheels for python 3.9 on the version we are using in Presidio. 
We formally support python versions 3.6 to 3.8 (will be added to our documentation website soon).
Thanks, Sharon

**Comment by lucazav** [comment]
Hi @SharonHart ,

thank you for your feedback.

Any hint to make it work on Python 3.9.1?
Do I need to install also Visual C++ Build Tools optional features?

Thanks.

**Comment by SharonHart** [comment]
@la

> Hi @SharonHart ,
> 
> thank you for your feedback.
> 
> Any hint to make it work on Python 3.9.1?
> Do I need to install also Visual C++ Build Tools optional features?
> 
> Thanks.

@lucazav For version 3.8, it should work without you installing the build tools. Haven't tested installing on 3.9.1 yet, but you might encounter other issues other than this one.
Thanks, Sharon

**Comment by lucazav** [comment]
Ok,

any chance to make it compatible also with Python 3.9?
If yes, any idea about when it'll be available?

Thank you so much.

**Comment by navalev** [comment]
@lucazav supporting python 3.9 is in our backlog, no ETA currently.
