### ISSUE TITLE
Anonymizing multiple emails with Faker in a text message

### ISSUE THREAD

**Issue by lucazav** [microsoft/presidio#633]
Hi,

I'm trying to anonymize emails using Faker. All is ok if in my text there is only one email address. If it contains multiple email addresses, the same fake email is used multiple times. Here the code I'm using:

```
def anonymizeEmail(text_to_anonymize): 
    analyzer_results = analyzer.analyze(text=text_to_anonymize, entities=["EMAIL_ADDRESS"], language='en')

    anonymized_results = anonymizer.anonymize(
        text=text_to_anonymize,
        analyzer_results=analyzer_results,    
        anonymizers_config={"EMAIL_ADDRESS": AnonymizerConfig("replace", {"new_value": fake.safe_email()})}
    )

    return anonymized_results

fake = Faker('en_US')
fake.add_provider(internet)

analyzer = AnalyzerEngine()
anonymizer = AnonymizerEngine()

text = 'The user has the following two emails: email1@gmail.com and email2@gmail.com'
anonymizeEmail(text)
```

The output is:

> The user has the following two emails: kenneth74@example.net and kenneth74@example.net

How can I change the `AnonymizerConfig` in order to generate a fake email address for each one found into the string?

Thanks.

**Comment by efung** [comment]
One way you could extend Presidio is by allowing the `AnonymizerConfig` objects to take lambda functions, not just static strings. 

Here's a diff that implements the idea:

```diff
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: presidio-anonymizer/presidio_anonymizer/anonymizers/replace.py
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ presidio-anonymizer/presidio_anonymizer/anonymizers/replace.py:18 @ class Replace(Anonymizer):
         new_val = params.get(self.NEW_VALUE)
         if not new_val:
             return f"<{params.get('entity_type')}>"
-        return new_val
+        return new_val(text) if callable(new_val) else new_val

     def validate(self, params: Dict = None) -> None:
         """Validate the new value is string."""
-        validate_type(params.get(self.NEW_VALUE), self.NEW_VALUE, str)
+        new_val = params.get(self.NEW_VALUE)
+        if callable(new_val):
+            return
+        else:
+            validate_type(new_val, self.NEW_VALUE, str)
         pass

     def anonymizer_name(self) -> str:
```

and here's how you would call it:

```python
    anonymized_result = anonymizer.anonymize(
        text=text_to_anonymize,
        analyzer_results=analyzer_results,    
        anonymizers_config={
            "EMAIL_ADDRESS": AnonymizerConfig("replace", {"new_value": lambda x: fake.safe_email()})
            }
    )
```

**Comment by navalev** [comment]
thank you @efung for suggesting this. @lucazav you can also create a new type of Anonymizer, instead of modifing the Replace anonymizer (in case that funtionalty will still be needed).

**Comment by lucazav** [comment]
Hi @navalev ,

sure, I could create a new Anonimizer. But it would be really useful to allow AnonymizerConfig to take lambda functions out-of-the-box.

**Comment by navalev** [comment]
Seems like a useful feature @lucazav! we welcome community contributions :)

**Comment by lucazav** [comment]
I'd like to contribute, @navalev. Unfortunately I'm not a master Pythonista. I'm just a data analyst :(

**Comment by navalev** [comment]
@lucazav this was added to our backlog - thanks for suggesting this feature!

**Comment by efung** [comment]
> @lucazav this was added to our backlog - thanks for suggesting this feature!

Great, thank you! We coincidentally needed this functionality today as well, which is why I spent some time to figure out how to do it.

**Comment by efung** [comment]
Another benefit of allowing lambdas (that are passed the input to be replaced, redacted, etc.) is that the function can examine the input.

For example, if the detected entity was a `<NAME>`, the function can see if it has one word (maybe just a first or last name) or more than one word (a full name). The replacement can then try to match the format of the original, maybe trying to match the case of the input as well.
