### ISSUE TITLE
Image anonymization is slow

### ISSUE THREAD

**Issue by kubistika** [microsoft/presidio#645]
Hi,

First of all, thank you guys for making this awesome project :)

I wanted to ask if there are any ways to improve image anonymization performance. I'm using Presidio as a python package and it takes about 5~ seconds to process pretty small images. I'm using the example code from the Presidio docs.

**Comment by omri374** [comment]
Hi @kubistika, thanks for your issue.
This is indeed a bug. the `AnalyzerEngine` instance used in the presidio-image-redactor is initialized on every request, which takes a few seconds. If you or anyone is interested in fixing it, that would be great. If not, we'll get to it soon.

**Comment by kubistika** [comment]
Hi @omri374, thanks for you reply. I submitted a pull request.

**Comment by navalev** [comment]
@kubistika issue was closed after your PR was merged - thanks for contributing! if there's still an issue, feel free to reopen this one, or open a new issue
