### ISSUE TITLE
Spacey package versions have conflicting dependencies

### ISSUE THREAD

**Issue by detwizard** [microsoft/presidio#660]
**Describe the bug**
pip installing presidio-image-redactor won't install due to conflicting dependencies, I have tried in a new environment also.
Which i thought was strange as you have upgraded the spacey version in your code a few days ago.

Message:
ERROR: Cannot install presidio-image-redactor because these package versions have conflicting dependencies.

The conflict is caused by:
    presidio-analyzer 2.1.0 depends on spacy==2.3
    presidio-analyzer 2.0.3 depends on spacy==2.3
    presidio-analyzer 2.0.2 depends on spacy==2.3
    presidio-analyzer 2.0.1 depends on spacy==2.3
    presidio-analyzer 2.0.0 depends on spacy==2.3

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

**Comment by omri374** [comment]
Hi @detwizard, thanks for your issue. We will be releasing new versions on Monday so these issues should be resolved after the release

**Comment by SharonHart** [comment]
@detwizard Can you please specify the python and pip versions you are using? 
Also by 'new environment' you meant virtualenv right?

**Comment by detwizard** [comment]
Hi, V21.0.1 for pip and 3.9 for python, but i have tried on v3.7 as well.
correct yeah i mean pipenv

**Comment by SharonHart** [comment]
@detwizard 
We've released a new version for presidio-analyzer with an updated version of spacy. 
It might resolved you issue, I can't tell for sure since I haven't been able to reproduce your issue.
Would be happy if you'll try and let us know.

**Comment by detwizard** [comment]
This has fixed the issue! thank you
