### ISSUE TITLE
Outdated import in python sample `presidio_notebook.ipynb`

### ISSUE THREAD

**Issue by alazraq** [microsoft/presidio#673]
- **Problem:** In the `presidio_notebook.ipynb` notebook under `docs\samples\python`, the following import statement is not used and does not work: `from presidio_anonymizer.entities import AnonymizerConfig`.
- **Solution:** This import statement should be replaced by `from presidio_anonymizer.entities.engine import OperatorConfig` which is used in the last cell.

**Comment by omri374** [comment]
Hi @alazraq, thanks for your issue! Would you like to contribute a fix?

**Comment by alazraq** [comment]
Hello @omri374, I would love to. This is just a one-line change if you give me Contributor rights I can do the PR quickly.

**Comment by omri374** [comment]
@alazraq thanks! You can just fork the repo and create a PR from your fork
