### ISSUE TITLE
Making PII not clear enough.

### ISSUE THREAD

**Issue by smirachowdhary** [microsoft/presidio#690]
I am learning python. I was implementing your code to work for credit card, not phone numbers, which is the only thing shown. What do I do?

**Comment by navalev** [comment]
Hi @smirachowdhary, presidio can detect a credit card entity, can u please share the code you are trying to execute?

**Comment by smirachowdhary** [comment]
Sure. Here:

text_to_anonymize = input("")

analyzer = AnalyzerEngine()
analyzer_results = analyzer.analyze(text=text_to_anonymize, entities=["PHONE_NUMBER"], language='en')

print(analyzer_results)

titles_recognizer = PatternRecognizer(supported_entity="TITLE",deny_list=["Mr.","Mrs.","Miss"])

analyzer.registry.add_recognizer(titles_recognizer)

analyzer_results = analyzer.analyze(text=text_to_anonymize,
entities=["TITLE"],
language="en")
print(analyzer_results)

analyzer_results = analyzer.analyze(text=text_to_anonymize, language='en')

anonymizer = AnonymizerEngine()

anonymized_results = anonymizer.anonymize(
    text=text_to_anonymize,
    analyzer_results=analyzer_results,    
    anonymizers_config={"DEFAULT": AnonymizerConfig("replace", {"new_value": "<ANONYMIZED>"}), 
                        "CREDIT_CARD": AnonymizerConfig("mask", {"type": "mask", "masking_char" : "*", "chars_to_mask" : 12, "from_end" : True}),
                        "TITLE": AnonymizerConfig("redact", {})}
)

print(anonymized_results)

**Comment by navalev** [comment]
gald to hear :) closing this issue, feel free to reopen if needed
