### ISSUE TITLE
Unable to use analyze_batch as a method

### ISSUE THREAD

**Issue by GLT-Dashboard** [microsoft/presidio#694]
Unable to use analyze_batch as a method 

![pii](https://user-images.githubusercontent.com/77790174/117404664-55c3db00-aed8-11eb-822c-e692e8b875e7.PNG)

**Comment by navalev** [comment]
Hi @GLT-Dashboard, the analyze_batch method is not part of the offical presidio release, and can be found in branch [omri374/batch_analyze](https://github.com/microsoft/presidio/tree/omri374/batch_analyze). You can build the presidio-anonymizer package from the branch to use the method.
