### ISSUE TITLE
Analyzer - Add analyzer support for JSON files

### ISSUE THREAD

**Issue by Ilanak** [microsoft/presidio#70]
Currently the analyzer is not trained to analyze json files. 
Therefor when analyzing these files the fields are detected wrongly:
Examples:

1.       {
        "text": "uuid:26c446d2-65a9-4eaa-9a70-53da2aded653\"}},{\"url\":\"http://synthetichealth.github.io",
        "field": {
            "name": "PERSON"
        },
        "probability": 0.85,
        "location": {
            "start": 1920,
            "end": 2005,
            "length": 85
        }
    },

2.
    {
        "text": "oid:2.16.840.1.113883.4.3.25\",\"value\":\"S99910353\"},{\"type\":{\"coding\":[{\"system\":\"http://hl7.org",
        "field": {
            "name": "NRP"
        },
        "probability": 0.85,
        "location": {
            "start": 2898,
            "end": 2993,
            "length": 95
        }
    }

Json files attached

[before-anonymization2.txt](https://github.com/Microsoft/presidio/files/2474011/before-anonymization2.txt)
[before-anonymization.txt](https://github.com/Microsoft/presidio/files/2474012/before-anonymization.txt)

**Comment by omri374** [comment]
Moving to internal backlog

**Comment by ammills01** [comment]
@omri374 do you all have plans to move forward with a solution to this?  If so, have you given any thought to it? I too have JSON files I'll be running through Presidio and as it sits now I'm getting malformed JSON back. My guess is the only good solution here is to loop over the JSON and send the value for each key into the anonymizer, which seems really expensive, but not as expensive as doing that on the client side and making API calls for each value.

**Comment by omri374** [comment]
@ammills01 I'll reopen the issue. We don't have any ETA on this, but we'll prioritize it for the next development cycle.

**Comment by omri374** [comment]
Looks like the right way to go here is to have official support for json files, and have the user define which fields should be analyzed and anonyized and which should be ignored. I suppose this would require a json schema from the user

**Comment by ammills01** [comment]
Thanks @omri374. One consideration I want to bring up is nested JSON. You may have n number of properties at the first level, and all of those are consistent and well known. But then one of those properties could contain a JSON object with n number of properties with nesting of its own. In my case, I know I want the content of only 1 property analyzed, details in the example below, and within that I don't have a consistent structure. I want the values analyzed, but not the keys. I can easily see passing in a struct decorated with something that tells Presidio which properties to analyze, but it gets kinda hairy when you dive into something more loosely structured like the 'details' object. 

`
    {
      "id": 1,
      "event_id": 100,
      "source": "test_source",
      "type": "test_type",
      "details": {
        ...
        lots of key/value pairs
        {
          ...
          some nesting with new k/v pairs
          {
            ...
            more nesting
          }
        }
        ...
      }
      ...
    }

`

**Comment by omri374** [comment]
Thanks @ammills01, I agree, that's the biggest challenge with JSON. I think the best solution would to provide an additional JSON which points to the specific parts of the json (nested or not) which needs to be analyzed. Then, Presidio would return the either the original JSON with updated values, or a small JSON with only the amended changes, and the user would have to merge the two back. Will that answer your need?

**Comment by ammills01** [comment]
> Thanks @ammills01, I agree, that's the biggest challenge with JSON. I think the best solution would to provide an additional JSON which points to the specific parts of the original json (nested or not) which needs to be analyzed. Then, Presidio would return the either the original JSON with updated values, or a small JSON with only the amended changes, and the user would have to merge the two back. Will that answer your need?

Yeah, that would work for me. I think returning the full JSON with updates would make life easier for most, but I can see a use case for only sending back the updates if bandwidth concerns come into play. Using this method, if I handed you a JSON object that contains the data and another that contains the field I want redacted, would you treat the field to be redacted as a string or would you see if it's JSON first? If it's JSON, would you stringify it and process it as a string or loop over all properties and analyze each value?

**Comment by omri374** [comment]
We've created some documentation on this matter here: #714
Please share any feedback you have on this.
