### ISSUE TITLE
Analyzer - detects part of a guid as phone number

### ISSUE THREAD

**Issue by Ilanak** [microsoft/presidio#71]
Analyzer detected part of this guid as phone number:
110bcd25-a55d-453a-8046-1297901ea002

    {
        "text": "046-1297901",
        "field": {
            "name": "PHONE_NUMBER"
        },
        "probability": 0.5,
        "location": {
            "start": 52,
            "end": 63,
            "length": 11
        }
    },

Json file attached
[test.txt](https://github.com/Microsoft/presidio/files/2474044/test.txt)

**Comment by teo-chenglim** [comment]
One possible solution is to filter probability that higher than 0.6?

**Comment by omri374** [comment]
Yes. some regexes have many false positives due to the simplicity of the pattern. We try to give lower confidence scores in these cases.

**Comment by omri374** [comment]
Closing for now as we have more detailed measures on false predictions between classes.
