### ISSUE TITLE
Defect - Image redactor occasionally creates an additional trailing bounding box 

### ISSUE THREAD

**Issue by rakan41** [microsoft/presidio#718]
**Describe the bug**
Image redactor occasionally creates an extra bounding box for the word following the PII text. This occurs when the PII text consists of more than one word and the preceding word is longer than the following word. 
For example, in the image below, the name on first line is incorrectly redacted, whereas it is incorrectly redacted in the first line. Because "Jessica" is longer than "Smith", the following word "lives" is also redacted. However, since "Constantine" is longer than "John", the error does not occur. 
![image](https://user-images.githubusercontent.com/44086695/119420642-51087f00-bd40-11eb-9746-7a356a307a90.png)

![image](https://user-images.githubusercontent.com/44086695/119420563-1e5e8680-bd40-11eb-87be-4a2d646fc4c9.png)

**To Reproduce**
1. Create a text document with PII text (e.g. names). Ensure there are examples where the PII text has more than one word, and the last word being shorter than the preceding word.
2. Convert the text document into an image (e.g. using snipping tool)
3. Pass the image in step 2 into the Presidio image redactor. 

**Expected behavior**
The image redactor should only redact the PII text and not any of the adjacent text. 

**Screenshots**
See above. 

**Additional context**
The bug can be found in the static method "map_analyzer_results_to_bounding_boxes" in the [image analyzer module](https://github.com/microsoft/presidio/blob/main/presidio-image-redactor/presidio_image_redactor/image_analyzer_engine.py). The "pos" increment at the end of the "while" loop should use the length of the previous word, not the current word.

**Comment by omri374** [comment]
Thanks @rakan41. Any contribution would be greatly appreciated.

**Comment by rakan41** [comment]
Updated code so that the bounding box is incremented by the current word length, rather than the next word. Seems to have fixed the issue for the above sample. 
![image](https://user-images.githubusercontent.com/44086695/122323708-dc091d80-cf6a-11eb-91bd-7d1a4f3cad32.png)

**Comment by rakan41** [comment]
Note the following changes after code change:

1. "lives" on first line no longer is redacted.
2. "London" is now redacted on second line. 
Both of these changes are expected behaviour.
