### ISSUE TITLE
Azure Pipelines Variable Group

### ISSUE THREAD

**Issue by daniel-bub** [microsoft/presidio#721]
Hi,

We want to setup an internal development pipeline based on the public presidio repository. For this we aim to use Azur DevOps and thus want to reuse the existing pipeline definitions.
Would it be possible to provide a description of the Variable Group, which is used within the pipeline? This would make an adoption easier.

BR Daniel

**Comment by SharonHart** [comment]
Hi @daniel-bub!
The variable group, referred as 'Presidio-V2-CI' in the pipelines contains the following variables:

ACR_AZURE_SUBSCRIPTION
ACR_REGISTRY_NAME
ANALYZER_DEV_APP_NAME
ANALYZER_PROD_APP_NAME
ANONYMIZER_DEV_APP_NAME
ANONYMIZER_PROD_APP_NAME
IMAGE_REDACTOR_DEV_APP_NAME
IMAGE_REDACTOR_PROD_APP_NAME
DEV_AZURE_SUBSCRIPTION
DEV_RESOURCE_GROUP_NAME
PROD_AZURE_SUBSCRIPTION
PROD_RESOURCE_GROUP_NAME

I hope most of those are self-explanatory, if not, let us know in another comment. 
Of course some of the variables can be discarded according to the use case, like when not developing for the image-redactor, or not using production resources.

**Comment by daniel-bub** [comment]
Thanks a lot for the quick reply. I haven't seen that part of the documentation. Good to know. Hopefully in the future Azure DevOps provides the ability to import variable groups via YAML templates. ;-)
