### ISSUE TITLE
PII detection for dates not working 

### ISSUE THREAD

**Issue by smirachowdhary** [microsoft/presidio#730]
I would like to report a bug. In the example below, I try to see if 3/3/2021 (date) is PII detected, its not, though its supposed to be. I have also tried with quite a few different dates.

Here is the code:

```
import PIIClass

def test_Birthdate_Single():
    #Arrange - setup input and objects
    pii = PIIClass.PII()
    s = "His name is Mr. Jones and his birthdate is on 3/3/2021."
    #Act - call the main method / function that you are testing
    res = pii.BirthdateAnalyzer(s)
    print(res)
    #Assert - verifying that your output is what is expected
    assert len(res) == 1
    assert res[0] == '3/3/2021'

def test_Birthdate_Multiple():
    #Arrange - setup input and objects
    pii = PIIClass.PII()
    s="""
    He can't wait for his birthday on 5/25/1989.
    His duaghter's birthday was 5/4/2000.
    His son's birthday is on 4/31/2009.
    """
    #Act - call the main method / function that you are testing
    res = pii.BirthdateAnalyzer(s)
    print(res)
    #Assert - verifying that your output is what is expected
    assert len(res) == 3
    assert res[0] == '5/25/1989'
    assert res[1] == '5/4/2000'
    assert res[2] == '4/31/2009'

def test_Birthdate_Zero():
    #Arrange - setup input and objects
    pii = PIIClass.PII()
    s="Valentine's Day is fun."
    #Act - call the main method / function that you are testing
    res = pii.BirthdateAnalyzer(s)
    print(res)
    #Assert - verifying that your output is what is expected
    assert len(res) == 0

```

Here is PIIClass.py:
from presidio_analyzer import AnalyzerEngine, PatternRecognizer
from presidio_anonymizer import AnonymizerEngine
from presidio_anonymizer.entities import AnonymizerConfig
# text: "His name is Mr. Jones and his phone number is 212-555-5555"

#text_to_anonymize = input("")

class PII:
    analyzer = AnalyzerEngine()

    def GetAnalyzerResultsByEntity(self,entity,text):
        result = []

        analyzer_results = PII.analyzer.analyze(text=text, entities=entity, language='en')
        for x in analyzer_results:
            result.append(text[x.start:x.end])
        
        return result
    
    def PhoneAnalyzer(self,text):
        return self.GetAnalyzerResultsByEntity(["PERSON"],text)
    
    def CreditCardAnalyzer(self,text):
        return self.GetAnalyzerResultsByEntity(["CREDIT_CARD"],text)
    
    def SocialSecurityNumberAnalyzer(self,text):
        return self.GetAnalyzerResultsByEntity(["US_SSN"],text)
    
    def PassportAnalyzer(self,text):
        return self.GetAnalyzerResultsByEntity(["US_PASSPORT"],text)
    
    def BankNumberAnalyzer(self,text):
        return self.GetAnalyzerResultsByEntity(["US_BANK_NUMBER"],text)
    
    def EmailAddressAnalyzer(self,text):
        return self.GetAnalyzerResultsByEntity(["EMAIL_ADDRESS"],text)
    
    def NameAnalyzer(self,text):
        return self.GetAnalyzerResultsByEntity(["PERSON"],text)
    
    def AddressAnalyzer(self,text):
        return self.GetAnalyzerResultsByEntity(["LOCATION"],text)
        # short forms of places don't count, and won't give FULL address just names of places and Ave, street, ect.
    
    def BirthdateAnalyzer(self,text):
        return self.GetAnalyzerResultsByEntity(["DATE_TIME"],text)
        # Trickiest. Includes:
        # "a year", "2 week", ect.
        # Holidays where there are dates in sentence

Here is the output:

PS C:\Smira\GitHub> pytest "c:/Smira/GitHub/PII--Detector/test cases/classes/Birthdate.py"
========================================================= test session starts =========================================================
platform win32 -- Python 3.8.8, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: C:\Smira\GitHub
collected 3 items

PII--Detector\test cases\classes\Birthdate.py FF.                                                                                [100%]

============================================================== FAILURES ===============================================================
________________________________________________________ test_Birthdate_Single ________________________________________________________

    def test_Birthdate_Single():
        #Arrange - setup input and objects
        pii = PIIClass.PII()
        s = "His name is Mr. Jones and his birthdate is on 3/3/2021."
        #Act - call the main method / function that you are testing
        res = pii.BirthdateAnalyzer(s)
        print(res)
        #Assert - verifying that your output is what is expected
>       assert len(res) == 1
E       assert 0 == 1
E        +  where 0 = len([])

PII--Detector\test cases\classes\Birthdate.py:11: AssertionError
-------------------------------------------------------- Captured stdout call ---------------------------------------------------------
[]
_______________________________________________________ test_Birthdate_Multiple _______________________________________________________

    def test_Birthdate_Multiple():        
        #Arrange - setup input and objects
        pii = PIIClass.PII()
        s="""
        He can't wait for his birthday on 5/25/1989.
        His duaghter's birthday was 5/4/2000.
        His son's birthday is on 4/31/2009.
        """
        #Act - call the main method / function that you are testing
        res = pii.BirthdateAnalyzer(s)
        print(res)
        #Assert - verifying that your output is what is expected
>       assert len(res) == 3
E       AssertionError: assert 2 == 3
E        +  where 2 = len(['5/25/1989', '4/31/2009'])

PII--Detector\test cases\classes\Birthdate.py:26: AssertionError
-------------------------------------------------------- Captured stdout call --------------------------------------------------------- 
['5/25/1989', '4/31/2009']
======================================================= short test summary info ======================================================= 
FAILED PII--Detector/test cases/classes/Birthdate.py::test_Birthdate_Single - assert 0 == 1
FAILED PII--Detector/test cases/classes/Birthdate.py::test_Birthdate_Multiple - AssertionError: assert 2 == 3
===================================================== 2 failed, 1 passed in 6.38s =====================================================

**Comment by SharonHart** [comment]
Hi @smirachowdhary,
We've introduced a new date recognizer in version 2.2.2, which we will release soon. Your expected dates should be recognized following this change.

**Comment by smirachowdhary** [comment]
Thank you, @SharonHart. Can you please let me know the expected time frame for release of version 2.2.2.

**Comment by smirachowdhary** [comment]
Okay! Thanks @SharonHart ! I'll do it now.
