### ISSUE TITLE
Errors on K8S

### ISSUE THREAD

**Issue by RoboBuffalo** [microsoft/presidio#737]
Hi there,
While I was deploying via docker image on k8s after container was running ran into below issue:
![image](https://user-images.githubusercontent.com/40163504/123393700-a2559980-d59e-11eb-8de7-daa7c5a7f529.png)

**Comment by omri374** [comment]
Hi @RoboBuffalo, have you deployed Presidio to k8s using the provided samples? Could you please provide a reproducible example?

**Comment by RoboBuffalo** [comment]
Thanks for your prompt response :)
I think as we're using istio in our k8s cluster ,It's hard to use samples.
In other hand for security policies I have to pull the image from hub and push it into internal image registry.

**Comment by navalev** [comment]
@RoboBuffalo what image are you trying to deploy? analyzer or anonymizer? 
Are you pulling the image from dockerhub or building it yourself?

**Comment by RoboBuffalo** [comment]
I'm pulling Analyzer from mcr.microsoft.com

**Comment by SharonHart** [comment]
@omri374 @navalev Not sure if its related, but pulling latest analyzer from MCR fetches a v1 version.

**Comment by SharonHart** [comment]
@RoboBuffalo Can you share some more traces? 
For example the whole output of command screenshot above (preferably with debug flag on)
Also share the output of `docker image inspect` on the image you're fetching to see that it's the correct one.

**Comment by navalev** [comment]
Hi @RoboBuffalo, could you update with some more logs on the issue you are facing?

**Comment by navalev** [comment]
@RoboBuffalo we will be closing this , please re-open if this is still an issue
