### ISSUE TITLE
how to analyzer cn phone eg: 18911192389 ?

### ISSUE THREAD

**Issue by jiankebe** [microsoft/presidio#746]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by jiankebe** [comment]
solve

**Comment by omri374** [comment]
Hi @jiankebe, posting an example here for others looking for a solution. The `PhoneRecognizer` class supports five regions by default: `("US", "UK", "DE", "FE", "IL")`. It is possible to either replace the default recognizer with a different one, or add an additional one in parallel to the existing one.

To create a new `PhoneRecognizer` looking for Chinese numbers, here's a code snippet:

```python
from presidio_analyzer import AnalyzerEngine
from presidio_analyzer.predefined_recognizers import PhoneRecognizer

# Create a new recognizer for CN numbers as CN is not a default region supported by the PhoneRecognizer
cn_phone_recognizer = PhoneRecognizer(supported_entities=["CN_PHONE_NUMBER"])
analyzer = AnalyzerEngine()
analyzer.registry.add_recognizer(cn_phone_recognizer)

res = analyzer.analyze(text="My number in Beijing is 10 6552 9988", language="en")
print(res)
```

Which results in
`[type: CN_PHONE_NUMBER, start: 24, end: 36, score: 0.95, type: LOCATION, start: 13, end: 20, score: 0.85]`

Presidio leverages the [phonenumbers](https://github.com/daviddrysdale/python-phonenumbers) Python package for phone number detection, and a Presidio user can define any region that the `phonenumbers` package supports. For more information on what this package can detect and how it detects it, see this xml file: https://github.com/daviddrysdale/python-phonenumbers/blob/dev/resources/PhoneNumberMetadata.xml
