### ISSUE TITLE
anonymize strips spaces and newlines from text

### ISSUE THREAD

**Issue by itaim** [microsoft/presidio#748]
**Describe the bug**
Anonymizing text eliminates spaces and new lines.
For example this text:
```
Let us know if you have any questions. Otherwise we can plan to discuss more on next week’s call.

Thanks!
John

John Doe | Marketing Manager, Paid Search | Marketing | Strategic Education, Inc. | 612.977.4912
```

Is parsed as:
```
Let us know if you have any questions. Otherwise we can plan to discuss more on <DATE_TIME> call.

Thanks!
<PERSON><PERSON> | Marketing Manager, Paid Search | Marketing | Strategic Education, Inc. | <PHONE_NUMBER>
```
As you can see the new lines and spaces were eliminated from between the persons making the text malformed.

**To Reproduce**
Code to reproduce:
```
def test_new_line():
    analyzer = AnalyzerEngine()
    results = analyzer.analyze(text3, "en")
    engine = AnonymizerEngine()
    anony = engine.anonymize(text3, results)
    print(anony.text)
```
**Expected behavior**
The text should maintain the spaces and newlines between entities

**Comment by navalev** [comment]
thanks @itaim! we'll look into this. We always welcome contributions to code :)

**Comment by bhushan-borole** [comment]
Hey @navalev 
I would like to work on this issue.

**Comment by navalev** [comment]
@bhushan-borole looking forward to your PR!

**Comment by bhushan-borole** [comment]
@navalev Judging from the reproduced code, the issue will probably be in `AnonymizerEngine` and not `AnalyzerEngine`.
I will take a look at it and let you know if I am stuck anywhere.

**Comment by omri374** [comment]
@bhushan-borole could you please share the output of the analyzer engine? Is there a space in between the indices of the two entities?

**Comment by bhushan-borole** [comment]
@omri374 I haven't set up presidio locally yet, I just used the web interface.

**Comment by omri374** [comment]
Just did a quick check and it seems like this is an issue with how spaCy detects entities in text.
```python
import spacy

nlp = spacy.load("en_core_web_lg")

text = """
Let us know if you have any questions. Otherwise we can plan to discuss more on next week’s call.

Thanks!
John

John Doe | Marketing Manager, Paid Search | Marketing | Strategic Education, Inc. | 612.977.4912
"""

doc = nlp(text)
[(ent.start, ent.end, ent.text, ent.label_) for ent in doc.ents]
```
Returns:
```
[(18, 21, 'next week’s', 'DATE'),
 (27, 29, 'John\n\n', 'PERSON'),
 (29, 33, 'John Doe | Marketing', 'PERSON')]
```

So the newline characters are actually part of the detected entity. This might be related to [this issue](https://github.com/explosion/spaCy/issues/4792).

Either preprocessing of the text or postprocessing of the list of `RecognizerResult`s could help overcome this issue.


Tested with this environment:
============================== Info about spaCy ==============================

spaCy version    3.0.6                         
Platform         Windows-10-10.0.19041-SP0     
Python version   3.7.9
