### ISSUE TITLE
Ability to pass kwargs to "redact" method for "ImageRedactorEngine" class

### ISSUE THREAD

**Issue by rakan41** [microsoft/presidio#749]
There are number of arguments available in the "analyze" method for the "AnalyzerEngine" class that would be useful have in the "redact" method for "ImageRedactorEngine". For example, the parameter "entities" in "analzye" method would be useful in "redact" method to ensure only selected entities are redacted. Similarly, the "score_threshold" parameter will also be useful in choosing the sensitivity of redaction. 

The proposed solution is to pass "**kwargs" argument in redact method. This will be similar to the implementation of "analyze" method in "ImageAnalyzerEngine" (see circled below). 
![image](https://user-images.githubusercontent.com/44086695/127096807-0aecb583-f690-4a7e-80a8-70939840c7e8.png)

![image](https://user-images.githubusercontent.com/44086695/127096640-f4b98420-a42c-4325-b7bd-ad219ffc1f9a.png)

**Comment by omri374** [comment]
Hey @rakan41, great suggestion! Thanks. Are you interested in creating a PR?

**Comment by rakan41** [comment]
@omri374 , yes no worries. Happy to have a look at this one.

**Comment by rakan41** [comment]
**SourceImage**
![image](https://user-images.githubusercontent.com/44086695/127276361-79f008b9-d3e3-45b2-bd43-bfd8542b1041.png)

**Before Change**
Running below redact method produces following: 
`redacted_image = engine.redact(image, (255, 192, 203))`
![image](https://user-images.githubusercontent.com/44086695/127276427-fde7dc37-30d9-477b-9806-9e263dcdd985.png)
Notice that the person, location, and phone number were all redacted. 
**Post Change**
We can now run the below redact method with entities as a parameter
`redacted_image = engine.redact(image, (255, 192, 203),entities=['PERSON', 'LOCATION'])`
![image](https://user-images.githubusercontent.com/44086695/127276761-6758e406-7546-4a91-8bcb-e1acd9474dbe.png)
Note that the phone number was not redacted. This is because "phone number" was not included as an entity in the key arguments above.

**Comment by omri374** [comment]
Looks good!
