### ISSUE TITLE
rule based address recognizer 

### ISSUE THREAD

**Issue by fatemerhmi** [microsoft/presidio#752]
I came across [this Demo](https://www.youtube.com/watch?v=1pUEG0MZxvM) and learned that `presidio` detect the address using data from open street map which includes: Names of places + point of interest + addresses for specific regions. 

Later in the demo `presidio` put his data in a Trie data structure and use term frequency to find the address. 

I looked into the [predefined recognizers](https://github.com/microsoft/presidio/tree/main/presidio-analyzer/presidio_analyzer/predefined_recognizers) and also the [supported list in documentation](https://microsoft.github.io/presidio/supported_entities/#list-of-supported-entities) but I wasn't able to find anything on address. 

As far as I was able to figure out, the address detection is part of [spacy recognizer](https://github.com/microsoft/presidio/blob/main/presidio-analyzer/presidio_analyzer/predefined_recognizers/spacy_recognizer.py#L37). But I wasn't able to find anything else. 

Would you please point out where the rule-based approach for finding address is located in the GitHub repo? Or is this something deprecated?

**Comment by fatemerhmi** [comment]
Hi @omri374, 

Of course. I'd be happy to collaborate on this :)

**Comment by omri374** [comment]
Syncing with @fatemerhmi offline.

**Comment by sdixit0309** [comment]
Hello,

Is there any update on this issue and is there any version of address recognizer available even in development/testing phase?

**Comment by omri374** [comment]
Hi @sdixit0309, there is no official address recognizer in Presidio.
What I would suggest to look into is NER models which were trained on data containing addresses.
For example: https://huggingface.co/obi/deid_roberta_i2b2

Here's an example Presidio recognizer which leverages this specific transformers model: https://huggingface.co/spaces/omri374/presidio/blob/main/transformers_recognizer.py (an adaptation of the [transformers sample](https://github.com/microsoft/presidio/blob/main/docs/samples/python/transformers_recognizer.py) in Presidio's samples gallery).
