### ISSUE TITLE
AnonymizerEngine not parsing anonymized text

### ISSUE THREAD

**Issue by damiank333** [microsoft/presidio#753]
**Describe the bug**
Anonymizer engine does not parse anonymized text.

I've been using presidio on Python 3.8.8 over the last week and note that there have been changes in the libraries and parameters used for anonymizing text. Prior to these changes, I was able to parse text with identifying information and print anonymized text, however, now the anonymized text is not being printed.

Using the code on your page as an example:

![Capture](https://user-images.githubusercontent.com/88767010/128991074-5bbe5412-a6e4-4d99-83b2-1001b668c20b.JPG)

This prints the following line and I'm not sure why that is: 
<presidio_anonymizer.entities.engine.result.engine_result.EngineResult object at 0x00000161DDA1F8B0> 

**Expected behavior**
The expected result would be: 
My name is BIP, BIP

**Comment by navalev** [comment]
@damiank333, what version of presidio are you using? and is it the containrized version of the python package?

**Comment by omri374** [comment]
I think there's a missing `__repr__` for the `EngineResult` class.

**Comment by omri374** [comment]
In the meantime, this should work:
1. To get the anonymized text:
```python
print(result.text)
```

2. To get the locations of anonymized entities:
```python
[(item.text, item.start, item.end) for item in result.items]
```

**Comment by damiank333** [comment]
Great thank you, that has resolved the issue
