### ISSUE TITLE
Unable to test Microsoft Presidio deployed as an Azure app service

### ISSUE THREAD

**Issue by palirashmi** [microsoft/presidio#756]
I deployed presidio to Azure as an app service using the link provided on this page:[ https://microsoft.github.io/presidio/samples/deployments/app-service/]( https://microsoft.github.io/presidio/samples/deployments/app-service/
) I am getting following error: {"error":"The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again."}

Can you pls help resolve this.

**Comment by SharonHart** [comment]
@palirashmi What URL are you trying to access? 
The root path should return a similar result, try to add /health for the healthprobe

**Comment by navalev** [comment]
Hi @palirashmi could you provide furthur information on the issue you face?

**Comment by omri374** [comment]
Closing for now, feel free to re-open if you have additional questions / information on this.
