### ISSUE TITLE
Batch Processing (Pandas Dataframe) with the ability to add additional additional regex recognizers

### ISSUE THREAD

**Issue by bilalbobat** [microsoft/presidio#764]
Hello

First off let me thank you for putting out such an excellent functionality, its great.

I am attempting to use the sample batch processing pandas dataframe example specified here:
https://microsoft.github.io/presidio/samples/python/batch_processing/

With my own additional regex recognizer(s) that I want to add to already default built ins.

I want the anonymisation to be applied to newly created Dataframe as per the sample you have shown

Here is the sample of the code I want adding which will identify any UK Postcodes:

How can I combine this to the existing code batch processing code, ideally an example showing multiple regex instances that a user may want to specify and how to apply the various Built-in operators ex redact, mask
 
```python
import pandas as pd

from presidio_analyzer import AnalyzerEngine, PatternRecognizer, EntityRecognizer, Pattern, RecognizerResult
from presidio_analyzer.recognizer_registry import RecognizerRegistry

from presidio_anonymizer import AnonymizerEngine

# Define the regex pattern in a Presidio `Pattern` object:
postcode_pattern = Pattern(name="POSTCODE_UK",regex="([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))\s?[0-9][A-Za-z]{2})", score = 0.5)

# Define the recognizer with one or more patterns
postcode_recognizer = PatternRecognizer(supported_entity="POSTCODE_UK", patterns = [postcode_pattern])

registry = RecognizerRegistry()
registry.load_predefined_recognizers()

```

The example above is purely for reference on the regex expression and naming that will need adding. Be handy to know as well on how to apply the different anonymisation options 

Sample Input File
[samplepatient - pandas.txt](https://github.com/microsoft/presidio/files/7147862/samplepatient.-.pandas.txt)

Output Should look like this
[samplepatient - pandas output.txt](https://github.com/microsoft/presidio/files/7147869/samplepatient.-.pandas.output.txt)

**Comment by omri374** [comment]
Hi @bilalbobat, thanks for your question.

In the batch processing sample, the two classes: `BatchAnalyzerEngine` and `BatchAnonymizerEngine` inherit from the standard `AnalyzerEngine` and `AnonymizerEngine` classes. Therefore, it's possible to pass the same arguments that the base class accepts. So instead of this cell:
```python
batch_analyzer = BatchAnalyzerEngine()
batch_anonymizer = BatchAnonymizerEngine()
```

Add this cell:

```python
# Define the regex pattern in a Presidio `Pattern` object:
postcode_pattern = Pattern(name="POSTCODE_UK",regex="([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1,2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1,2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))\s?[0-9][A-Za-z]{2})", score = 0.5)

# Define the recognizer with one or more patterns
postcode_recognizer = PatternRecognizer(supported_entity="POSTCODE_UK", patterns = [postcode_pattern])

registry = RecognizerRegistry()
registry.load_predefined_recognizers()

# Load the registry with the new recognizer to the AnalyzerEngine (in this case BatchAnalyzerEngine):
batch_analyzer = BatchAnalyzerEngine(registry=registry)
batch_anonymizer = BatchAnonymizerEngine()
```

> Tip: Consider breaking this regex into multiple ones and provide different confidence values to each. This will help determine the right acceptance threshold.

Hope this helps!

**Comment by omri374** [comment]
Closing for now, feel free to re-open if you have additional questions/issues.
