### ISSUE TITLE
Missing documentation for the phone number recognizer

### ISSUE THREAD

**Issue by omri374** [microsoft/presidio#772]
Presidio uses the [phonenumbers](https://github.com/daviddrysdale/python-phonenumbers) python package for better handling and coverage of phone numbers. [See code here](https://github.com/microsoft/presidio/blob/main/presidio-analyzer/presidio_analyzer/predefined_recognizers/phone_recognizer.py). 

It currently uses five regions ("US", "UK", "DE", "FE", "IL") as default, but could be extended by the user to every region supported by the `phonenumbers` package.

We're missing documentation for this, and should also consider having this recognizer be used as default (see [this comment on the PR](https://github.com/microsoft/presidio/pull/722#issuecomment-924331601)).

**Comment by lsmith77** [comment]
is this now fixed?

**Comment by omri374** [comment]
Not yet. If you have a specific question we'd be happy to provide guidance.

**Comment by ananyap18** [comment]
is this fixed ?

**Comment by omri374** [comment]
Anything specific documentation missing?
