### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by mcreichle** [microsoft/presidio#786]
**Describe the bug**
the PERSON attribute is triggered on exceedingly non person like strings. Did Elon Musk's Kid name mess up the algorithm? 

**To Reproduce**
from presidio_analyzer import AnalyzerEngine, RecognizerResult, RecognizerRegistry, Pattern

registry = RecognizerRegistry()
registry.load_predefined_recognizers()

a = AnalyzerEngine(registry=registry)

txt = 	"1607635102.00 -0.96"

result = a.analyze(text=txt,entities=["PERSON",],language='en')

print(result)

[type: PERSON, start: 14, end: 19, score: 0.85]

**Comment by undera** [comment]
I can evidence that specifically PERSON recognizer has a lot of false positives reported.

**Comment by omri374** [comment]
Consider using a different spacy model, like 'en_core_web_trf'
