### ISSUE TITLE
Feature: Support to Transformers engine

### ISSUE THREAD

**Issue by gustavorps** [microsoft/presidio#787]
Transformers provides the following tasks out of the box: 

* Sentiment analysis: is a text positive or negative?
* Text generation (in English): provide a prompt and the model will generate what follows.
* Name entity recognition (NER): in an input sentence, label each word with the entity it represents (person, place, etc.)
* Question answering: provide the model with some context and a question, extract the answer from the context.
* Filling masked text: given a text with masked words (e.g., replaced by `[MASK]`), fill the blanks.
* Summarization: generate a summary of a long text.
* Translation: translate a text in another language.
* Feature extraction: return a tensor representation of the text.

See the [Pipelines](https://huggingface.co/transformers/main_classes/pipelines.html) to understate the main supported tasks

**Comment by omri374** [comment]
Related to #887
