### ISSUE TITLE
Presidio demo - Anonymize text as default option

### ISSUE THREAD

**Issue by omri374** [Microsoft/presidio#79]
**Describe the bug**
The demo currently starts when all detected fields are not anonymized. The user doesn't see any of presidio's functionality unless he or she changes the action from None to something else.

**To Reproduce**
Start the demo

**Expected behavior**
Processed text should have detected fields anonymized instead of ignored.

**Comment by torosent** [comment]
@omri374  Fixed with Replace option.

Thank you @Ilanak
