### ISSUE TITLE
Issue with multi-line input

### ISSUE THREAD

**Issue by omri374** [microsoft/presidio#800]
Tried Presidio on latest Dockers.

Send the following text;
String inputText = "Mr. Cha Wee a 46year old male patient from Southampton presented with severe left loin colic pain 3 days duration.\n"
                + "Sent home on painkillers and plan for X-ray KUB and USS Abdomen ASAP. \n"
                + "He can be contacted on cha2008@gmail.com\n"
                + "or over the phone on +94773003053 and local number 077512 962 769";

Get an error 500!

Overall setup works fine with single liners such as ;
String inputText = "John Smith drivers license is AC432223";

Any thoughts how to allow multi line support ?

Thanks,

_Originally posted by @chamiw2008 in https://github.com/microsoft/presidio/discussions/799_

**Comment by omri374** [comment]
@chamiw2008 what error message did you get?

**Comment by chamiw2008** [comment]
500
Output : {"error":"The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application."}

**Comment by SharonHart** [comment]
@chamiw2008 Can you please share the full request details, or code snippet? I wasn't able to reproduce the issue. 
The following code snippet for using python requests works on multiline input:
```python
import json
import requests

inputText = "Mr. Cha Wee a 46year old male patient from Southampton presented with severe left loin colic pain 3 days duration.\n" + "Sent home on painkillers and plan for X-ray KUB and USS Abdomen ASAP. \n" + "He can be contacted on cha2008@gmail.com\n" + "or over the phone on +94773003053 and local number 077512 962 769"

response = requests.request("POST", "http://localhost:5002/analyze",
                            headers={'Content-Type': 'application/json'},
                            data=json.dumps({"text": inputText, "language": "en"}))

print(response.text)
```

**Comment by chamiw2008** [comment]
@SharonHart Thanks for taking the time to look in to the problem.

My code is in Java as I am trying to make a custom processor for the Apache NiFi to allow anonymization using Presidio.
Code is as below;

`    private String analyse(String jsonInputString, String urlString) throws MalformedURLException, IOException {

        URL url = new URL(urlString);

        HttpURLConnection con = (HttpURLConnection) url.openConnection();
        con.setRequestMethod("POST");
        con.setRequestProperty("Content-Type", "application/json");
        // con.setRequestProperty("Accept", "application/json");
        con.setDoOutput(true);

        try (OutputStream os = con.getOutputStream()) {
            byte[] input = jsonInputString.getBytes("utf-8");
            os.write(input, 0, input.length);
        }

        int responseCode = con.getResponseCode();
        String output = "";

        switch (responseCode) {
            case 200:
            case 201:

                BufferedReader br = new BufferedReader(new InputStreamReader(con.getInputStream()));
                StringBuilder sb = new StringBuilder();
                String line;
                while ((line = br.readLine()) != null) {
                    sb.append(line + "\n");
                }
                br.close();
                output = sb.toString();
        }

     
        System.out.println("Respose : " + responseCode);
        System.out.println("Output : " + output);
        return output;
    }` 

Input was as in the original post.
For the time being I have removed all the newline characters. But that changes the formatting in the output probably making it difficult to read longer text.

Thanks.

**Comment by SharonHart** [comment]
@chamiw2008 I beleive that although the response is 500, this is a client issue on how the request is made (I believe that there's a bug propagating 400s as 500s). An evidance is the client code I've provided that sends a similar input to yours. Nevertheless, I'll try to take a look at the snippet you've provided.

**Comment by SharonHart** [comment]
@chamiw2008 Seems like jsonInputString is missing, can you please provide it as well?

**Comment by SharonHart** [comment]
Closing as not reproducible, feel free to supply further information
