### ISSUE TITLE
Unable to use stanza as NlpEngineProvider

### ISSUE THREAD

**Issue by Subrat08** [microsoft/presidio#813]
**Describe the bug**
I am trying to use stanza instead of spacy as NlpEngineProvider. While doing so I am getting error as Wrong NLP engine configuration

**To Reproduce**
`from presidio_analyzer.nlp_engine import NlpEngineProvider
configuration = {
    "nlp_engine_name": "stanza",
    "models": [{"lang_code": "en", "model_name": "OntoNotes"}],
}`

`provider = NlpEngineProvider()
provider.nlp_engines`
returns {'spacy': presidio_analyzer.nlp_engine.spacy_nlp_engine.SpacyNlpEngine}
It only has spacy in it, hence while trying with stanza it gives Key error

**Comment by omri374** [comment]
Hi @Subrat08,
There are some prerequisites for using Stanza within Presidio. Make sure you install both `stanza` and `spacy_stanza` packages, and download the relevant model (e.g. `stanza.downoad("en")`).

The `model_name` in Stanza is identical to the language (see [Stanza's available models here](https://stanfordnlp.github.io/stanza/available_models.html#available-ner-models) and a description on how to download [here](https://stanfordnlp.github.io/stanza/download_models.html)).

Here's a working example:
```python
import stanza
from presidio_analyzer import AnalyzerEngine, RecognizerRegistry
from presidio_analyzer.nlp_engine import NlpEngineProvider

stanza.download("en") # One time download

configuration = { "nlp_engine_name": "stanza", "models": [{"lang_code": "en", "model_name": "en"}] }

provider = NlpEngineProvider(nlp_configuration=configuration)
nlp_engine_with_stanza = provider.create_engine()

analyzer = AnalyzerEngine(nlp_engine=nlp_engine_with_stanza)

# Analyze
results= analyzer.analyze(text="My name is Raphael", language="en", return_decision_process=True)
print(results)
print(results[0].analysis_explanation)
```

> [type: PERSON, start: 11, end: 18, score: 0.85]
> {'recognizer': 'StanzaRecognizer', 'pattern_name': None, 'pattern': None, 'original_score': 0.85, 'score': 0.85, 'textual_explanation': "Identified as PERSON by Stanza's Named Entity Recognition", 'score_context_improvement': 0, 'supportive_context_word': '', 'validation_result': None}

**Comment by Subrat08** [comment]
Thanks for the quick reply. I have tried that but unfortunately I am getting same error.

**Comment by omri374** [comment]
Have you run `pip install stanza spacy_stanza`?

**Comment by Subrat08** [comment]
Yes, here is the screenshot
![image](https://user-images.githubusercontent.com/11193040/148204918-c1b7e719-8060-444f-a81a-645067946f61.png)

**Comment by omri374** [comment]
Could you please share your environment details? os, python version, `pip freeze` etc?

**Comment by Subrat08** [comment]
OS: Windows 10 21H1
Python: 3.6.8
[requirements.txt](https://github.com/microsoft/presidio/files/7814398/requirements.txt)

**Comment by omri374** [comment]
I think you're missing `spacy_stanza`

**Comment by Subrat08** [comment]
I installed that but still it gives me the same error.

**Comment by Subrat08** [comment]
Thanks, it worked now! Followed these steps
1. Uninstalled and re-installed stanza and spacy-stanza  packages. 
2. Restarted the kernel
3.  Re-ran the code provided by you
