### ISSUE TITLE
Datetime incorrectly detected as LOCATION

### ISSUE THREAD

**Issue by CaptainDaVinci** [microsoft/presidio#819]
**Describe the bug**
A date time text field is incorrectly analyzed as LOCATION entitiy.

**To Reproduce**
1. Install the analyzer package
2. Download the spacy en_core_web_lg model
3. Run: 
```
analyzer_engine.analyze('Time 2021-03-01 07:16:59.605000', entities=['EMAIL_ADDRESS', 'PERSON', 'IP_ADDRESS', 'LOCATION', 'NRP'], language='en')
```

Output:
```
[type: LOCATION, start: 16, end: 31, score: 0.85]
```

**Expected behavior**
No result based on the entities passed.

**Comment by omri374** [comment]
Hi @CaptainDaVinci, Presidio relies on spaCy Named Entity Recognition models when it comes to detecting locations and dates/times (although there's also a regex-based date time recognizer). 

These models sometimes have errors. [Here's are a few ideas on how to improve the accuracy of a Presidio instance](https://github.com/microsoft/presidio/discussions/767).

Specifically, you can customize your Presidio instance to be able to detect dates using other mechanisms. Here I'm using a 3rd party python package (`datefinder`) to recognizer dates and times in text: 

```python
import datefinder # pip install datefinder
from presidio_analyzer import RecognizerResult


text = "Time 2021-03-01 07:16:59.605000"
matches = datefinder.find_dates(text, index=True)

results = []
for match in matches:
    results.append(RecognizerResult(entity_type="DATE_TIME", start = match[1][0], end=match[1][1], score=0.9))

results
```
>  [type: DATE_TIME, start: 0, end: 31, score: 0.9]

This example could be turned into a custom `EntityRecognizer` and added to the list of recognizer Presidio runs. See [docs here](https://microsoft.github.io/presidio/analyzer/adding_recognizers/#creating-a-new-entityrecognizer-in-code).

Another potential customization is to ignore specific entities that are extracted out of spaCy. In this code snippet we ignore the LOCATION entity that gets returned by spaCy, in case it is causing false positives:

```python
from presidio_analyzer import AnalyzerEngine
from presidio_analyzer.predefined_recognizers import SpacyRecognizer

SpacyRecognizer.ENTITIES.remove("LOCATION")

analyzer_engine = AnalyzerEngine()
analyzer_engine.analyze('Time 2021-03-01 07:16:59.605000', entities=['EMAIL_ADDRESS', 'PERSON', 'IP_ADDRESS', 'LOCATION', 'DATE_TIME', 'NRP'], language='en')
```
> [type: DATE_TIME, start: 5, end: 15, score: 0.85]

So although "LOCATION" is sent to Presidio as a requested entity, it doesn't have any recognizer that can recognize it, and it isn't returned.
