### ISSUE TITLE
Usage question - mysql

### ISSUE THREAD

**Issue by elusivenode** [microsoft/presidio#821]
What is the general usage pattern to use Presidio to anonymise data in a database? I can’t see any discussion of this is the docs.

**Comment by omri374** [comment]
Hi @elusivenode, there are some samples / discussions on this. For example:
1. Using Presidio in batch mode: https://microsoft.github.io/presidio/samples/python/batch_processing/
2. Using Azure Data Factory to create an ETL pipeline with Presidio: https://microsoft.github.io/presidio/samples/deployments/data-factory/presidio-data-factory-template-gallery-http/

Hope this helps. Would be happy to discuss this in more details if needed.

**Comment by elusivenode** [comment]
Thank you Omri. Appreciate your efforts.

**Comment by omri374** [comment]
With pleasure. Closing the issue for now, please re-open if needed.
