### ISSUE TITLE
Replace datetime with year

### ISSUE THREAD

**Issue by PabloBotas** [microsoft/presidio#826]
Hi!
I have been looking for the functionality to replace datetime with year or month/year information. This would be very useful to reduce the amount of information while keeping it informative. Is it available?

Thanks!

**Comment by omri374** [comment]
Hi @PabloBotas, do you mean to anonymize dates by replacing the full date with only the year or month?
If yes, this capability is not currently available, but could be implemented as an additional anonymization operator. Note that dates and times could be detected in many different formats, so such operator would have to handle different types of dates.

In [this example](https://microsoft.github.io/presidio/samples/python/example_custom_lambda_anonymizer/), we're creating a custom operator using a lambda function. In your case the lambda function could get the datetime text, and return only the year/month.

This would be a great new capability, so if you're interested in making a contribution, we'd be happy to help with that.

**Comment by PabloBotas** [comment]
Hi,
Sadly I think I don't have the bandwidth to tackle this problem, although it would definitely be interesting. Does the NER annotating datetime have any explicit knowledge of the expected format? I mean, is it rule-based or is it a more *modern* classifier?

**Comment by omri374** [comment]
In the case of DATE_TIME, it's both. The default settings uses both regex and a NER model
