### ISSUE TITLE
Mismatched scores returned from AnalyzerEngine

### ISSUE THREAD

**Issue by liaeh** [microsoft/presidio#847]
**Describe the bug**
For some inputs, the results returned by the analyzer have unexpected scores of 1.0 under the attribute , despite no context words being present in the input at all. These scores are different than the scores listed `analysis_explanation` when `return_decision_process = True` (these are the expected scores).

**To Reproduce**

An example:
```
from presidio_analyzer import AnalyzerEngine
analyzer = AnalyzerEngine()
text = 'You can call my phone 907-882-3534'
results = analyzer.analyze(text , language='en', return_decision_process = True)
print(results)
> [type: UK_NHS, start: 22, end: 34, score: 1.0, type: PHONE_NUMBER, start: 22, end: 34, score: 0.75]
# UK_NHS has a score of 1.0 despite no context words in input, and default pattern score = 0.5

print([i.score for i in results])
> [1.0***, 0.75]

print([i.analysis_explanation.score for i in results])
> [0.5**, 0.75]
# this is the expected score for UK_NHS entity
```

**Expected behavior**
Scores should match for both attributes. 

**Additional context**
```
presidio-analyzer==2.2.27
presidio-anonymizer==2.2.27
```

**Comment by omri374** [comment]
Thanks @liaeh, we're looking into it.

**Comment by omri374** [comment]
Hi @liaeh, the UK_NHS_NUMBER is validated using checksum: https://github.com/microsoft/presidio/blob/f53e6c057556cf9e48180a654c26f74304f81602/presidio-analyzer/presidio_analyzer/predefined_recognizers/uk_nhs_recognizer.py#L54

Therefore, the score of 1.0 is the correct one. What's incorrect is the analysis explanation score, which should also equal 1.0. I'll soon create a PR to fix it.

**Comment by liaeh** [comment]
Hi @omri374, thanks for looking into this! The boosting of a score to 1.0 if validated is confusing to me, I haven't seen this [mentioned in the docs ](https://microsoft.github.io/presidio/api/analyzer_python/#presidio_analyzer.pattern_recognizer.PatternRecognizer.validate_result)(correct me if I'm not wrong). This behavior should be better documented. From how it is documented now, I would expect patterns with `validate_result` to require `validate_result=True` to just keep the match in `List[RecognizerResults]` without modifying the score.

**Comment by omri374** [comment]
Hi @liaeh, there's indeed a gap in the docs around this. If you're interested in creating a PR to update the docstrings or the docs themselves, that would be super. If not, we'll try to address it in the future.

**Comment by omri374** [comment]
Since a checksum is a pretty strong guarantee of a number being a specific entity, we assign the confidence to 1.0. Having said that it could be that a phone number accidentally passes a checksum for another entity. One thing we can do is to have the confidence value more configurable.

**Comment by liaeh** [comment]
@omri374 sure, I'll create a PR to update the docs.

I agree it would be nice to have the confidence more configurable. In this scenario, since the result validation boosts the score right away to the MAX_SCORE, then there's no more room for context to be taken into consideration.
