### ISSUE TITLE
Different output for same text in presidio demo website and Python API

### ISSUE THREAD

**Issue by mugenShouren** [microsoft/presidio#862]
**Describe the bug**
I am getting different PII output for same text in presidio-demo website and Python API. As shown below Ontario is not detected in Python API. 

**To Reproduce**
Demo-Website: https://presidio-demo.azurewebsites.net/

Text: 
""" 
AD01 Satellite station
AD02 TORONTO, ONTARIO
AD03 M5R 1X6
AD04 CANADA
"""

**Demo-website Output**

LOCATION | 0.85 | TORONTO | 28:35
LOCATION | 0.85 | ONTARIO | 37:44
LOCATION | 0.85 | CANADA | 63:69

**Python API Output**

type: LOCATION, start: 31, end: 38, score: 0.85, entity: TORONTO
type: LOCATION, start: 66, end: 72, score: 0.85, entity: CANADA 

**Python API version**
presidio-analyzer                    2.2.27
presidio-anonymizer               2.2.27

**Installation CMDs ran***
pip install presidio_analyzer
pip install presidio_anonymizer
python -m spacy download en_core_web_lg

**Comment by mugenShouren** [comment]
```
from presidio_analyzer import AnalyzerEngine
analyzer = AnalyzerEngine()
results = analyzer.analyze(text=test_text,
                           entities=["LOCATION","PERSON"],
                           language='en')
```
Above python code is used for detecting the same.

**Comment by omri374** [comment]
Hi @mugenShouren. It could be that the demo website uses a different spaCy version or spaCy model version because it was deployed some time ago. Other than that, the demo website uses the default [presidio-analyzer container](https://hub.docker.com/_/microsoft-presidio-analyzer).

**Comment by mugenShouren** [comment]
@omri374 but the accuracy is very bad. I am getting **_40% more false positives and 20% more false negatives when using python SDK_** over the demo website. Now I am not sure how a newer version got this worse. I was planning to use it for the development of a project but now with these accuracies, I might not be able to. I also tried older releases of python SDK, but they were all giving the same FPs & FNs. 

> Can anyone identify the configurations or version of Python SDK on the demo website in the backend???

**Comment by omri374** [comment]
Hi @mugenShouren, the demo website uses the configuration defined in the analyzer [Pipfile.lock](https://github.com/microsoft/presidio/blob/main/presidio-analyzer/Pipfile.lock) file. If you use `pipenv` and install from this pipfile.lock, you should get the exact same configuration that the demo website has. More on setting up `pipenv` could be found [on Presidio's docs here](https://microsoft.github.io/presidio/development/#setting-up-pipenv).

Specifically, it uses `spacy==3.2.1` and [this en_core_web_lg model](https://github.com/explosion/spacy-models/releases/download/en_core_web_lg-3.2.0/en_core_web_lg-3.2.0-py3-none-any.whl).

**Comment by mugenShouren** [comment]
Hi @omri374 from your earlier comment I though of deprecating the spacy & it's model and trying the same. I tested my data with `spacy==3.2.0`  & `en_core_web_lg-3.2.0` [model](https://github.com/explosion/spacy-models/releases/tag/en_core_web_lg-3.2.0) and it is now giving me the same outputs as the demo website. The latest release of Spacy caused this issue. 
Thanks a lot @omri374 for your help!!

**Comment by omri374** [comment]
Great. Could be an issue for `spacy` though, if there's something that affects the model accuracy.
