### ISSUE TITLE
Transformers based NLP engine

### ISSUE THREAD

**Issue by omri374** [microsoft/presidio#887]
## Background
Presidio currently leverages spaCy for NER. It is possible to [switch to a stanza model](https://microsoft.github.io/presidio/tutorial/05_languages/), or to create additional NER recognizers using 3rd party packages such as Flair and Transformers (see examples [here](https://github.com/microsoft/presidio/blob/main/docs/samples/python/flair_recognizer.py) and [here](https://github.com/microsoft/presidio/blob/main/docs/samples/python/transformers_recognizer.py)).
However, it is not possible to completely replace a spacy/stanza model with a transformers model, except for when using the `trf` models coming from spaCy, such as `en_core_web_trf`. 

## Proposed solution

Create a new type of `NlpEngine` called `TransformersNlpEngine` which runs a transformers NER model instead of spaCy's NER. The user could decide which transformers model to plug in (either pretrained or custom). 

Since Presidio leverages spaCy's pipeline for different features such as lemmas and tokens, which aren't supported by a transformers NER model, we propose to create a [spaCy pipeline](https://spacy.io/usage/processing-pipelines) without NER, and add a new component which runs a transformers NER model.

Instead of this pipeline which we currently have:
![image](https://user-images.githubusercontent.com/3776619/176368408-d513a6d7-7f0e-4ffa-b4b6-7a598f30025f.png)

We would have this pipeline:
![image](https://user-images.githubusercontent.com/3776619/176369943-94080c2d-1442-49c7-93cf-41db08fa4a82.png)

This pipeline would not be trainable, but one can train a transformers model and inject it into this pipeline

**Comment by matthewchung74** [comment]
Hi @erann1987 , is there any documentation on how to add a transformer model, as mentioned here? https://github.com/microsoft/presidio/blob/37f74e8e880cb1bdf3f5224a05eaa9b63df02d31/presidio-analyzer/presidio_analyzer/nlp_engine/transformers_nlp_engine.py#L89
