### ISSUE TITLE
ImportError: cannot import name 'BatchAnalyzerEngine' from 'presidio_analyzer'

### ISSUE THREAD

**Issue by ZhangzihanGit** [microsoft/presidio#893]
**Describe the bug**
When I follow the batch processing example notebook [here](https://github.com/microsoft/presidio/blob/main/docs/samples/python/batch_processing.ipynb), it raises an import error: 
`ImportError: cannot import name 'BatchAnalyzerEngine' from 'presidio_analyzer'`

**To Reproduce**
1. Go to the notebook https://github.com/microsoft/presidio/blob/main/docs/samples/python/batch_processing.ipynb
2. Setup the environment

```
python==3.8
pandas==1.4.3
spacy==3.3.1
presidio-analyzer==2.2.28
presidio-anonymizer==2.2.28
```

4. Execute the first cell

**Expected behavior**
It should import `BatchAnalyzerEngine` correctly.

**Comment by omri374** [comment]
Thanks for the input @ZhangzihanGit. This is because the `BatchAnalyzerEngine` was not released to PyPI yet. We will soon create a release.

**Comment by omri374** [comment]
Version 2.2.29 was released yesterday. Could you please check if the problem persists?

**Comment by ZhangzihanGit** [comment]
Thanks @omri374! it's working now
