### ISSUE TITLE
Recommended Server configuration

### ISSUE THREAD

**Issue by flyfei-cmd** [microsoft/presidio#898]
We are using Presidio to recognize  PII,  
Firstly we choose a server which configuration is: 15GB RAM，20 vCPU, no GPU， In this server, we use Stanza NLP model to recognize PII in articles with 7000 or 8000 words。
And the result shows we need almost 11 seconds to finish recognizing one article
This is too slow for us.  

And then we choose a server which configuration is 125GB RAM, 40vCPU，with GPU(Tesla V100). In this server, we do the same tests as above, And the result shows we need almost 3 seconds to finish recognizing one article.

This is also not fast enough for us.
Do you have some recommended server configuration for using Presidio?  Test code is like below:

```
def func():
    configuration = {'nlp_engine_name': 'stanza', 'models': [{'lang_code': 'zh', 'model_name': 'zh'}]}
    engine = NlpEngineProvider(nlp_configuration=configuration).create_engine()
    analyzer = AnalyzerEngine(nlp_engine=engine, supported_languages=['zh'])
    for _ in range(100):
        for _ in range(100):
            print('start run Presidio')
            start_time = time.time()
            analyzer.analyze(text, 'zh')
            print(f'End of running {time.time()-start_time}')
```

**Comment by flyfei-cmd** [comment]
hi @omri374 , much thanks for your reply.
I am trying to use BatchAnalyzerEngine,  But the results shows that the codes do not run in parallel, the time cost doubled.
I have tested spaCy and stanza, both nlp model showed the same result. The code is like below:

```
input_list = [text1, text2]
# text1 is the same text as text2
def func():
    configuration = {'nlp_engine_name': 'spacy', 'models': [{'lang_code': 'zh', 'model_name': 'zh_core_web_md'}]}
    engine = NlpEngineProvider(nlp_configuration=configuration).create_engine()
    analyzer = AnalyzerEngine(nlp_engine=engine, supported_languages=['zh'])
    batch_analyzer_engine = BatchAnalyzerEngine(analyzer_engine=analyzer)
    # text = 'Any text information used for testing. The longer the text message, the better'
    for _ in range(100):
        for _ in range(100):
            print('start to run: ')
            start_time = time.time()
            #analyzer.analyze(text, 'zh')
            batch_analyzer_engine.analyze_iterator(texts=input_list, language="zh")
            print(f'end of run{time.time()-start_time}')
        print(f'Current Time：{datetime.now()}')
        print(u'Used Memory：%.4f GB' % (psutil.Process(os.getpid()).memory_info().rss / 1024 / 1024 / 1024))
```
If I want to run the codes in parallel to use BatchAnalyzerEngine,  Is there something wrong in my codes?

**Comment by omri374** [comment]
Hi @flyfei-cmd, did you manage to get an improvement using `BatchAnalyzerEngine`?

**Comment by omri374** [comment]
closing the issue, feel free to reopen if needed

**Comment by Ogers-Ruda** [comment]
@omri374 I gave BatchAnalyzerEngine a shot but unfortunately didn’t see any speed-up. I experimented with several batch sizes (small to quite large) and the throughput stayed roughly the same. Also, since I’m running Presidio with transformer on a single GPU, bumping multiprocess beyond 1 consistently throws CUDA-related errors. Any other tuning tips would be appreciated.

**Comment by RonShakutai** [comment]
Hi @Ogers-Ruda , 
Thanks for reaching out, and thanks to @omri374 for sharing.

We optimized Presidio + transformers on GPU by making sure that **spaCy itself** runs on CUDA, so the tokenizer and alignment steps stay on the GPU and avoid costly CPU⇄GPU transfers.

```python
import spacy
spacy.require_gpu()          # call this before loading any pipeline
```

You can find more details in the spaCy documentation: https://spacy.io/api/top-level#spacy.require_gpu
I recommend giving this a try, please let us know if it helps improve the performance.

**Comment by Ogers-Ruda** [comment]
Hi @ShakutaiGit ,

Thank you for the reply. I've been running spacy on CUDA the way you showed, and I have verified that the tokenizer and alignment do indeed stay on GPU. This is the reason why I tried BatchAnalyzerEngine as I was getting no more improvements with other ways.
