### ISSUE TITLE
Load Spacy model in Pyspark

### ISSUE THREAD

**Issue by julianmscope** [microsoft/presidio#899]
**Describe the bug**
The problem is that when I want to load a model and use it in python everything works correctly. But when I want to use it in pyspark with the following code it does not work, it is because it is not loaded in the workers.

**To Reproduce**
```
class LoadedSpacyNlpEngine(SpacyNlpEngine):
    def __init__(self, loaded_spacy_model):
        self.nlp = {"es": loaded_spacy_model}

nlp = spacy.load("es_core_news_md")
loaded_nlp_engine = LoadedSpacyNlpEngine(loaded_spacy_model=nlp)

analyzer = AnalyzerEngine(
    nlp_engine=loaded_nlp_engine,
    supported_languages=["es"])

anonymizer = AnonymizerEngine()
broadcasted_analyzer = spark.sparkContext.broadcast(analyzer)
broadcasted_anonymizer = spark.sparkContext.broadcast(anonymizer)

def anonymize_text(text: str) -> str:
    analyzer = broadcasted_analyzer.value
    anonymizer = broadcasted_anonymizer.value
    analyzer_results = analyzer.analyze(text=text, language="es")
    anonymized_results = anonymizer.anonymize(
        text=text,
        analyzer_results=analyzer_results,
        operators={"DEFAULT": OperatorConfig("replace", {"new_value": "<ANONYMIZED>"})},
    )
    return anonymized_results.text

def anonymize_series(s: pd.Series) -> pd.Series:
    return s.apply(anonymize_text)

# define a the function as pandas UDF
anonymize = sf.pandas_udf(anonymize_series, returnType=StringType())

df.withColumn(
    "presidio", anonymize(sf.col("content_final"))
)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/109996345/180886348-94dc63c9-ddcc-46f3-bd48-42536ad7b191.png)

**Additional context**
When I use it directly without loading the model from spacy it works, the problem is when I use the function LoadedSpacyNlpEngine to load the model

**Comment by omri374** [comment]
Hi @julianmscope 
Not a spark expert, but it seems like an issue with pickling the object and passing it to workers. 
Maybe broadcasting `loaded_nlp_engine` would work? or looking into using `cloudpickle` (even just importing it). Please LMK if this helps.

**Comment by omri374** [comment]
Closing the issue, feel free to reopen
