### ISSUE TITLE
EntityRecognizer ImportError: cannot import name dataclasses

### ISSUE THREAD

**Issue by JGillette71** [microsoft/presidio#900]
**Describe the bug**
Receiving “ImportError: cannot import name dataclasses” upon execution of “from presidio_analyzer.entity_recognizer import EntityRecognizer” 
Appears to be coming from “init pydantic.__init__()” under the hood. 
Researched known issues with Presidio and Pydantic to no avail… 
I'm only seeing this issue in DataBricks -- code works fine on Colab. See additional context. 

**To Reproduce**
Databricks Python Notebook 
python --version 3.7.5
V_ENV=/databricks/python3

```
`
# analyzer for detection
! pip install presidio-analyzer
# anonymizer to perform masking
! pip install presidio-anonymizer
# language context for model
! python -m spacy download en_core_web_trf

from presidio_analyzer import AnalyzerEngine, PatternRecognizer, EntityRecognizer, Pattern
from presidio_anonymizer import AnonymizerEngine 
from presidio_anonymizer.entities import RecognizerResu1t, OperatorConfig

def pseudonymize_string(dataframe, column, row):
  #  simply anonymize one element in dataframe while preserving subject as entity 
 
  if type(dataframe[column][row]) ==str:
    text = dataframe[column][row] 
    
    # Set up the engine, loads the NLP module (spaCy model by default)
    analyzer = AnalyzerEngine()
    
    # add subject recognition
    subject_name = dataframe['f_name'][row] + ' ' + dataframe['1_name'][row] 
    subject_recognizer = PatternRecognizer(supported_entity='SUBJECT', deny_list=[subject_name])
    analyzer.registry.add_recognizer(subject_recognizer)
    
    # Call analyzer to get results
    # supported entity types --> https://microsoft.github.io/presidio/supported_entities/
    results = analyzer.analyze(text=text, entities=['PERSON','LOCATION','SUBJECT'], language='en') 
    
    # Analyzer results are passed to the AnonymizerEngine for 
    anonymizer = AnonymizerEngine()
    
    # call anonymizer 
    anonymized_text = anonymizer.anonymize(text=text, analyzer_results=results)
    
    # assign fake name to subject - don't want this calling multiple times in anonymizer
    subject_fake = Faker().name()
    
    # populate pseudonyms over identified entities 
    pseudonym_text = anonymizer.anonymize(text=text,
                                          analyzer_results=results,
                                          operators={'PERSON': OperatorConfig('custom', {'lambda': Faker().name()}),
                                                     'LOCATION': OperatorConfig('custom', {'lambda': Faker().city()}),
                                                     'SUBJECT': OperatorConfig('custom', {'lambda': subject_fake})})
    
    # capture results
    results_dict = {'original': text, 
                    'anonymized': anonymized_text.text,
                    'pseudonymized': pseudonym_text.text}
    return(results_dict)
  else:
    print('must provide str type element as arg')`

```
**Expected behavior**
Returns dictionary with original text, anonymized text, and masked text while maintaining entity integrity for subject identified in record. 

**Screenshots**
![image](https://user-images.githubusercontent.com/70489145/181606572-20c17e36-5258-4408-b1d2-4782e3338ada.png)
![image](https://user-images.githubusercontent.com/70489145/181606639-a9ec1850-b385-4855-b836-e3853363c3a5.png)
![image](https://user-images.githubusercontent.com/70489145/181606738-8a730f65-c109-498f-a17a-92a8516d9e62.png)
![image](https://user-images.githubusercontent.com/70489145/181606789-2d6dd829-913a-44c0-a9eb-0fa15a4e84d5.png)

**Additional context**

I am attempting to migrate this notebook from a personal colab to a organization's public databricks cluster. I've got limited visibility on the environment. Hoping someone has a fix I'm just overlooking. Thanks!

**Comment by omri374** [comment]
Hi, this seems to be an issue with spaCy. Could be an issue with how Databricks handles the spaCy objects.
