### ISSUE TITLE
Running notebook question

### ISSUE THREAD

**Issue by matthewchung74** [microsoft/presidio#903]
When running `1_Generate_data.ipynb` directly from the `notebooks` directory, I'm finding I need to shift some paths around to make it work. For example, I need to start my notebook with a 
```
%cd ..
```
such that it can reference `presidio_evaluator` since they are not in the same directory. 

The same applied do 
```
number_of_samples = 1500
cur_time = datetime.date.today().strftime("%B_%d_%Y")

raw_data_path = Path("../presidio_evaluator/data_generator/raw_data")
output_file = f"../data/generated_size_{number_of_samples}_date_{cur_time}.json"
output_conll = f"../data/generated_size_{number_of_samples}_date_{cur_time}.tsv"

templates_file_path = Path(raw_data_path, "templates.txt").resolve()
fake_name_generator_file = Path(raw_data_path, "FakeNameGenerator.com_3000.csv").resolve()

lower_case_ratio = 0.05
```

I'm not sure if there is something I am missing. Thanks and thanks for this great library.

**Comment by omri374** [comment]
Hi @matthewchung74, have you closed the issue because it is resolved?

**Comment by matthewchung74** [comment]
Hi @omri374 , thanks for responding. I closed since i was thinking I should first look at how the notebooks work within your CI. I wasn't sure if I wasn't missing something obvious.

**Comment by omri374** [comment]
We assume Jupyter is started from the root of the repo (not the notebooks folder). 
In this case it should work out of the box.
