### ISSUE TITLE
I am trying to add a new recognizer in predefined_recognizer and then register in Recognizerregistry. But unable to register it.

### ISSUE THREAD

**Issue by 5urabhi** [microsoft/presidio#904]

**Comment by omri374** [comment]
Could you please share the steps you have taken?
Generally speaking, once creating a new recognizer class, there's the dictionary of recognizers in the recognizer registry code:
https://github.com/microsoft/presidio/blob/37f74e8e880cb1bdf3f5224a05eaa9b63df02d31/presidio-analyzer/presidio_analyzer/recognizer_registry/recognizer_registry.py#L72

It might be more straightforward to add a custom recognizer ([see docs](https://microsoft.github.io/presidio/tutorial/03_rule_based/)).

**Comment by omri374** [comment]
Please see [this tutorial](https://microsoft.github.io/presidio/tutorial/03_rule_based/).
Once you have your recognizer class (assuming it's a class, and not a regex or deny-list. For those there are other tutorials, you can add it to the list of recognizers.


Example:

Say you created a new recognizer class called `NumbersRecognizer`:
```python
from presidio_analyzer import AnalyzerEngine

new_numbers_recognizer = NumbersRecognizer(supported_entities=["NUMBER"])

text = "Roberto lives in Five 10 Broad st."
analyzer = AnalyzerEngine()
analyzer.registry.add_recognizer(new_numbers_recognizer)

numbers_results = analyzer. Analyze(text=text, language="en")
print(numbers_results)
```

**Comment by 5urabhi** [comment]
It can help to register the recognizer internally . But I want to ask how can I register  a new recognizer class through user input.
Like through API we can add recognizer class through ad_hoc_recognizers but it is just for that response how can we register it internally in the recognizer_registry.
