### ISSUE TITLE
Context word is recognized as entity in Pattern Recognizer

### ISSUE THREAD

**Issue by rayliu2007** [microsoft/presidio#909]
**Describe the bug**
When using patternrecogninzer with context, if regex matches context word too, then context work itself is recognized as entity too. But it should not.

**Comment by omri374** [comment]
Not sure I understand the issue. If a regex falsely detects a word as entity, then the issue is probably with the regex. Isn't it? Is the issue that the same word isn't used as context in addition to being an entity?

**Comment by omri374** [comment]
Closing for now, please re-open if needed.
