### ISSUE TITLE
AU_ACN entity raises an exception in some cases: ValueError: invalid literal for int() with base 10: '\\n'

### ISSUE THREAD

**Issue by MichalAI21** [microsoft/presidio#910]
**Describe the bug**
When having AU_ACN entity in the list, probably the regex pattern matches texts like: `123 456\n789` as the entity. Later, the code try to validate this and to cast `\n` into an integer, which causes a ValueError. 
I would really like to get your help.

Thank you!

**To Reproduce**
Just run: `AnalyzerEngine().analyze(text="123 456\n789", language="en")`

**Expected behavior**
I would like to get the analyzer result as usual.

**Additional context**

`"Traceback (most recent call last):\n File \"/usr/local/lib/python3.9/site-packages/presidio_analyzer/analyzer_engine.py\", line 204, in analyze\n    current_results = recognizer.analyze(\n  File \"/usr/local/lib/python3.9/site-packages/presidio_analyzer/pattern_recognizer.py\", line 94, in analyze\n    pattern_result = self.__analyze_patterns(text, regex_flags)\n  File \"/usr/local/lib/python3.9/site-packages/presidio_analyzer/pattern_recognizer.py\", line 198, in __analyze_patterns\n    validation_result = self.validate_result(current_match)\n  File \"/usr/local/lib/python3.9/site-packages/presidio_analyzer/predefined_recognizers/au_acn_recognizer.py\", line 73, in validate_result\n    acn_list = [int(digit) for digit in text]\n  File \"/usr/local/lib/python3.9/site-packages/presidio_analyzer/predefined_recognizers/au_acn_recognizer.py\", line 73, in <listcomp>\n    acn_list = [int(digit) for digit in text]\nValueError: invalid literal for int() with base 10: '\\n'"`

**Comment by omri374** [comment]
Thanks for reporting. This is a bug.

If you are not interested int he `AU_ACN` entity, here's a workaround, which removes this recognizer from the list of predefined recognizers:

```python
from presidio_analyzer import AnalyzerEngine
engine = AnalyzerEngine()
recognizers = engine.registry.recognizers

# Remove AU recognizers
new_recognizers = [rec for rec in recognizers if rec.name not in ("AuTfnRecognizer", "AuAcnRecognizer")]

# Update recognizers list
engine.registry.recognizers = new_recognizers

# Test
engine.analyze(text="123 456\n789", language="en")
```

**Comment by MichalAI21** [comment]
@omri374 Thank you for the quick response and for you solution.
My temporary solution until the fix is to remove "AU_ACN" and "AU_TFN" from the entity list I pass into `analyzer.analyze()` function.

Have a great day!
Michal
