### ISSUE TITLE
Merging partial intersection with the same entity_type

### ISSUE THREAD

**Issue by ducquangkstn** [microsoft/presidio#917]
**Is your feature request related to a problem? Please describe.**
We have multiple recognizer with different approaches, 2 recognizers could be used for the same `entity_type`
Merging `Partial intersection` with the same `entity_type` would look like
```python
from presidio_analyzer import RecognizerResult

text = 'Name: Quang Nguyen Duc'
anonymizer = AnonymizerEngine()

analyzer_results = [
    RecognizerResult("NAME", start=6, end = 18, score=1), # Quang Nguyen
    RecognizerResult("NAME", start=11, end = 22, score=1),
]

anonymized_result = anonymizer.anonymize(text,analyzer_results)
print(anonymized_result.text)
```

The result is `Name: <NAME><NAME> `

**Describe the solution you'd like**
I expected `Name: <NAME>`

**Describe alternatives you've considered**

**Additional context**

**Comment by omri374** [comment]
Hi @ducquangkstn, this is a great suggestion. We will look into this, but also open to community contributions.
