### ISSUE TITLE
Issue running Presidio custom Docker image

### ISSUE THREAD

**Issue by nikhilwadhwa84** [microsoft/presidio#931]
Hi, I cloned the Presidio repo, and then ran: 
`docker-compose build`

Then I get:
`executor failed running [/bin/sh -c pip install pipenv   && pipenv sync]: exit code: 1
ERROR: Service 'presidio-analyzer' failed to build : Build failed`

In the details I see a bunch of messages like:
`#8 4.289✔ Successfully created virtual environment! 
#8 4.349 Virtualenv location: /usr/bin/presidio-analyzer/.venv
#8 4.358 Installing dependencies from Pipfile.lock (0db79c)...
#8 77.32 An error occurred while installing blis==0.7.5 --hash=sha256:730952f74adb0fa7dde9f1bc11249d5a64f3a3a9cf7dfa23b189a4b767bdf2d0 --hash=sha256:ad4af690c37a5953d3aea660ad89b636bfbb80ca1470995554670ca2143f0cb2 --hash=sha256:2339cb19594134775bda8b86f23a893828fc7e8d63f09ba9a15f30b2b16c966c --hash=sha256:cf11c233ea5c2d30683e7c9641c5dc4cd76ed0f64755ba3321dfb8db39feb316 --hash=sha256:5966ddf3bce84aa7bb09ce4ca059309602fa63280a5d5e5365bb2a294bd5a138 --hash=sha256:65ba723821cc57eb4227eb8dd05c57fff23d97f826d4325b316cd8a63aac8d6a --hash=sha256:8345bd04777557ef385e2f2d1f14a19d53b2ea9ca5fe107a2cdc50d7bafb8eb2 --hash=sha256:9eecfce3d8fce61dede7b0ae0dffa461c22072437b6cde85587db0c1aa75b450 --hash=sha256:31401da283ed42905f0fbf2f8b88ea424c6a911482426f84b5b88c54d382e4d1 --hash=sha256:5023781272e0b2868be2f92017aa6836557990f1ca5ba2af5e9f5a0acf04fd8a --hash=sha256:0c185979f8f528d634f5548b8cd84ab0366d340c27c039ad3937fab186c1c252 --hash=sha256:5812a7c04561ae7332cf730f57d9f82cbd12c5f86a5bfad66ee244e51d06266d --hash=sha256:833e01e9eaff4c01aa6e049bbc1e6acb9eca6ee513d7b35b5bf135d49705ad33 --hash=sha256:0e476931f0d5703a21c77e7f69b8ebdeeea493fc7858a86f627ac2b376a12c8d --hash=sha256:66204a19e38986645940c887498c7b5520efb5bbc6526bf1b8a58f7d3eb37da0 --hash=sha256:d9034dabce4e42e3a1a7b99cc6de430484c8c369e51556ee8d47a53c085de681! Will try again.`

This is my Docker version:
`docker --version                                                                            
Docker version 20.10.10, build b485636`

Im also on a Apple silicon MacOS. Is this a known issue?

**Comment by nikhilwadhwa84** [comment]
So upon further investigation, this has to do with the SHA checksums of the dependencies being hardcoded, as they are different for the ARM-based M1 chips. The temporary fix is to regenerate the lock file.

A good long term fix could be to have a separate lock file for ARM architectures. I could create a PR with this lock file, but it would be a good idea to examine how to pick up a different lock file based on detecting the architecture.

**Comment by omri374** [comment]
Hi @nikhilwadhwa84, having multiple lock files is difficult to maintain. Perhaps a solution would be to optionally lock the requirements within the docker image build?
