### ISSUE TITLE
How can we Analyze more than 1mb file ?

### ISSUE THREAD

**Issue by Vikash-Sinha** [microsoft/presidio#935]
we have many file more than 1mb. i'm analyze those file by sending those data into chunks. But the demerits of using chunks here is start and end postion of finding entites are wrong. its not append the results value.

**Comment by omri374** [comment]
Hi @Vikash-Sinha, similar to other NLP modules, splitting the text is sometimes necessary. In that case, re-alignment of the output is also needed. This is currently not supported by Presidio, but happy to further discuss.

**Comment by Vikash-Sinha** [comment]
Hi Omri,

First thanks for your response, but as you say that split the text and then
analyze and then re-alignment the output. In this case due to splitting we
can miss some entities. like regex entity, address entity, Phone Number
entity and many other entities.

How do we overcome this?

Thanks
Vikash Kumar

**Comment by omri374** [comment]
There are several approaches for sentence tokenization. One of them is this one: https://github.com/neurosnap/sentences, the other is spaCy's sentencizer: https://spacy.io/api/sentencizer. My suggestion would be to try out different sentence tokenization approaches and see what works best for your dataset.
