### ISSUE TITLE
Not able to run Presidio PII detection on large character length column and Large dataset using spark

### ISSUE THREAD

**Issue by prasanthgp93** [microsoft/presidio#938]
Hi Team,

We are trying to use presidio PII UDF in spark engine for a large dataset. We are trying to cover all the 24 listed Entities. Let says we have a column with more than 6 lakhs characters its taking too much time to complete. 6 lakhs length is just an example her 
As actual use case we have column character length varying from 1 lakh to below 1 million. 
How can we reduce the run time here is there any optimal way here to achieve this PII detection on large character length text or dataset.

**Note:** Job goes to hung state.

Kindly respond us with a solution to implement it in our Prod.

Below is our Code sample using spark what we try and packages we download.
we use : Apache Spark 3.2.1,Python version 3.8.10

downloaded packages
```sh
#!/bin/bash
pip install presidio-analyzer
pip install presidio-anonymizer
python -m spacy download en_core_web_lg
```

spark udf call:
```python
analyzer = AnalyzerEngine()
anonymizer = AnonymizerEngine()
broadcasted_analyzer = sc.broadcast(analyzer)
broadcasted_anonymizer = sc.broadcast(anonymizer)

def anonymize_text(text: str) -> str:
    analyzer            = broadcasted_analyzer.value
    anonymizer          = broadcasted_anonymizer.value
    analyzer_results    = analyzer.analyze(text=text,entities=entities,language="en")
    anonymized_results  = anonymizer.anonymize(
        text=text,
        analyzer_results=analyzer_results,
        operators={"DEFAULT": OperatorConfig("replace",{"new_value": "********"})},
    )
    return anonymized_results.text

def anonymize_series(s: pd.Series) -> pd.Series:
    return s.apply(anonymize_text)
  
# define a the function as pandas UDF
anonymize = pandas_udf(anonymize_series, returnType=StringType())
```
spark dataframe call:
```python
df=spark.read.load(f{s3path}).withColumn(f"{column_name}", anonymize(col(f"{column_name}")))
```

**Comment by omri374** [comment]
If I understand correctly, the issue is that every cell in the dataframe has long text (600K characters long). Correct?
In that case this is similar to #935 where sentence parsing is probably needed. Moreover, once the splitting of the text into smaller texts happens, a suggestion would be to put each small text in a row of its own, and have spark handle parallelism.

**Comment by prasanthgp93** [comment]
[omri374](https://github.com/omri374)

Thanks for the response.

To Rephrase the question more in detail 
Use case is like we have a table which are reading it records spark dataframe the table has  column name called 'description'.
where in this column for each record we will have more number of characters so said it will range from 1 lakhs to 2 8 lakhs range. Since we are using the UDF call as mentioned in above sample each record will be processed inside the udf.

Our job goes into hanging stores state somethings we think its because of long text length.

we thought initially its due to en_core_web_lg
So we tried using en_core_web_trf model ran again as well but still it looks same hanging issue is repeated.

Looking forward for your support here.

**Comment by omri374** [comment]
Thanks for the clarification. 
My suggestion would be to split the text, and create more rows. So if you have 1000 rows each with 100K long texts, turn it into a 100000 rows with 1k long texts. Once this is done, you can merge the text back to its original structure.

**Comment by prasanthgp93** [comment]
[omri374](https://github.com/omri374)

Thanks for the suggestion do you have any code sample to add this logic into below presidio UDF code.
It would be very much help helpful if u give us code added  as suggested.

**Pyspark Presidio UDF :**

analyzer = AnalyzerEngine()
anonymizer = AnonymizerEngine()
broadcasted_analyzer = sc.broadcast(analyzer)
broadcasted_anonymizer = sc.broadcast(anonymizer)

def anonymize_text(text: str) -> str:
    analyzer            = broadcasted_analyzer.value
    anonymizer          = broadcasted_anonymizer.value
    analyzer_results    = analyzer.analyze(text=text,entities=entities,language="en")
    anonymized_results  = anonymizer.anonymize(
        text=text,
        analyzer_results=analyzer_results,
        operators={"DEFAULT": OperatorConfig("replace",{"new_value": "********"})},
    )
    return anonymized_results.text

def anonymize_series(s: pd.Series) -> pd.Series:
    return s.apply(anonymize_text)
  
# define a the function as pandas UDF
anonymize = pandas_udf(anonymize_series, returnType=StringType())

**Comment by prasanthgp93** [comment]
Also it looks like Job are going to Hung state for a long time while processing last few tasks in spark.

Is this expected behaviour of Presidio UDF

**Comment by prasanthgp93** [comment]
[omri374](https://github.com/omri374)
Please can u you update on the above request

**Comment by omri374** [comment]
Hi @prasanthgp93. This is more of a Spark issue than a Presidio issue. I assume (but not sure) that this hangs because of the length of the text. See this comment https://github.com/microsoft/presidio/issues/935#issuecomment-1284997900 with some ideas on how to split the text into chunks.

**Comment by prasanthgp93** [comment]
Hi [omri374](https://github.com/omri374),

We are using en_core_web_lg spacy model.
Also, we trying to pass a language name in below python UDF call.
analyzer_results = analyzer.analyze(text=text,entities=entities,language="en")

Our records has multi language texts , Not sure why still multi language texts was getting hashed.
Though we are using english model and also we are passing language filter to Analyser engine.

Can you explain us this.
we tried below suggestion still other languages text are getting hashed.
https://microsoft.github.io/presidio/analyzer/languages/

Please let us how to process only one language text PII hashing through Analyser.

**Comment by omri374** [comment]
Hi, if you know the language for each request a priori, you could load multiple NER models into Presidio, e.g., one for each language.

**Comment by prasanthgp93** [comment]
[omri374](https://github.com/omri374) Please update on above.

Just want to know do except english for other foreign languages. Do we want to write our own recogniser logics etc or its already available in presidio.

Current presidio model in git support only English language PII detection ? right?

**Comment by prasanthgp93** [comment]
[omri374](https://github.com/omri374)

i'm trying to generate a ".whl" file for presidio_analyzer using pycharm tool. when i tried importing it in my databricks note book i'm getting the below error.
 
**from presidio_analyzer import AnalyzerEngine**

Error:
cannot import name 'AnalyzerEngine' from partially initialized module 'presidio_analyzer' (most likely due to a circular import) (/local_disk0/.ephemeral_nfs/envs/pythonEnv-e8ccd353-c21d-489f-82f9-b2f4a6fcff09/lib/python3.9/site-packages/presidio_analyzer/__init__.py)

**Comment by omri374** [comment]
@praaanthgp93 how are you generating the wheel file? It seems that the wheel file itself isn't built correctly. Is it working locally (not in Databricks)?

**Comment by prasanthgp93** [comment]
Thanks for the reply here. https://github.com/omri374

I just downloaded your zip file extracted it into Pycharm. Ran analyzer_engine.py.
Please check attachment for the same it ran below message.

Zip file url : https://github.com/microsoft/presidio/archive/refs/heads/main.zip

**/usr/bin/python3 /Users/pgunasekaran/Downloads/presidio-main/presidio-analyzer/presidio_analyzer/analyzer_engine.py 
Process finished with exit code 0**

**Quick Question:** 
Do we have any Enterprise or Paid version for presidio/ spark technical team to collaborate into and implement this PII model in our organisation production environment. 

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/116293292/202844493-254c78e1-fbe2-4f83-8ddc-9b2bcc748ad7.png">

**Comment by omri374** [comment]
Please reach out to presidio@microsoft.com and we can take it from there.
