### ISSUE TITLE
Inaccurate scanning results

### ISSUE THREAD

**Issue by Temimal** [microsoft/presidio#944]
The following contents are my scan result, it is not accurate.

LOCATION +13:00
NRP +13:00
PERSON ConfigManager.cpp:196
LOCATION win_err=2
PHONE_NUMBER 364596
PHONE_NUMBER 1667470478
PHONE_NUMBER 089758
PHONE_NUMBER 089795
PHONE_NUMBER 0.237115
PHONE_NUMBER 364822
PHONE_NUMBER 382473
PHONE_NUMBER 1667470479
PHONE_NUMBER 384997
PHONE_NUMBER 388439
PHONE_NUMBER 01.696170
PHONE_NUMBER 01.696359
PHONE_NUMBER 02.711273
PHONE_NUMBER 02.711484
PHONE_NUMBER 03.728702
PHONE_NUMBER 03.728901
PHONE_NUMBER 04.763054

**Comment by omri374** [comment]
Hi @Temimal please see this https://github.com/microsoft/presidio/discussions/767#discussion-3567223
