### ISSUE TITLE
org.apache.spark.api.python.PythonException: 'ValueError: Did not find word ' ' in the list of tokens although it is expected to be found'

### ISSUE THREAD

**Issue by prasanthgp93** [microsoft/presidio#945]
We are running Presidio using spark but though we are replacing all unicode and new line in text using below regex we are getting Value Error error from the job. Please help us on this and let us know the solution to fix this.

"'ValueError: Did not find word ' ' in the list of tokens although it is expected to be found'"

**Regex used to replace unicode and other space character.**

re.sub(r'\t|\u00A0|\u1680|\u2000|\u2001|\u2002|\u2003|\u2004|\u2005|\u2006|\u2007|\u2008|\u2009|\u200A|\u202F|\u205F|\u3000|\n',' ',str(text))

Please reply us on this.

**Comment by prasanthgp93** [comment]
Kindly give us a reply team.

**Comment by omri374** [comment]
Could you please create a reproducible example? It's difficult to say where the issue is.

**Comment by prasanthgp93** [comment]
[omri374](https://github.com/omri374)

Could please let us know which entity type in below list will take more time to detect or have more of complex pattern match.
since we are implementing  presidio on a larger data(GB size) in order to achieve throughput time. We are planning to limit the entity list as per complexity & its processing time.

**List of Entities**
https://microsoft.github.io/presidio/supported_entities/

**Comment by omri374** [comment]
Hi, the NER models (Spacy or others) are the usual suspects, and the phone-number recognizer which compares each text to a large set of formats is another. Best thing to do would be to run a profiler. 
On the spaCy side you could consider using a smaller model (e.g. `en_core_web_sm` which might be less accurate but faster), and for the phone numbers you could configure it to look up phone numbers belonging to less countries.

**Comment by prasanthgp93** [comment]
Thanks https://github.com/omri374 do we have any other such PII category. Shall we consider IBAN code in the complex list.

**Comment by omri374** [comment]
Consider IBAN as a recognizer that takes longer than others? Could be. Do you have a list of entities you are expected to have in your dataset?

**Comment by prasanthgp93** [comment]
[omri374](https://github.com/omri374)

Since our spark run are taking time. So we are trying to reduce the entities to get some less run time.
so we are looking at least for some basic hashing to happen in our dataset.

May be we can implement only Numeric PII entities alone for multiple languages.

{'CREDIT_CARD','EMAIL_ADDRESS','PHONE_NUMBER','PASSPORT','SSN','DRIVER_LICENSE/MEDICAL','BANK_NUMBER', 'IP_ADDRESSS','ITIN'}
Its good if we add some more simple entities into above list too.
