### ISSUE TITLE
analyzer.registry.remove_recognizer() does not remove the recognizer from registry.

### ISSUE THREAD

**Issue by apethree** [microsoft/presidio#950]
**Describe the bug**
analyzer.registry.remove_recognizer(...) does not remove the recognizer from the registry. However the analyzer.registry.add_recognizer(...) is working as intended.

**To Reproduce**
1. Create a new analyzer
2. Add a custom recognizer()
3. Remove the recognizer()
4. You will see that the recognizer that you tried to remove is still showing up.

**Expected behavior**
Removed recognizer should not show up() in  analysis

**Additional context**
```
zip_context_recognizer = ContextBasedRecognizer(supported_entities = ["ZIP"],
                                                context=["zipcode", "zip", "zip code", "zip_code"])

analyzer = AnalyzerEngine()
analyzer.registry.add_recognizer(zip_context_recognizer)
analyzer.registry.remove_recognizer(zip_context_recognizer)
analyzer.analyze(text="Address 515 main st, California and postal code 78731",language="en",context=["zip_code"])```

Result:
```
[type: ZIP, start: 0, end: 53, score: 1.0,
 type: LOCATION, start: 21, end: 31, score: 0.85]
```
The result should not have showed ZIP as that recognizer has been removed.


Full code for testing:
```
from typing import List, Optional
from presidio_analyzer import AnalyzerEngine, EntityRecognizer, RecognizerResult, AnalysisExplanation
from presidio_analyzer.nlp_engine import NlpArtifacts

class ContextBasedRecognizer(EntityRecognizer):
    
    def enhance_using_context(
        self,
        text: str,
        raw_recognizer_results: List[RecognizerResult],
        other_raw_recognizer_results: List[RecognizerResult],
        nlp_artifacts: NlpArtifacts,
        context: Optional[List[str]] = None,
    ) -> List[RecognizerResult]:
            if not context or not self.context:
                return []

            for context_term in context:
                if context_term in self.context:
                    return [RecognizerResult(entity_type=self.supported_entities[0],
                                            start=0, 
                                            end=len(text), score=1.0,
                                            analysis_explanation=self._build_explanation(score=1.0)
                                          )]
            return []
    
    
    def _build_explanation(
        self,
        score: float
    ) -> AnalysisExplanation:
        explanation = AnalysisExplanation(
            recognizer=self.name,
            original_score=score,
            pattern_name="Context",
            pattern=None,
            validation_result=True,
        )
        return explanation

```zip_context_recognizer = ContextBasedRecognizer(supported_entities = ["ZIP"] , context=["zipcode", "zip", "zip code", "zip_code"])

analyzer = AnalyzerEngine()
analyzer.registry.add_recognizer(zip_context_recognizer)
analyzer.registry.remove_recognizer(zip_context_recognizer)
analyzer.analyze(text="Address 515 main st, California and postal code 78731",language="en",context=["zip_code"])

```

**Comment by omri374** [comment]
Hi @apethree
the `remove_recognizer` method accepts a recognizer name as string, not the recognizer object. Therefore, the right way to use it would be to name the recognizer, and then use its name to call the `remove_recognizer` method.

However, this could be a potential improvement to accept either a string or a recognizer object. Feel free to suggest a PR if you're interested to contribute.

**Comment by apethree** [comment]
Thanks for pointing that out. For anyone else reading this you have to provide name explicitly otherwise a default named is added which is like: "ContextBasedRecognizer". Add it like this:

```
zip_context_recognizer = ContextBasedRecognizer(name="spaceship",supported_entities = ["ZIP"],
                                                context=["zipcode", "zip", "zip code", "zip_code"])

```

Don't do this:
```
zip_context_recognizer = ContextBasedRecognizer(supported_entities = ["ZIP"],
                                                context=["zipcode", "zip", "zip code", "zip_code"])
```

I would love to add a PR but I think it will break on default names as there can be multiple objects with same name, I am not feeling confident on how to do this correctly. Thanks for helping closing this for now.

**Comment by omri374** [comment]
@apethree one approach we could think of is for the `remove_recognizer` to accept either a string (name) or a recognizer instance.

```python
from typing import Union
from presidio_analyzer import EntityRecognizer

def remove_recognizer(self, recognizer: Union[str, EntityRecognizer]) -> None:
    if isintance(recognizer, str):
        # remove using name
    elif isinstance(recognizer, EntityRecognizer):
        # remove the actual instancce
    else:
        raise ValueError("recognizer should either be of type str (recognizer name) or of type EntityRecognizer")

```
Or something similar to this. Happy to hear your thoughts on whether this would be helpful.
