### ISSUE TITLE
The US ITIN recognizer is missing a range of numbers

### ISSUE THREAD

**Issue by aperezfals** [microsoft/presidio#954]
I was checking for the official IRS format for an ITIN. Extracted from here: 
https://www.irs.gov/pub/irs-pdf/p1915.pdf

The definition of an ITIN is:
>An ITIN is a tax processing number, issued by the Internal Revenue Service, for certain resident and nonresident aliens, their spouses, and their dependents. It is a nine-digit number beginning with the number “9”, has a range of numbers from "50" to "65", "70" to 88", 90” to “92” and “94” to “99” for the fourth and fifth digits and is formatted like a SSN (i.e. 9XX-7X-XXXX).

None of the regular expressions in `UsItinRecognizer` are including the range from 50 to 66 in the fourth and fifth digits.

**Solution**
The range from 50 to 65 can be included in the 3 patterns. Posible regex:
```python
Pattern(
  "Itin (medium)",
  r"\b(9\d{2})[- ]{1}(((5\d)|(6[0-5]))|(7[0-9]{1}|8[0-8]{1})|(9[0-2]{1})|(9[4-9]{1}))[- ]{1}(\d{4})\b",  # noqa: E501
  0.5,
),
```
**Posible improvements to the regex**
- Delete all the {1} quantifiers since by default the preceding expression will be evaluated exactly once
- Delete innecessary groups 
```python
 Pattern(
  "Itin (medium)",
  r"\b9\d{2}[- ](5\d|6[0-5]|7\d|8[0-8]|9([0-2]|[4-9]))[- ]\d{4}\b",  # noqa: E501
  0.5,
),
```

**Comment by omri374** [comment]
Thanks! reviewed and approved the PR.
