### ISSUE TITLE
ValueError: [E088] Text of length 10000000 exceeds maximum of 1000000

### ISSUE THREAD

**Issue by millefalcon** [microsoft/presidio#957]
**`ValueError`: [E088] Text of length 10000000 exceeds maximum of 1000000**
A `ValueError` is raised when the `text` to `AnalyzerEngine().analyze` provided is longer than `1000000` characters.
The default [`max_length`](https://github.com/explosion/spaCy/blob/master/spacy/language.py#L135)  for the language pipeline is `10**6`. Though we can increase the `max_length`, I don't see a way to provide the `max_length` from the `AnalyzerEngine`.

Having said that, I'm not sure how to best handle this. Should we provide a mechanism to allow setting the `max_length` from the `AnalyzerEngine` or maybe it is user's responsibility to chunk the data within the default `max_length`  ?

**To Reproduce**
```python3
$ python3 -m venv .venv
$ .venv/bin/pip install presidio-analyzer
$ .venv/bin/pip install presidio-anonymizer
$ .venv/bin/python -m spacy download en_core_web_lg
$ .venv/bin/python
>>> from presidio_analyzer import AnalyzerEngine
>>> 
>>> text = 'x'*10000000
>>> analyzer = AnalyzerEngine()
>>> supported_entities = ['PERSON', 'EMAIL_ADDRESS','PHONE_NUMBER']
>>> 
>>> 
>>> analyzer_results = analyzer.analyze(text=text, language='en', entities=supported_entities)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cs-1055/python/anonymize/.venv/lib/python3.8/site-packages/presidio_analyzer/analyzer_engine.py", line 189, in analyze
    nlp_artifacts = self.nlp_engine.process_text(text, language)
  File "/home/cs-1055/python/anonymize/.venv/lib/python3.8/site-packages/presidio_analyzer/nlp_engine/spacy_nlp_engine.py", line 44, in process_text
    doc = self.nlp[language](text)
  File "/home/cs-1055/python/anonymize/.venv/lib/python3.8/site-packages/spacy/language.py", line 1014, in __call__
    doc = self._ensure_doc(text)
  File "/home/cs-1055/python/anonymize/.venv/lib/python3.8/site-packages/spacy/language.py", line 1105, in _ensure_doc
    return self.make_doc(doc_like)
  File "/home/cs-1055/python/anonymize/.venv/lib/python3.8/site-packages/spacy/language.py", line 1094, in make_doc
    raise ValueError(
ValueError: [E088] Text of length 10000000 exceeds maximum of 1000000. The parser and NER models require roughly 1GB of temporary memory per 100,000 characters in the input. This means long texts may cause memory allocation errors. If you're not using the parser or NER, it's probably safe to increase the `nlp.max_length` limit. The limit is in number of characters, so you can check whether your inputs are too long by checking `len(text)`.
```

**Expected behavior**
A way to provide the `max_length` and or other config to the underlying model.

**Screenshots**
NA

**Additional context**
Awesome library btw ❤️. Thank you for all the work that are being done. I'm not sure how to best handle the situation here, but since the `analyzer` failed with an exception not directly from the `analyzer`, I thought i'd raise the issue. Maybe this error is good enough for the user, and maybe they can chunk the amount of `text` goes into the `analyzer`.  Please let me know if i need to provide any more information or clarify something.

**Comment by millefalcon** [comment]
There seems to be 2 other similar issues.
https://github.com/microsoft/presidio/issues/935 and https://github.com/microsoft/presidio/issues/938.
And from those I see, the usual thing to do is chunking the text. If that's the way to go for the moment. I think, this issue best be closed ?

**Comment by omri374** [comment]
Hi @millefalcon, yes, regardless of which underlying NER model we're using, there's a limit on text size. You could potentially change the underlying model using the `NlpEngineProvider` and pass the new `NlpEngine` to the analyzer, but I'm not sure this is completely solvable this way. The right thing to do would to chunk the text as you mentioned.
