### ISSUE TITLE
Hebrew Support

### ISSUE THREAD

**Issue by pavsh** [microsoft/presidio#988]
Hi guys,
Since almost all of you like me from Israel i hope you can help me.
Does anybody used presidio for PII with the Hebrew language?
Is there any Recognizers or NPL engines that opened sourced for Hebrew?

**Comment by omri374** [comment]
Hi @pavsh, yes there is! There's this solution which is built on top of Presidio: https://github.com/8400TheHealthNetwork/HebSafeHarbor/

It can also serve as an example for those tackling other languages.
