### ISSUE TITLE
Flair remote recognizer throws `AttributeError`

### ISSUE THREAD

**Issue by mohammed-zia** [microsoft/presidio#992]
**Describe the bug**
When attempting to use Flair as the external recognizer, I get an AttributeError:

```bash
Traceback (most recent call last):
  File "/home/user/Desktop/project/flair_recognizer.py", line 213, in <module>
    results = analyzer.analyze(
  File "/home/user/miniconda3/envs/torch/lib/python3.9/site-packages/presidio_analyzer/analyzer_engine.py", line 204, in analyze
    current_results = recognizer.analyze(
  File "/home/user/Desktop/project/flair_recognizer.py", line 153, in analyze
    flair_result = self._convert_to_recognizer_result(ent, explanation)
  File "/home/user/Desktop/project/flair_recognizer.py", line 166, in _convert_to_recognizer_result
    start=entity.start_pos,
AttributeError: 'Span' object has no attribute 'start_pos'
```
Couldn't find any mention of this in docs or issues, please let me know if I've missed something. That error shows just by running [`flair_recognizer.py`](https://github.com/microsoft/presidio/blob/main/docs/samples/python/flair_recognizer.py) from the official docs.

Interestingly if I edit L168 and 169 to:

```python
start=entity.start_position,
end=entity.end_position,
```
it works fine. I guess this is just disparity in latest version of flair? In which case I may have missed some specific version install that I need. Hopefully this saves someone else the debugging, feel free to close if this isn't the right place. Happy to raise a PR if needed.

**To Reproduce**
1. Go to [`flair_recognizer.py`](https://github.com/microsoft/presidio/blob/main/docs/samples/python/flair_recognizer.py) and clone locally.
2. Run the Python script without modifying the file
3. See error

**Expected behavior**
The script should return analysis info of detections and decision process.

**Additional context**
System Versions:
* Ubuntu 20.04
* Python 3.9.15
* presidio-analyzer==2.2.31
* presidio-anonymizer==2.2.31
* spacy==3.4.4
* spacy-legacy==3.0.10
* spacy-loggers==1.0.4
* flair==0.11.3

**Comment by SharonHart** [comment]
@mohammed-zia  Looking at flair source code, the property should be accessed using start_position and end_position, as you mentioned.
We will be happy if you can raise a PR fixing it, thanks!
