### ISSUE TITLE
Use analyzer without default entities

### ISSUE THREAD

**Issue by hummingbird1989** [microsoft/presidio#995]
In the documentation, it's mentioned that when the AnalyzerEngine is loaded, it loads all available recognizers including the NlpEngine. I was wondering if it's possible to run the analyzer without the NLP entities being detected.

**Comment by navalev** [comment]
Hi @hummingbird1989 you can use the ad_hoc_recognizers parameter to set which recognizers to use

**Comment by omri374** [comment]
Hi @hummingbird1989, if you want to create an `AnalyzerEngine` with no recognizers, you can instantiate the `RecognizerRegistry` this way:
```python
from presidio_analyzer import AnalyzerEngine, RecognizerRegistry

registry = RecognizerRegistry()
analyzer = AnalyzerEngine(registry=registry)
```

This would start Presidio with no loaded recognizers. Then, you could add the ones you're interested in:
```python
analyzer.registry.add_recognizer(my_recognizer)
```

**Comment by hummingbird1989** [comment]
Thanks, @omri374 !

**Comment by shamikbose** [comment]
@omri374 I tried the method shown above to add a custom recognizer that I built similarly to the [CreditCardRecognizer()](https://github.com/microsoft/presidio/blob/main/presidio-analyzer/presidio_analyzer/predefined_recognizers/credit_card_recognizer.py)
Here's the definition for my class
```
class IPRecognizer(PatternRecognizer):
    def __init__(
        self,
        patterns: Optional[List[Pattern]] = None,
        context: Optional[List[Pattern]] = None,
        supported_language: str = "en",
        supported_entity: str = "IP_ADDRESS",
    ):
        patterns = patterns if patterns else self.PATTERNS
        context = (context,)
        super().__init__(
            supported_entity=supported_entity,
            patterns=patterns,
            context=context,
            supported_language=supported_language,
        )
```
When I try to add it to the registry, I get the following error
```
Traceback (most recent call last):
  File "bigcode_pii_presidio.py", line 8, in <module>
    registry.add_recognizer(IPRecognizer)
  File "C:\Anaconda2\envs\pii_detection\lib\site-packages\presidio_analyzer\recognizer_registry\recognizer_registry.py", line 193, in add_recognizer
    raise ValueError("Input is not of type EntityRecognizer")
ValueError: Input is not of type EntityRecognizer
```

What should I change?
